/**
 * 30 天情境對話 —— 龍龍語言教室的核心。
 *
 * 每天一段真的會發生的對話，捷克文為主、英文對照（在布拉格兩種都用得到），
 * 下面的單字**只收這段對話裡出現過的字**，學完就能立刻把整段講出來。
 *
 * 資料用陣列存以求緊湊，載入時才轉成物件：
 *   lines: [說話者, 捷克文, 拼讀, 英文, 中文]
 *   words: [捷克文, 拼讀, 中文, 英文]
 *
 * 順序是照留學時間軸排的（下飛機 → 安頓 → 日常 → 校園 → 疑難雜症），不要隨意調動。
 */

export const DIALOGUE_STAGES = [
  { id: 1, name: '第一週 · 抵達與安頓', range: 'Day 1–7' },
  { id: 2, name: '第二週 · 吃喝與交通', range: 'Day 8–14' },
  { id: 3, name: '第三週 · 校園與社交', range: 'Day 15–21' },
  { id: 4, name: '第四週 · 生活疑難雜症', range: 'Day 22–30' },
];

export const DIALOGUES = [
  {
    day: 1, stage: 1, icon: '👋', scene: '第一次見面',
    goal: '打招呼、說出自己是誰、聽懂對方在問什麼',
    lines: [
      ['A', 'Dobrý den!', 'DOB-ree den', 'Hello!', '您好！'],
      ['B', 'Dobrý den. Jak se jmenujete?', 'yak se YME-nu-ye-te', 'Hello. What is your name?', '您好，您叫什麼名字？'],
      ['A', 'Jmenuju se Josh. A vy?', 'YME-nu-yu se', 'My name is Josh. And you?', '我叫 Josh。您呢？'],
      ['B', 'Já jsem Petra. Odkud jste?', 'OD-kud yste', 'I am Petra. Where are you from?', '我是 Petra。您從哪裡來？'],
      ['A', 'Jsem z Tchaj-wanu.', 'ysem s TCHAY-va-nu', 'I am from Taiwan.', '我來自台灣。'],
      ['B', 'Těší mě!', 'TYE-shee mnye', 'Nice to meet you!', '幸會！'],
      ['A', 'Mě taky. Na shledanou.', 'mnye TA-ki', 'You too. Goodbye.', '我也是。再見。'],
      ['B', 'Jak dlouho tady budete?', 'yak DLOU-ho', 'How long will you be here?', '您會在這裡待多久？'],
      ['A', 'Jeden semestr. Studuju na Karlově univerzitě.', 'na KAR-lo-vye', 'One semester. I study at Charles University.', '一個學期。我在查理大學唸書。'],
      ['B', 'To je super! Mluvíte trochu česky?', 'MLU-vee-te TRO-khu', 'That is great! Do you speak a little Czech?', '太好了！您會說一點捷克語嗎？'],
      ['A', 'Jenom trochu, ale učím se.', 'U-cheem se', 'Only a little, but I am learning.', '只會一點，但我在學。'],
      ['B', 'To je vidět. Držím palce!', 'DR-zheem PAL-tse', 'I can tell. Good luck!', '看得出來。祝你順利！'],
    ],
    words: [
      ['dobrý den', 'DOB-ree den', '您好（正式）', 'hello'],
      ['jak', 'yak', '怎麼、如何', 'how'],
      ['jmenovat se', 'YME-no-vat se', '叫做（名字）', 'to be called'],
      ['a vy?', 'a vi', '您呢？', 'and you?'],
      ['odkud', 'OD-kud', '從哪裡', 'where from'],
      ['jsem', 'ysem', '我是', 'I am'],
      ['z', 's', '從……來', 'from'],
      ['těší mě', 'TYE-shee mnye', '幸會', 'nice to meet you'],
      ['taky', 'TA-ki', '也', 'too / also'],
      ['na shledanou', 'na SKHLE-da-nou', '再見（正式）', 'goodbye'],
      ['učit se', 'U-chit se', '學習', 'to learn'],
      ['držím palce', 'DR-zheem PAL-tse', '祝你好運', 'fingers crossed'],
    ],
    tip: '捷克人講 jmenuju se 是口語、jmenuji se 是書面，兩個都對。第一次見面一律用「您」(vy)。',
  },
  {
    day: 2, stage: 1, icon: '🛂', scene: '機場入境查驗',
    goal: '通過護照查驗，回答停留目的與時間',
    lines: [
      ['官員', 'Dobrý den, váš pas prosím.', 'vaash pas', 'Hello, your passport please.', '您好，請出示護照。'],
      ['你', 'Tady je.', 'TA-di ye', 'Here it is.', '在這裡。'],
      ['官員', 'Jaký je účel vaší cesty?', 'YA-kee ye OO-chel', 'What is the purpose of your trip?', '您此行的目的是什麼？'],
      ['你', 'Jsem student. Budu studovat v Praze.', 'BU-du STU-do-vat', 'I am a student. I will study in Prague.', '我是學生，我要在布拉格唸書。'],
      ['官員', 'Jak dlouho tady zůstanete?', 'yak DLOU-ho', 'How long will you stay here?', '您會待多久？'],
      ['你', 'Jeden semestr, asi pět měsíců.', 'A-si pyet MYE-see-tsoo', 'One semester, about five months.', '一個學期，大約五個月。'],
      ['官員', 'Máte potvrzení o studiu?', 'PO-tvr-ze-nyee', 'Do you have a confirmation of study?', '您有在學證明嗎？'],
      ['你', 'Ano, tady je.', 'A-no', 'Yes, here it is.', '有，在這裡。'],
      ['官員', 'Kde budete bydlet?', 'BID-let', 'Where will you be staying?', '您會住在哪裡？'],
      ['你', 'Na koleji Strahov, mám tu potvrzení.', 'na KO-le-yi', 'At Strahov dorm, I have the confirmation here.', '住 Strahov 宿舍，證明在這。'],
      ['官員', 'Máte zpáteční letenku?', 'ZPAA-tech-nyee LE-ten-ku', 'Do you have a return ticket?', '您有回程機票嗎？'],
      ['你', 'Ano, na leden.', 'na LE-den', 'Yes, for January.', '有，一月的。'],
      ['官員', 'Děkuji. Hezký pobyt v Praze!', 'HEZ-kee PO-bit', 'Thank you. Enjoy your stay in Prague!', '謝謝。祝您在布拉格愉快！'],
    ],
    words: [
      ['pas', 'pas', '護照', 'passport'],
      ['tady', 'TA-di', '這裡', 'here'],
      ['účel', 'OO-chel', '目的', 'purpose'],
      ['cesta', 'TSES-ta', '旅程、路', 'trip / journey'],
      ['budu', 'BU-du', '我將會', 'I will'],
      ['studovat', 'STU-do-vat', '唸書', 'to study'],
      ['jak dlouho', 'yak DLOU-ho', '多久', 'how long'],
      ['zůstat', 'ZOO-stat', '停留', 'to stay'],
      ['měsíc', 'MYE-seets', '月', 'month'],
      ['potvrzení o studiu', 'PO-tvr-ze-nyee o STU-di-yu', '在學證明', 'confirmation of study'],
      ['bydlet', 'BID-let', '居住', 'to stay / live'],
      ['letenka', 'LE-ten-ka', '機票', 'plane ticket'],
    ],
    tip: '在學證明務必印紙本隨身帶，海關與外國人警局都會要。回答「一個學期」比講日期安全。',
  },
  {
    day: 3, stage: 1, icon: '🧳', scene: '領行李與行李遺失',
    goal: '找到行李轉盤，行李沒出來時能求助',
    lines: [
      ['你', 'Promiňte, kde je výdej zavazadel?', 'VEE-dey ZA-va-za-del', 'Excuse me, where is baggage claim?', '不好意思，行李提領處在哪裡？'],
      ['職員', 'Rovně a pak doprava.', 'ROV-nye a pak DO-pra-va', 'Straight ahead and then right.', '直走然後右轉。'],
      ['你', 'Děkuju. … Můj kufr tady není.', 'mooy KU-fr', 'Thank you. … My suitcase is not here.', '謝謝。……我的行李箱不在這裡。'],
      ['職員', 'Máte útržek od zavazadla?', 'OO-tr-zhek', 'Do you have the baggage tag?', '您有行李條嗎？'],
      ['你', 'Ano, tady. Co mám dělat?', 'tso maam DYE-lat', 'Yes, here. What should I do?', '有，在這。我該怎麼辦？'],
      ['職員', 'Vyplňte prosím tento formulář.', 'VI-plnye-te', 'Please fill in this form.', '請填這張表格。'],
      ['你', 'Kdy mi ho doručíte?', 'DO-ru-chee-te', 'When will you deliver it to me?', '你們什麼時候會送來？'],
      ['職員', 'Většinou do dvou dnů.', 'VYET-shi-nou', 'Usually within two days.', '通常兩天內。'],
      ['職員', 'Jakou barvu má váš kufr?', 'YA-kou BAR-vu', 'What colour is your suitcase?', '您的行李箱什麼顏色？'],
      ['你', 'Černý, střední velikost.', 'CHER-nee', 'Black, medium size.', '黑色，中型。'],
      ['職員', 'A vaše telefonní číslo?', 'TE-le-fon-nyee CHEES-lo', 'And your phone number?', '您的電話號碼？'],
      ['你', 'Ještě nemám české číslo, mám jen e-mail.', 'CHES-kee', 'I do not have a Czech number yet, only email.', '我還沒有捷克號碼，只有 email。'],
      ['職員', 'To stačí. Ozveme se vám.', 'OZ-ve-me se', 'That is enough. We will contact you.', '這樣就夠了。我們會聯絡您。'],
    ],
    words: [
      ['výdej zavazadel', 'VEE-dey ZA-va-za-del', '行李提領處', 'baggage claim'],
      ['zavazadlo', 'ZA-va-zad-lo', '行李', 'luggage'],
      ['kufr', 'KU-fr', '行李箱', 'suitcase'],
      ['rovně', 'ROV-nye', '直走', 'straight ahead'],
      ['doprava', 'DO-pra-va', '往右', 'to the right'],
      ['útržek', 'OO-tr-zhek', '存根、行李條', 'tag / stub'],
      ['formulář', 'FOR-mu-laarzh', '表格', 'form'],
      ['vyplnit', 'VI-pl-nyit', '填寫', 'to fill in'],
      ['kdy', 'kdi', '什麼時候', 'when'],
      ['doručit', 'DO-ru-chit', '送達', 'to deliver'],
      ['barva', 'BAR-va', '顏色', 'colour'],
      ['ozvat se', 'OZ-vat se', '聯絡、回覆', 'to get in touch'],
    ],
    tip: 'Co mám dělat?（我該怎麼辦）是所有出狀況場合的萬用句，先背起來。',
  },
  {
    day: 4, stage: 1, icon: '🚌', scene: '從機場進市區',
    goal: '買車票、確認搭哪一班、確認要不要轉車',
    lines: [
      ['你', 'Dobrý den, jak se dostanu do centra?', 'DO-sta-nu do TSEN-tra', 'Hello, how do I get to the centre?', '您好，我要怎麼去市中心？'],
      ['職員', 'Autobusem sto devatenáct a pak metrem.', 'AU-to-bu-sem', 'By bus 119 and then by metro.', '搭 119 號公車，然後轉地鐵。'],
      ['你', 'Kde koupím jízdenku?', 'KOU-peem YEEZ-den-ku', 'Where do I buy a ticket?', '我在哪裡買票？'],
      ['職員', 'Tady v automatu. Devadesát minut stačí.', 'AU-to-ma-tu', 'Here at the machine. Ninety minutes is enough.', '在這台售票機。九十分鐘的票就夠了。'],
      ['你', 'Musím přestoupit?', 'MU-seem PRZHE-stou-pit', 'Do I have to change?', '我需要轉車嗎？'],
      ['職員', 'Ano, na Nádraží Veleslavín.', 'NAA-dra-zhee', 'Yes, at Nádraží Veleslavín.', '要，在 Veleslavín 站。'],
      ['你', 'A musím jízdenku označit?', 'O-zna-chit', 'And do I have to validate the ticket?', '車票需要打票嗎？'],
      ['職員', 'Ano, hned po nástupu.', 'hned po NAA-stu-pu', 'Yes, right after boarding.', '要，一上車就打。'],
      ['你', 'Jak dlouho to trvá do centra?', 'TR-vaa', 'How long does it take to the centre?', '到市中心要多久？'],
      ['職員', 'Asi čtyřicet minut.', 'CHTI-rzhi-tset', 'About forty minutes.', '大約四十分鐘。'],
      ['你', 'A jezdí to i v noci?', 'YEZ-dyee', 'And does it run at night too?', '晚上也有車嗎？'],
      ['職員', 'Metro do půlnoci, pak jezdí noční tramvaje.', 'NOCH-nyee', 'The metro until midnight, then night trams run.', '地鐵開到午夜，之後有夜間電車。'],
      ['你', 'Skvělé, děkuju za pomoc!', 'SKVYE-lee', 'Great, thanks for your help!', '太好了，謝謝您的幫忙！'],
    ],
    words: [
      ['dostat se', 'DO-stat se', '抵達、到得了', 'to get to'],
      ['centrum', 'TSEN-trum', '市中心', 'centre'],
      ['autobus', 'AU-to-bus', '公車', 'bus'],
      ['metro', 'ME-tro', '地鐵', 'metro'],
      ['jízdenka', 'YEEZ-den-ka', '車票', 'ticket'],
      ['automat', 'AU-to-mat', '自動售票機', 'ticket machine'],
      ['stačit', 'STA-chit', '足夠', 'to be enough'],
      ['přestoupit', 'PRZHE-stou-pit', '轉車', 'to change (transport)'],
      ['označit', 'O-zna-chit', '打票、驗證', 'to validate'],
      ['nástup', 'NAA-stup', '上車', 'boarding'],
      ['trvat', 'TR-vat', '花費（時間）', 'to take (time)'],
      ['noční', 'NOCH-nyee', '夜間的', 'night (adj.)'],
    ],
    tip: '沒打票被查到罰 1000 Kč 起跳，而且查票員穿便服。上車第一件事就是把票塞進打票機。',
  },
  {
    day: 5, stage: 1, icon: '🚕', scene: '叫車與確認車資',
    goal: '說出目的地、問價錢、避免被繞路',
    lines: [
      ['你', 'Dobrý den, jedete na Strahov?', 'YE-de-te', 'Hello, do you go to Strahov?', '您好，您有到 Strahov 嗎？'],
      ['司機', 'Ano, nastupte si.', 'NA-stup-te si', 'Yes, get in.', '有，請上車。'],
      ['你', 'Kolik to bude stát?', 'KO-lik to BU-de staat', 'How much will it cost?', '大概多少錢？'],
      ['司機', 'Asi tři sta korun.', 'trzhi sta KO-run', 'About three hundred crowns.', '大約三百克朗。'],
      ['你', 'Můžu platit kartou?', 'PLA-tit KAR-tou', 'Can I pay by card?', '我可以刷卡嗎？'],
      ['司機', 'Samozřejmě.', 'SA-mo-zrzhey-mnye', 'Of course.', '當然可以。'],
      ['你', 'Tady zastavte, prosím. Děkuju!', 'ZA-stav-te', 'Stop here, please. Thank you!', '請在這裡停，謝謝！'],
      ['司機', 'Máte adresu?', 'A-dre-su', 'Do you have the address?', '您有地址嗎？'],
      ['你', 'Ano, Vaníčkova sedm. Ukážu vám to.', 'U-kaa-zhu', 'Yes, Vaníčkova 7. I will show you.', '有，Vaníčkova 7 號。我給您看。'],
      ['司機', 'Dobře. Bude to asi dvacet minut.', 'DVA-tset', 'All right. It will be about twenty minutes.', '好。大概二十分鐘。'],
      ['你', 'Mám kufr, můžete otevřít kufr auta?', 'O-tev-rzheet', 'I have a suitcase, can you open the boot?', '我有行李箱，可以開後車廂嗎？'],
      ['司機', 'Jasně, otevřu.', 'YAS-nye', 'Sure, I will open it.', '當然，我開。'],
    ],
    words: [
      ['jet', 'yet', '（搭車）去', 'to go (by vehicle)'],
      ['nastoupit', 'NA-stou-pit', '上車', 'to get in'],
      ['kolik', 'KO-lik', '多少', 'how much'],
      ['stát', 'staat', '值多少錢', 'to cost'],
      ['koruna', 'KO-ru-na', '克朗', 'crown (CZK)'],
      ['platit', 'PLA-tit', '付錢', 'to pay'],
      ['karta', 'KAR-ta', '卡片', 'card'],
      ['samozřejmě', 'SA-mo-zrzhey-mnye', '當然', 'of course'],
      ['zastavit', 'ZA-sta-vit', '停下', 'to stop'],
      ['tady', 'TA-di', '這裡', 'here'],
      ['adresa', 'A-dre-sa', '地址', 'address'],
      ['ukázat', 'U-kaa-zat', '指給看', 'to show'],
    ],
    tip: '上車前先問 Kolik to bude stát? 布拉格路邊攔的計程車惡名昭彰，用 Bolt / Uber 比較安全。',
  },
  {
    day: 6, stage: 1, icon: '🏠', scene: '宿舍報到',
    goal: '辦入住、拿鑰匙、問基本設施',
    lines: [
      ['你', 'Dobrý den, mám tu rezervaci na kolej.', 'RE-zer-va-tsi', 'Hello, I have a reservation for the dorm.', '您好，我有訂宿舍。'],
      ['櫃檯', 'Vaše jméno a doklad, prosím.', 'YMEE-no', 'Your name and ID, please.', '請給我您的名字和證件。'],
      ['你', 'Josh An, tady je pas.', '', 'Josh An, here is my passport.', 'Josh An，這是護照。'],
      ['櫃檯', 'Máte pokoj číslo tři sta dvanáct.', 'PO-koy CHEES-lo', 'You have room number 312.', '您的房間是 312。'],
      ['你', 'Kde je prádelna a kuchyňka?', 'PRAA-del-na', 'Where is the laundry and the kitchen?', '洗衣間和小廚房在哪裡？'],
      ['櫃檯', 'V přízemí, vedle výtahu.', 'PRZHEE-ze-mee', 'On the ground floor, next to the lift.', '在 0 樓，電梯旁邊。'],
      ['你', 'A wifi? Jaké je heslo?', 'HES-lo', 'And wifi? What is the password?', '那 wifi 呢？密碼是什麼？'],
      ['櫃檯', 'Je to na té kartičce. Tady máte klíč.', 'kleech', 'It is on that card. Here is your key.', '在那張卡片上。這是您的鑰匙。'],
      ['你', 'Do kdy musím kartu vrátit?', 'VRAA-tit', 'By when do I have to return the card?', '卡片什麼時候要還？'],
      ['櫃檯', 'Poslední den pobytu, jinak platíte pokutu.', 'PO-ku-tu', 'The last day of your stay, otherwise you pay a fine.', '住宿最後一天，不然要罰款。'],
      ['你', 'Rozumím. A kde se platí kolej?', 'RO-zu-meem', 'I understand. And where do I pay for the dorm?', '了解。宿舍費在哪裡繳？'],
      ['櫃檯', 'Převodem na účet, pošlu vám údaje mailem.', 'PRZHE-vo-dem', 'By bank transfer, I will email you the details.', '銀行轉帳，我會把資料寄給您。'],
      ['你', 'Výborně, moc děkuju.', 'mots DYE-ku-yu', 'Excellent, thank you very much.', '太好了，非常感謝。'],
    ],
    words: [
      ['rezervace', 'RE-zer-va-tse', '訂位、預訂', 'reservation'],
      ['kolej', 'KO-ley', '學生宿舍', 'dormitory'],
      ['jméno', 'YMEE-no', '名字', 'name'],
      ['doklad', 'DO-klad', '證件', 'ID document'],
      ['pokoj', 'PO-koy', '房間', 'room'],
      ['číslo', 'CHEES-lo', '號碼', 'number'],
      ['prádelna', 'PRAA-del-na', '洗衣間', 'laundry room'],
      ['přízemí', 'PRZHEE-ze-mee', '一樓（地面層）', 'ground floor'],
      ['heslo', 'HES-lo', '密碼', 'password'],
      ['klíč', 'kleech', '鑰匙', 'key'],
      ['vrátit', 'VRAA-tit', '歸還', 'to return'],
      ['pokuta', 'PO-ku-ta', '罰款', 'fine / penalty'],
    ],
    tip: 'přízemí 是地面層（台灣說的一樓），1. patro 才是台灣的二樓。約在「一樓」見面前先講清楚。',
  },
  {
    day: 7, stage: 1, icon: '🔧', scene: '宿舍出問題',
    goal: '報修暖氣、燈、熱水，聽懂對方什麼時候來',
    lines: [
      ['你', 'Dobrý den, nefunguje mi topení.', 'ne-FUN-gu-ye', 'Hello, my heating does not work.', '您好，我的暖氣壞了。'],
      ['管理員', 'Od kdy?', 'od kdi', 'Since when?', '從什麼時候開始？'],
      ['你', 'Od včera večer. Je mi hrozná zima.', 'HROZ-naa ZI-ma', 'Since last night. I am really cold.', '從昨天晚上，我冷死了。'],
      ['管理員', 'Který pokoj?', 'KTE-ree', 'Which room?', '哪一間？'],
      ['你', 'Tři sta dvanáct. A taky neteče teplá voda.', 'ne-TE-che TEP-laa', 'Room 312. And there is no hot water either.', '312。而且也沒有熱水。'],
      ['管理員', 'Přijdu se tam podívat odpoledne.', 'PRZHI-du', 'I will come and look this afternoon.', '我下午過去看。'],
      ['你', 'Můžete přijít po páté? Mám přednášku.', 'po PAA-tee', 'Can you come after five? I have a lecture.', '可以五點後嗎？我有課。'],
      ['管理員', 'Dobře, v šest.', 'DOB-rzhe', 'Fine, at six.', '好，六點。'],
      ['你', 'A ještě jedna věc — nejde wifi.', 'NEY-de', 'And one more thing — the wifi does not work.', '還有一件事——wifi 不能用。'],
      ['管理員', 'Zkusil jste restartovat router?', 'RES-tar-to-vat', 'Have you tried restarting the router?', '您試過重開路由器嗎？'],
      ['你', 'Zkusil, ale nepomohlo to.', 'NE-po-mo-hlo', 'I did, but it did not help.', '試過了，但沒有用。'],
      ['管理員', 'Tak se na to taky podívám.', 'PO-dyee-vaam', 'Then I will look at that too.', '那我也一起看。'],
      ['你', 'Díky moc, jste zachránce.', 'ZA-khraan-tse', 'Thanks a lot, you are a lifesaver.', '太感謝了，你是救星。'],
    ],
    words: [
      ['fungovat', 'FUN-go-vat', '運作、能用', 'to work / function'],
      ['topení', 'TO-pe-nyee', '暖氣', 'heating'],
      ['od kdy', 'od kdi', '從何時起', 'since when'],
      ['včera', 'VCHE-ra', '昨天', 'yesterday'],
      ['zima', 'ZI-ma', '冷、冬天', 'cold / winter'],
      ['který', 'KTE-ree', '哪一個', 'which'],
      ['téct', 'teetst', '流（水）', 'to flow'],
      ['teplá voda', 'TEP-laa VO-da', '熱水', 'hot water'],
      ['přijít', 'PRZHI-yeet', '過來', 'to come'],
      ['odpoledne', 'OD-po-led-ne', '下午', 'afternoon'],
      ['nejde', 'NEY-de', '不能用、行不通', 'does not work'],
      ['pomoct', 'PO-motst', '幫上忙', 'to help'],
    ],
    tip: 'Nefunguje mi …（我的……壞了）套用在任何東西上：nefunguje mi wifi / světlo / sprcha。',
  },
  {
    day: 8, stage: 2, icon: '🛒', scene: '超市採買',
    goal: '找東西、秤重、結帳、拒絕塑膠袋',
    lines: [
      ['你', 'Promiňte, kde najdu rýži?', 'NAY-du REE-zhi', 'Excuse me, where can I find rice?', '不好意思，米在哪裡？'],
      ['店員', 'V pátém regálu vlevo.', 'PAA-teem RE-gaa-lu', 'In the fifth aisle on the left.', '左邊第五排。'],
      ['你', 'Děkuju. A musím zeleninu zvážit?', 'ZVAA-zhit', 'Thanks. Do I have to weigh the vegetables?', '謝謝。蔬菜需要自己秤嗎？'],
      ['店員', 'Ano, tam u váhy.', 'u VAA-hi', 'Yes, over at the scales.', '要，在那邊的磅秤。'],
      ['收銀', 'Máte naši kartičku?', 'NA-shi KAR-tich-ku', 'Do you have our loyalty card?', '您有我們的會員卡嗎？'],
      ['你', 'Ne, děkuju. Tašku nepotřebuju.', 'TASH-ku', 'No, thanks. I do not need a bag.', '沒有，謝謝。我不需要袋子。'],
      ['收銀', 'Bude to dvě stě čtyřicet korun.', 'dvye stye', 'That will be 240 crowns.', '總共 240 克朗。'],
      ['你', 'Platím kartou. Účtenku, prosím.', 'OOCH-ten-ku', 'I will pay by card. Receipt, please.', '我刷卡。請給我收據。'],
      ['你', 'Promiňte, kde máte mléko bez laktózy?', 'bez LAK-too-zi', 'Excuse me, where is the lactose-free milk?', '不好意思，無乳糖牛奶在哪裡？'],
      ['店員', 'V chladicím pultu vzadu.', 'KHLA-dyi-tseem', 'In the fridge at the back.', '後面的冷藏櫃。'],
      ['你', 'Děkuju. Máte ještě čerstvé pečivo?', 'CHER-stvee PE-chi-vo', 'Thanks. Do you still have fresh bread?', '謝謝。還有新鮮麵包嗎？'],
      ['店員', 'Ráno je nejvíc, teď už moc ne.', 'NEY-veets', 'There is most in the morning, not much now.', '早上最多，現在剩不多。'],
      ['你', 'Dobře, přijdu zítra ráno.', 'PRZHI-du', 'All right, I will come tomorrow morning.', '好，我明天早上來。'],
    ],
    words: [
      ['najít', 'NA-yeet', '找到', 'to find'],
      ['rýže', 'REE-zhe', '米', 'rice'],
      ['regál', 'RE-gaal', '貨架、排', 'shelf / aisle'],
      ['vlevo', 'VLE-vo', '在左邊', 'on the left'],
      ['zelenina', 'ZE-le-nyi-na', '蔬菜', 'vegetables'],
      ['zvážit', 'ZVAA-zhit', '秤重', 'to weigh'],
      ['váha', 'VAA-ha', '磅秤', 'scales'],
      ['kartička', 'KAR-tich-ka', '會員小卡', 'loyalty card'],
      ['taška', 'TASH-ka', '袋子', 'bag'],
      ['účtenka', 'OOCH-ten-ka', '收據', 'receipt'],
      ['čerstvý', 'CHER-stvee', '新鮮的', 'fresh'],
      ['pečivo', 'PE-chi-vo', '麵包類', 'baked goods'],
    ],
    tip: '蔬果一定要自己秤重貼標，忘了的話收銀員會請你回去秤，後面會排一排人。',
  },
  {
    day: 9, stage: 2, icon: '☕', scene: '咖啡廳',
    goal: '點飲料、內用外帶、問 wifi、找位子',
    lines: [
      ['你', 'Dobrý den, dám si latte.', 'daam si', 'Hello, I will have a latte.', '您好，我要一杯拿鐵。'],
      ['店員', 'Malé, nebo velké?', 'MA-lee NE-bo VEL-kee', 'Small or large?', '小杯還是大杯？'],
      ['你', 'Velké, prosím. S sebou.', 's SE-bou', 'Large, please. To go.', '大杯，謝謝。外帶。'],
      ['店員', 'Něco k tomu?', 'NYE-tso k TO-mu', 'Anything with that?', '還要別的嗎？'],
      ['你', 'Ne, děkuju. Kolik to dělá?', 'DYE-laa', 'No, thank you. How much is it?', '不用了，謝謝。多少錢？'],
      ['店員', 'Devadesát pět korun.', 'DE-va-de-saat pyet', 'Ninety-five crowns.', '九十五克朗。'],
      ['你', 'Máte wifi? Jaké je heslo?', 'HES-lo', 'Do you have wifi? What is the password?', '有 wifi 嗎？密碼是什麼？'],
      ['店員', 'Je na účtence. Je tu volno vzadu.', 'VOL-no VZA-du', 'It is on the receipt. There is a free seat at the back.', '在收據上。後面有空位。'],
      ['你', 'Máte i něco bez cukru?', 'bez TSU-kru', 'Do you have anything without sugar?', '有無糖的嗎？'],
      ['店員', 'Můžu udělat bez sirupu.', 'SI-ru-pu', 'I can make it without syrup.', '可以不加糖漿。'],
      ['你', 'Super. Můžu tu sedět a učit se?', 'SE-dyet', 'Great. Can I sit here and study?', '太好了。我可以在這裡坐著唸書嗎？'],
      ['店員', 'Jasně, klidně celé odpoledne.', 'KLID-nye', 'Sure, the whole afternoon if you like.', '當然，坐一整個下午都行。'],
      ['你', 'Perfektní, děkuju!', 'PER-fekt-nyee', 'Perfect, thank you!', '太完美了，謝謝！'],
    ],
    words: [
      ['dát si', 'daat si', '我要點（餐廳用）', 'to have (order)'],
      ['malý', 'MA-lee', '小的', 'small'],
      ['velký', 'VEL-kee', '大的', 'large'],
      ['s sebou', 's SE-bou', '外帶', 'to go / takeaway'],
      ['něco', 'NYE-tso', '某個東西', 'something'],
      ['dělat', 'DYE-lat', '做、（總共）算', 'to make / come to'],
      ['heslo', 'HES-lo', '密碼', 'password'],
      ['volno', 'VOL-no', '空著、有空位', 'free / vacant'],
      ['vzadu', 'VZA-du', '在後面', 'at the back'],
      ['nebo', 'NE-bo', '或者', 'or'],
      ['cukr', 'TSU-kr', '糖', 'sugar'],
      ['klidně', 'KLID-nye', '儘管、沒問題', 'feel free'],
    ],
    tip: '「Je tu volno?」（這位子有人嗎）在咖啡廳與啤酒館都超常用，捷克人很習慣併桌。',
  },
  {
    day: 10, stage: 2, icon: '🍽️', scene: '餐廳點餐',
    goal: '入座、看菜單、點餐、說飲食限制',
    lines: [
      ['服務生', 'Dobrý den, kolik vás bude?', 'KO-lik vaas', 'Hello, how many of you?', '您好，幾位？'],
      ['你', 'Dva, prosím. Máte anglický jídelní lístek?', 'YEE-del-nyee LEES-tek', 'Two, please. Do you have an English menu?', '兩位。有英文菜單嗎？'],
      ['服務生', 'Ano. Co si dáte k pití?', 'k PI-tyee', 'Yes. What would you like to drink?', '有。想喝點什麼？'],
      ['你', 'Jedno velké pivo a neperlivou vodu.', 'NE-per-li-vou', 'One large beer and still water.', '一杯大啤酒和一杯無氣泡水。'],
      ['服務生', 'A k jídlu?', 'k YEED-lu', 'And to eat?', '餐點呢？'],
      ['你', 'Dám si svíčkovou. Je v tom maso?', 'SVEECH-ko-vou', 'I will have svíčková. Is there meat in it?', '我要奶醬燉牛肉。裡面有肉嗎？'],
      ['服務生', 'Ano, hovězí.', 'HO-vye-zee', 'Yes, beef.', '有，牛肉。'],
      ['你', 'Dobře. A jednou bez masa, prosím.', 'bez MA-sa', 'Fine. And one without meat, please.', '好。另一份不要肉，謝謝。'],
      ['你', 'Co byste doporučil?', 'DO-po-ru-chil', 'What would you recommend?', '您推薦什麼？'],
      ['服務生', 'Dnes máme výbornou kachnu.', 'KAKH-nu', 'Today we have excellent duck.', '今天的烤鴨很棒。'],
      ['你', 'Jak dlouho to bude trvat?', 'TR-vat', 'How long will it take?', '要等多久？'],
      ['服務生', 'Asi dvacet minut.', 'DVA-tset MI-nut', 'About twenty minutes.', '大約二十分鐘。'],
      ['你', 'To je v pohodě. A ještě jednu vodu, prosím.', 'v PO-ho-dye', 'That is fine. And one more water, please.', '沒問題。再來一杯水，謝謝。'],
    ],
    words: [
      ['jídelní lístek', 'YEE-del-nyee LEES-tek', '菜單', 'menu'],
      ['pití', 'PI-tyee', '飲料', 'drink'],
      ['pivo', 'PI-vo', '啤酒', 'beer'],
      ['neperlivá voda', 'NE-per-li-vaa VO-da', '無氣泡水', 'still water'],
      ['jídlo', 'YEED-lo', '食物、餐點', 'food / dish'],
      ['svíčková', 'SVEECH-ko-vaa', '奶醬燉牛肉（國菜）', 'svíčková (beef in cream sauce)'],
      ['maso', 'MA-so', '肉', 'meat'],
      ['hovězí', 'HO-vye-zee', '牛肉', 'beef'],
      ['bez', 'bez', '沒有、不加', 'without'],
      ['jednou', 'YED-nou', '一份、一次', 'once / one portion'],
      ['doporučit', 'DO-po-ru-chit', '推薦', 'to recommend'],
      ['v pohodě', 'v PO-ho-dye', '沒問題、還好', 'it is fine'],
    ],
    tip: '餐廳的水要錢而且不便宜，啤酒常常比水便宜。想喝自來水說 kohoutková 但很多店不供應。',
  },
  {
    day: 11, stage: 2, icon: '🧾', scene: '結帳與小費',
    goal: '叫服務生結帳、分開付、給小費',
    lines: [
      ['你', 'Zaplatíme, prosím!', 'ZA-pla-tyee-me', 'The bill, please!', '我們要結帳！'],
      ['服務生', 'Dohromady, nebo zvlášť?', 'DO-hro-ma-di / zvlaasht', 'Together or separately?', '一起還是分開？'],
      ['你', 'Zvlášť, prosím.', 'zvlaasht', 'Separately, please.', '分開，謝謝。'],
      ['服務生', 'Vaše je tři sta dvacet korun.', 'trzhi sta DVA-tset', 'Yours is 320 crowns.', '您的是 320 克朗。'],
      ['你', 'Tady je tři sta padesát, to je dobrý.', 'to ye DOB-ree', 'Here is 350, keep the change.', '這裡是 350，不用找了。'],
      ['服務生', 'Děkuju. Chutnalo vám?', 'KHUT-na-lo vaam', 'Thank you. Did you enjoy it?', '謝謝。合胃口嗎？'],
      ['你', 'Bylo to výborné.', 'VEE-bor-nee', 'It was excellent.', '非常好吃。'],
      ['服務生', 'Platíte kartou, nebo hotově?', 'HO-to-vye', 'Are you paying by card or cash?', '刷卡還是付現？'],
      ['你', 'Kartou, prosím.', 'KAR-tou', 'By card, please.', '刷卡，謝謝。'],
      ['服務生', 'Chcete účtenku?', 'OOCH-ten-ku', 'Would you like a receipt?', '需要收據嗎？'],
      ['你', 'Ano, prosím. A ještě jednu otázku — máte tu záchod?', 'ZAA-khod', 'Yes, please. One more question — do you have a toilet?', '要，謝謝。再問一下——這裡有廁所嗎？'],
      ['服務生', 'Vzadu vlevo, kód je na účtence.', 'kood', 'At the back on the left, the code is on the receipt.', '後面左邊，密碼在收據上。'],
    ],
    words: [
      ['zaplatit', 'ZA-pla-tit', '結帳、付清', 'to pay'],
      ['dohromady', 'DO-hro-ma-di', '一起（算）', 'together'],
      ['zvlášť', 'zvlaasht', '分開（算）', 'separately'],
      ['vaše', 'VA-she', '您的', 'yours'],
      ['to je dobrý', 'to ye DOB-ree', '不用找了', 'keep the change'],
      ['chutnat', 'KHUT-nat', '好吃、合胃口', 'to taste good'],
      ['výborný', 'VEE-bor-nee', '極好的', 'excellent'],
      ['bylo', 'BI-lo', '（過去）是', 'it was'],
      ['drobné', 'DROB-nee', '零錢', 'change (coins)'],
      ['spropitné', 'SPRO-pit-nee', '小費', 'tip'],
      ['hotově', 'HO-to-vye', '付現', 'in cash'],
      ['kód', 'kood', '密碼、代碼', 'code'],
    ],
    tip: '小費約 10%：直接說要付的整數金額（例如帳單 320 就說 „Tři sta padesát"），不要把錢留在桌上。',
  },
  {
    day: 12, stage: 2, icon: '🍺', scene: '啤酒館社交',
    goal: '併桌、點第二杯、乾杯、聊幾句',
    lines: [
      ['你', 'Dobrý den, je tu volno?', 'ye tu VOL-no', 'Hello, is this seat free?', '您好，這位子有人嗎？'],
      ['當地人', 'Je, posaďte se.', 'PO-sadye-te se', 'It is, have a seat.', '沒有，請坐。'],
      ['服務生', 'Dáte si pivo?', 'DAA-te si', 'Will you have a beer?', '要來杯啤酒嗎？'],
      ['你', 'Ano, jedno desítku.', 'DE-seet-ku', 'Yes, one ten-degree.', '好，一杯十度的。'],
      ['當地人', 'Na zdraví!', 'na ZDRA-vee', 'Cheers!', '乾杯！'],
      ['你', 'Na zdraví! Odkud jste?', 'OD-kud yste', 'Cheers! Where are you from?', '乾杯！您是哪裡人？'],
      ['當地人', 'Z Brna. A vy jste tu na studiích?', 'na STU-di-yeekh', 'From Brno. And you are here to study?', '布爾諾。您是來唸書的嗎？'],
      ['你', 'Ano, na jeden semestr. Ještě jedno, prosím!', 'YESH-tye YED-no', 'Yes, for one semester. One more, please!', '對，一個學期。再一杯，謝謝！'],
      ['當地人', 'Jak se ti tu líbí?', 'LEE-bee', 'How do you like it here?', '你喜歡這裡嗎？'],
      ['你', 'Moc! Jenom je tu zima.', 'ZI-ma', 'A lot! It is just cold here.', '很喜歡！只是有點冷。'],
      ['當地人', 'To ještě není nic, počkej na leden.', 'POCH-key', 'This is nothing, wait for January.', '這還好，等一月你就知道了。'],
      ['你', 'To se bojím. Zaplatíme?', 'BO-yeem', 'I am afraid of that. Shall we pay?', '我怕。要不要結帳？'],
      ['當地人', 'Jo, a příště pozvu já.', 'POZ-vu', 'Yeah, and next time it is on me.', '好，下次我請。'],
    ],
    words: [
      ['volno', 'VOL-no', '有空位', 'free seat'],
      ['posadit se', 'PO-sa-dyit se', '坐下', 'to sit down'],
      ['desítka', 'DE-seet-ka', '十度啤酒（較淡）', 'ten-degree beer'],
      ['na zdraví', 'na ZDRA-vee', '乾杯', 'cheers'],
      ['ještě', 'YESH-tye', '還、再', 'still / one more'],
      ['jeden', 'YE-den', '一個', 'one'],
      ['studia', 'STU-di-ya', '學業', 'studies'],
      ['semestr', 'SE-mes-tr', '學期', 'semester'],
      ['Brno', 'BR-no', '布爾諾（第二大城）', 'Brno'],
      ['prosím', 'PRO-seem', '請、麻煩了', 'please'],
      ['líbit se', 'LEE-bit se', '喜歡', 'to like'],
      ['pozvat', 'POZ-vat', '請客、邀請', 'to invite / treat'],
    ],
    tip: '碰杯時要看著對方的眼睛，不然傳說會倒楣七年。desítka（10°）比 dvanáctka（12°）淡，看酒精濃度不是溫度。',
  },
  {
    day: 13, stage: 2, icon: '🎫', scene: '辦長期票 Lítačka',
    goal: '辦學生月票，聽懂需要什麼文件',
    lines: [
      ['你', 'Dobrý den, chtěl bych studentskou jízdenku.', 'STU-dent-skou', 'Hello, I would like a student travel pass.', '您好，我想辦學生月票。'],
      ['職員', 'Máte potvrzení o studiu a fotku?', 'FOT-ku', 'Do you have a confirmation of study and a photo?', '您有在學證明和照片嗎？'],
      ['你', 'Ano, tady. Kolik to stojí na měsíc?', 'na MYE-seets', 'Yes, here. How much is it per month?', '有，在這。一個月多少錢？'],
      ['職員', 'Sto třicet korun, do dvaceti šesti let.', 'do DVA-tse-ti', 'A hundred thirty crowns, up to age 26.', '130 克朗，26 歲以下。'],
      ['你', 'Můžu ji nabít online?', 'NA-beet', 'Can I top it up online?', '可以線上加值嗎？'],
      ['職員', 'Ano, na webu nebo v aplikaci.', 'A-pli-ka-tsi', 'Yes, on the website or in the app.', '可以，在網站或 app。'],
      ['你', 'Kdy si ji můžu vyzvednout?', 'VI-zved-nout', 'When can I pick it up?', '我什麼時候能領？'],
      ['職員', 'Za týden.', 'za TEE-den', 'In a week.', '一週後。'],
      ['你', 'Musím mít u sebe průkaz?', 'PROO-kaz', 'Do I have to carry the card with me?', '我需要隨身帶證件嗎？'],
      ['職員', 'Ano, revizoři to kontrolují.', 'KON-tro-lu-yee', 'Yes, inspectors check it.', '要，查票員會查。'],
      ['你', 'A co když ji ztratím?', 'ZTRA-tyeem', 'And what if I lose it?', '如果弄丟了呢？'],
      ['職員', 'Zablokujeme ji a vystavíme novou.', 'VI-sta-vee-me', 'We will block it and issue a new one.', '我們會停用並補發新的。'],
      ['你', 'Rozumím, děkuju za informace.', 'IN-for-ma-tse', 'Understood, thanks for the information.', '了解，謝謝您的說明。'],
    ],
    words: [
      ['chtěl bych', 'KHTYEL bikh', '我想要（禮貌）', 'I would like'],
      ['studentský', 'STU-dent-skee', '學生的', 'student (adj.)'],
      ['fotka', 'FOT-ka', '照片', 'photo'],
      ['stát', 'staat', '值多少', 'to cost'],
      ['měsíc', 'MYE-seets', '月', 'month'],
      ['let', 'let', '歲（年的複數）', 'years (age)'],
      ['nabít', 'NA-beet', '加值、充電', 'to top up / charge'],
      ['aplikace', 'A-pli-ka-tse', '應用程式', 'app'],
      ['vyzvednout', 'VI-zved-nout', '領取', 'to pick up'],
      ['týden', 'TEE-den', '週', 'week'],
      ['průkaz', 'PROO-kaz', '證件、卡證', 'card / ID'],
      ['kontrolovat', 'KON-tro-lo-vat', '檢查', 'to check'],
    ],
    tip: '26 歲以下的學生月票便宜到不可思議，落地第一週就去辦，帶護照＋在學證明＋大頭照。',
  },
  {
    day: 14, stage: 2, icon: '🚋', scene: '在電車上問路',
    goal: '確認方向、問下車站、被查票時應對',
    lines: [
      ['你', 'Promiňte, jede tahle tramvaj na Malostranskou?', 'TA-hle TRAM-vay', 'Excuse me, does this tram go to Malostranská?', '不好意思，這班電車有到 Malostranská 嗎？'],
      ['乘客', 'Ne, musíte jet opačným směrem.', 'O-pach-neem SMYE-rem', 'No, you have to go the opposite way.', '沒有，您要搭反方向。'],
      ['你', 'Aha. Kde mám vystoupit?', 'VI-stou-pit', 'I see. Where should I get off?', '原來如此。我要在哪站下車？'],
      ['乘客', 'Na příští zastávce přestupte.', 'PRZHEESH-tyee ZA-staav-tse', 'Change at the next stop.', '下一站轉車。'],
      ['你', 'Děkuju moc!', 'mots', 'Thank you very much!', '非常感謝！'],
      ['查票員', 'Revizor, jízdenku prosím.', 'RE-vi-zor', 'Ticket inspector, ticket please.', '查票，請出示車票。'],
      ['你', 'Tady, mám měsíční kupón.', 'MYE-seech-nyee KU-poon', 'Here, I have a monthly pass.', '在這，我有月票。'],
      ['查票員', 'V pořádku, děkuju.', 'v PO-rzhaad-ku', 'All right, thank you.', '沒問題，謝謝。'],
      ['你', 'Kolik zastávek to je?', 'ZA-staa-vek', 'How many stops is it?', '還有幾站？'],
      ['乘客', 'Tři, pak uvidíte hrad.', 'U-vi-dyee-te', 'Three, then you will see the castle.', '三站，然後您會看到城堡。'],
      ['你', 'Super. Jezdí ta linka často?', 'LIN-ka', 'Great. Does that line run often?', '太好了。那條線班次多嗎？'],
      ['乘客', 'Ve špičce každých pět minut.', 'SHPICH-tse', 'Every five minutes at rush hour.', '尖峰時間每五分鐘一班。'],
      ['你', 'Výborně, ještě jednou díky.', 'YED-nou', 'Excellent, thanks again.', '太好了，再次謝謝。'],
    ],
    words: [
      ['tahle', 'TA-hle', '這個（陰性）', 'this'],
      ['tramvaj', 'TRAM-vay', '路面電車', 'tram'],
      ['opačný směr', 'O-pach-nee smyer', '反方向', 'opposite direction'],
      ['vystoupit', 'VI-stou-pit', '下車', 'to get off'],
      ['příští', 'PRZHEESH-tyee', '下一個', 'next'],
      ['zastávka', 'ZA-staav-ka', '站牌', 'stop'],
      ['přestoupit', 'PRZHE-stou-pit', '轉車', 'to change'],
      ['revizor', 'RE-vi-zor', '查票員', 'ticket inspector'],
      ['kupón', 'KU-poon', '長期票', 'pass'],
      ['v pořádku', 'v PO-rzhaad-ku', '沒問題', 'all right'],
      ['zastávka', 'ZA-staav-ka', '站', 'stop'],
      ['špička', 'SHPICH-ka', '尖峰時間', 'rush hour'],
    ],
    tip: '「Vystupujete?」（您要下車嗎）是擠向門口時的必備句，別默默硬擠。',
  },
  {
    day: 15, stage: 3, icon: '🚆', scene: '火車站買票',
    goal: '買到別的城市的票、確認月台與轉車',
    lines: [
      ['你', 'Dobrý den, jednu zpáteční do Brna.', 'ZPAA-tech-nyee', 'Hello, one return ticket to Brno.', '您好，一張到布爾諾的來回票。'],
      ['售票員', 'Na kdy?', 'na kdi', 'For when?', '什麼時候的？'],
      ['你', 'Zítra ráno, kolem osmé.', 'KO-lem OS-mee', 'Tomorrow morning, around eight.', '明天早上，八點左右。'],
      ['售票員', 'V osm deset, máte studentskou slevu?', 'SLE-vu', 'At 8:10, do you have a student discount?', '八點十分。您有學生折扣嗎？'],
      ['你', 'Ano, tady je ISIC.', '', 'Yes, here is my ISIC.', '有，這是我的 ISIC。'],
      ['售票員', 'Bude to dvě stě korun. Nástupiště tři.', 'NAA-stu-pish-tye', 'That is 200 crowns. Platform three.', '200 克朗。三號月台。'],
      ['你', 'Musím přestupovat?', 'PRZHE-stu-po-vat', 'Do I have to change trains?', '需要轉車嗎？'],
      ['售票員', 'Ne, je to přímý spoj.', 'PRZHEE-mee spoy', 'No, it is a direct connection.', '不用，是直達車。'],
      ['你', 'Můžu si to místo rezervovat?', 'RE-zer-vo-vat', 'Can I reserve a seat?', '可以劃位嗎？'],
      ['售票員', 'Za třicet korun navíc.', 'NA-veets', 'For thirty crowns extra.', '加 30 克朗。'],
      ['你', 'Dobře, chci místo u okna.', 'u OK-na', 'All right, I want a window seat.', '好，我要靠窗。'],
      ['售票員', 'Vagón čtyři, místo dvacet dva.', 'VA-goon', 'Carriage four, seat twenty-two.', '四號車廂，22 號座位。'],
      ['你', 'Děkuju moc, na shledanou.', '', 'Thank you very much, goodbye.', '非常感謝，再見。'],
    ],
    words: [
      ['zpáteční', 'ZPAA-tech-nyee', '來回（票）', 'return (ticket)'],
      ['jednosměrná', 'YED-no-smyer-naa', '單程（票）', 'one-way'],
      ['na kdy', 'na kdi', '什麼時候的', 'for when'],
      ['zítra', 'ZEE-tra', '明天', 'tomorrow'],
      ['kolem', 'KO-lem', '大約、左右', 'around'],
      ['sleva', 'SLE-va', '折扣', 'discount'],
      ['nástupiště', 'NAA-stu-pish-tye', '月台', 'platform'],
      ['přestupovat', 'PRZHE-stu-po-vat', '轉車', 'to change trains'],
      ['přímý spoj', 'PRZHEE-mee spoy', '直達車', 'direct connection'],
      ['odjezd', 'OD-yezd', '發車', 'departure'],
      ['rezervovat', 'RE-zer-vo-vat', '預訂、劃位', 'to reserve'],
      ['okno', 'OK-no', '窗戶', 'window'],
    ],
    tip: 'ISIC 國際學生證在捷克到處都能打折，火車、博物館、電影院都吃。',
  },
  {
    day: 16, stage: 3, icon: '🗺️', scene: '迷路問路',
    goal: '手機沒電時問到路、聽懂方向指示',
    lines: [
      ['你', 'Promiňte, ztratil jsem se.', 'ZTRA-tyil ysem se', 'Excuse me, I am lost.', '不好意思，我迷路了。'],
      ['路人', 'Kam chcete jít?', 'kam KHTSE-te', 'Where do you want to go?', '您要去哪裡？'],
      ['你', 'Hledám tuhle adresu.', 'HLE-daam TU-hle A-dre-su', 'I am looking for this address.', '我在找這個地址。'],
      ['路人', 'Jděte rovně a na semaforu doleva.', 'SE-ma-fo-ru DO-le-va', 'Go straight and turn left at the lights.', '直走，在紅綠燈左轉。'],
      ['你', 'Je to daleko?', 'DA-le-ko', 'Is it far?', '很遠嗎？'],
      ['路人', 'Asi deset minut pěšky.', 'PYESH-ki', 'About ten minutes on foot.', '走路大約十分鐘。'],
      ['你', 'Můžete mi to ukázat na mapě?', 'U-kaa-zat na MA-pye', 'Can you show me on the map?', '可以在地圖上指給我看嗎？'],
      ['路人', 'Jasně, tady jste a tady je to.', 'YAS-nye', 'Sure, you are here and it is here.', '當然，您在這，那裡是這。'],
      ['你', 'A je tam někde bankomat?', 'BAN-ko-mat', 'And is there a cash machine somewhere there?', '那附近有提款機嗎？'],
      ['路人', 'Hned vedle vchodu do metra.', 'VKHO-du', 'Right next to the metro entrance.', '就在地鐵入口旁邊。'],
      ['你', 'Skvělé. Mockrát děkuju za pomoc.', 'MOTS-kraat', 'Great. Thanks a lot for your help.', '太好了。非常感謝您的幫忙。'],
      ['路人', 'Není zač, hezký den!', 'NE-nyee zach', 'You are welcome, have a nice day!', '不客氣，祝您有美好的一天！'],
      ['你', 'Vám taky!', 'vaam TA-ki', 'You too!', '您也是！'],
    ],
    words: [
      ['ztratit se', 'ZTRA-tyit se', '迷路', 'to get lost'],
      ['kam', 'kam', '去哪裡', 'where to'],
      ['hledat', 'HLE-dat', '尋找', 'to look for'],
      ['adresa', 'A-dre-sa', '地址', 'address'],
      ['jít', 'yeet', '走、去', 'to go / walk'],
      ['semafor', 'SE-ma-for', '紅綠燈', 'traffic lights'],
      ['doleva', 'DO-le-va', '往左', 'to the left'],
      ['daleko', 'DA-le-ko', '遠', 'far'],
      ['pěšky', 'PYESH-ki', '走路', 'on foot'],
      ['mapa', 'MA-pa', '地圖', 'map'],
      ['bankomat', 'BAN-ko-mat', '提款機', 'cash machine'],
      ['vchod', 'vkhod', '入口', 'entrance'],
    ],
    tip: '女生說 Ztratila jsem se。捷克語的過去式會分性別，這個差別在每一句過去式裡都會遇到。',
  },
  {
    day: 17, stage: 3, icon: '🏫', scene: '學校國際處報到',
    goal: '報到、交文件、拿學生證',
    lines: [
      ['你', 'Dobrý den, jsem výměnný student.', 'VEE-myen-nee', 'Hello, I am an exchange student.', '您好，我是交換學生。'],
      ['職員', 'Vítejte! Máte Learning Agreement?', 'VEE-tey-te', 'Welcome! Do you have your Learning Agreement?', '歡迎！您有 Learning Agreement 嗎？'],
      ['你', 'Ano, a tady je pas a vízum.', 'VEE-zum', 'Yes, and here is my passport and visa.', '有，這是護照和簽證。'],
      ['職員', 'Výborně. Vyplňte prosím tento formulář.', 'VEE-bor-nye', 'Great. Please fill in this form.', '很好。請填這張表。'],
      ['你', 'Kdy dostanu studentskou kartu?', 'DO-sta-nu', 'When will I get my student card?', '我什麼時候拿到學生證？'],
      ['職員', 'Dnes odpoledne, ve druhém patře.', 've DRU-heem PAT-rzhe', 'This afternoon, on the second floor.', '今天下午，在二樓。'],
      ['你', 'A kde najdu svůj rozvrh?', 'ROZ-vrh', 'And where do I find my timetable?', '我的課表在哪裡看？'],
      ['職員', 'V systému SIS, přihlásíte se kartou.', 'PRZHI-hlaa-see-te', 'In the SIS system, you log in with the card.', '在 SIS 系統，用卡片登入。'],
      ['你', 'Kdy začíná semestr?', 'ZA-chee-naa', 'When does the semester start?', '學期什麼時候開始？'],
      ['職員', 'Přednášky začínají příští pondělí.', 'PRZHEESH-tyee', 'Lectures start next Monday.', '下週一開始上課。'],
      ['你', 'A je nějaká orientace pro cizince?', 'O-ri-en-ta-tse', 'And is there an orientation for foreigners?', '有給外國人的說明會嗎？'],
      ['職員', 'Ve čtvrtek v deset, v aule.', 'AU-le', 'On Thursday at ten, in the auditorium.', '星期四十點，在大禮堂。'],
      ['你', 'Přijdu, děkuju!', 'PRZHI-du', 'I will come, thank you!', '我會去，謝謝！'],
    ],
    words: [
      ['výměnný student', 'VEE-myen-nee STU-dent', '交換學生', 'exchange student'],
      ['vítejte', 'VEE-tey-te', '歡迎', 'welcome'],
      ['vízum', 'VEE-zum', '簽證', 'visa'],
      ['vyplnit', 'VI-pl-nyit', '填寫', 'to fill in'],
      ['dostat', 'DO-stat', '拿到、收到', 'to get'],
      ['studentská karta', 'STU-dent-skaa KAR-ta', '學生證', 'student card'],
      ['patro', 'PAT-ro', '樓層', 'floor'],
      ['rozvrh', 'ROZ-vrh', '課表', 'timetable'],
      ['systém', 'SIS-teem', '系統', 'system'],
      ['přihlásit se', 'PRZHI-hlaa-sit se', '登入、報到', 'to log in / register'],
      ['začínat', 'ZA-chee-nat', '開始', 'to begin'],
      ['cizinec', 'TSI-zi-nets', '外國人', 'foreigner'],
    ],
    tip: '報到當天把所有紙本一次帶齊：護照、簽證、Learning Agreement、在學證明、保險、大頭照。',
  },
  {
    day: 18, stage: 3, icon: '📚', scene: '選課與加簽',
    goal: '問課還能不能加、上課語言、考試方式',
    lines: [
      ['你', 'Dobrý den, můžu se ještě zapsat na tenhle předmět?', 'ZA-psat', 'Hello, can I still register for this course?', '您好，這門課我還能加選嗎？'],
      ['教授', 'Kolik máte kreditů?', 'KRE-di-too', 'How many credits do you have?', '您修了幾學分？'],
      ['你', 'Zatím dvacet. Je ta přednáška v angličtině?', 'v AN-glich-tyi-nye', 'Twenty so far. Is that lecture in English?', '目前二十。那堂課是英文授課嗎？'],
      ['教授', 'Ano, celá v angličtině.', 'TSE-laa', 'Yes, entirely in English.', '是，全英文。'],
      ['你', 'Jak vypadá zkouška?', 'VI-pa-daa ZKOUSH-ka', 'What is the exam like?', '考試怎麼考？'],
      ['教授', 'Ústní, ale nejdřív musíte získat zápočet.', 'OOST-nyee / ZAA-po-chet', 'Oral, but first you need the zápočet.', '口試，但要先拿到平時認證。'],
      ['你', 'Co pro zápočet potřebuju?', 'PO-trzhe-bu-yu', 'What do I need for the zápočet?', '平時認證需要什麼？'],
      ['教授', 'Docházku a jednu seminárku.', 'DO-khaaz-ku', 'Attendance and one seminar paper.', '出席和一份報告。'],
      ['你', 'Kdy je termín odevzdání?', 'O-dev-zdaa-nyee', 'When is the submission deadline?', '什麼時候要交？'],
      ['教授', 'Do konce semestru, tedy do ledna.', 'KON-tse', 'By the end of the semester, so by January.', '學期末，也就是一月前。'],
      ['你', 'Můžu psát anglicky?', 'psaat', 'Can I write in English?', '我可以用英文寫嗎？'],
      ['教授', 'Samozřejmě, pro výměnné studenty ano.', 'VEE-myen-nee', 'Of course, for exchange students yes.', '當然，交換生可以。'],
      ['你', 'Děkuju, to mi hodně pomůže.', 'PO-moo-zhe', 'Thank you, that helps me a lot.', '謝謝，這幫了我大忙。'],
    ],
    words: [
      ['zapsat se', 'ZA-psat se', '選課、註冊', 'to register / enrol'],
      ['předmět', 'PRZHED-myet', '科目', 'course / subject'],
      ['kredit', 'KRE-dit', '學分', 'credit'],
      ['přednáška', 'PRZHED-naash-ka', '講堂課', 'lecture'],
      ['angličtina', 'AN-glich-tyi-na', '英文', 'English (language)'],
      ['zkouška', 'ZKOUSH-ka', '考試', 'exam'],
      ['ústní', 'OOST-nyee', '口頭的', 'oral'],
      ['zápočet', 'ZAA-po-chet', '平時學分認證', 'course credit (prerequisite)'],
      ['docházka', 'DO-khaaz-ka', '出席', 'attendance'],
      ['seminárka', 'SE-mi-naar-ka', '學期報告', 'seminar paper'],
      ['odevzdání', 'O-dev-zdaa-nyee', '繳交', 'submission'],
      ['konec', 'KO-nets', '結束、末尾', 'end'],
    ],
    tip: '捷克大學是兩關制：先過 zápočet（出席＋作業）才有資格考 zkouška（多半口試），交換生最常在這裡踩雷。',
  },
  {
    day: 19, stage: 3, icon: '🙋', scene: '跟教授談延期',
    goal: '禮貌開口、說明原因、談出替代方案',
    lines: [
      ['你', 'Dobrý den, můžu se na něco zeptat?', 'ZE-ptat', 'Hello, may I ask something?', '您好，我可以請教一件事嗎？'],
      ['教授', 'Jistě, povídejte.', 'PO-vee-dey-te', 'Sure, go ahead.', '當然，請說。'],
      ['你', 'Chtěl bych požádat o odklad seminárky.', 'OD-klad', 'I would like to ask for an extension.', '我想申請報告延期。'],
      ['教授', 'Z jakého důvodu?', 'DOO-vo-du', 'For what reason?', '什麼原因？'],
      ['你', 'Byl jsem nemocný celý týden.', 'NE-mots-nee', 'I was ill for a whole week.', '我病了一整週。'],
      ['教授', 'Dobře. Do kdy to zvládnete?', 'ZVLAAD-ne-te', 'All right. By when can you manage?', '好。您什麼時候能交？'],
      ['你', 'Do příštího pondělí, pokud to jde.', 'PO-kud to yde', 'By next Monday, if that is possible.', '如果可以的話，下週一。'],
      ['教授', 'Souhlasím. Pošlete mi to e-mailem.', 'SOU-hla-seem', 'Agreed. Send it to me by email.', '同意。用 email 寄給我。'],
      ['你', 'Mám poslat i lékařskou zprávu?', 'LEE-karzh-skou', 'Should I also send a doctor\'s note?', '需要附醫生證明嗎？'],
      ['教授', 'Nemusíte, věřím vám.', 'VYE-rzheem', 'You do not have to, I believe you.', '不用，我相信您。'],
      ['你', 'Děkuju za pochopení.', 'PO-kho-pe-nyee', 'Thank you for your understanding.', '謝謝您的體諒。'],
      ['教授', 'Hlavně se dejte do pořádku.', 'DEY-te se', 'Mainly, get better.', '最重要的是把身體養好。'],
      ['你', 'Budu se snažit. Na shledanou.', 'SNA-zhit', 'I will try. Goodbye.', '我會努力。再見。'],
    ],
    words: [
      ['zeptat se', 'ZE-ptat se', '詢問', 'to ask'],
      ['jistě', 'YIS-tye', '當然', 'certainly'],
      ['požádat o', 'PO-zhaa-dat o', '申請、請求', 'to request'],
      ['odklad', 'OD-klad', '延期', 'postponement'],
      ['důvod', 'DOO-vod', '原因', 'reason'],
      ['nemocný', 'NE-mots-nee', '生病的', 'ill'],
      ['do kdy', 'do kdi', '在什麼時候之前', 'by when'],
      ['zvládnout', 'ZVLAAD-nout', '做得完、應付得來', 'to manage'],
      ['pokud', 'PO-kud', '如果', 'if'],
      ['souhlasit', 'SOU-hla-sit', '同意', 'to agree'],
      ['zpráva', 'ZPRAA-va', '報告、證明、訊息', 'report / note'],
      ['pochopení', 'PO-kho-pe-nyee', '體諒', 'understanding'],
    ],
    tip: 'Chtěl(a) bych požádat o… 是所有正式請求的開頭：延期、證明、加簽都用它。女生要說 Chtěla。',
  },
  {
    day: 20, stage: 3, icon: '💬', scene: '跟同學閒聊',
    goal: '打開話題、交換聯絡方式、約下次',
    lines: [
      ['你', 'Ahoj, ty jsi taky na výměně?', 'na VEE-mnye-nye', 'Hi, are you on exchange too?', '嗨，你也是交換生嗎？'],
      ['同學', 'Jo, z Německa. A ty?', 'z NYE-mets-ka', 'Yeah, from Germany. And you?', '對，從德國來。你呢？'],
      ['你', 'Z Tchaj-wanu. Jak dlouho tu jsi?', 'yak DLOU-ho', 'From Taiwan. How long have you been here?', '台灣。你來多久了？'],
      ['同學', 'Dva týdny. Bydlíš taky na koleji?', 'BID-leesh', 'Two weeks. Do you also live in the dorm?', '兩週。你也住宿舍嗎？'],
      ['你', 'Jo, na Strahově. Nedáme si někdy kafe?', 'NE-daa-me si', 'Yeah, at Strahov. Shall we get coffee sometime?', '對，Strahov。要不要改天喝咖啡？'],
      ['同學', 'Jasně! Máš Instagram?', 'YAS-nye', 'Sure! Are you on Instagram?', '好啊！你有 IG 嗎？'],
      ['你', 'Mám, napíšu ti.', 'NA-pee-shu ti', 'I do, I will message you.', '有，我傳給你。'],
      ['同學', 'Super, tak zatím!', 'tak ZA-tyeem', 'Great, see you!', '讚，那先這樣！'],
      ['同學', 'Co studuješ?', 'STU-du-yesh', 'What do you study?', '你讀什麼？'],
      ['你', 'Informatiku. A ty?', 'IN-for-ma-ti-ku', 'Computer science. And you?', '資訊。你呢？'],
      ['同學', 'Ekonomii. Nechceš jít v pátek na pivo?', 'E-ko-no-mi-yi', 'Economics. Want to go for a beer on Friday?', '經濟。週五要不要去喝一杯？'],
      ['你', 'Rád! Kam pudem?', 'PU-dem', 'Gladly! Where shall we go?', '好啊！要去哪？'],
      ['同學', 'Znám dobrou hospodu kousek odsud.', 'KOU-sek OD-sud', 'I know a good pub near here.', '我知道附近有間不錯的酒館。'],
    ],
    words: [
      ['ahoj', 'A-hoy', '嗨（朋友）', 'hi'],
      ['výměna', 'VEE-mnye-na', '交換', 'exchange'],
      ['Německo', 'NYE-mets-ko', '德國', 'Germany'],
      ['bydlet', 'BID-let', '住', 'to live'],
      ['někdy', 'NYEK-di', '改天、有時候', 'sometime'],
      ['kafe', 'KA-fe', '咖啡（口語）', 'coffee (colloquial)'],
      ['jasně', 'YAS-nye', '當然、沒問題', 'sure'],
      ['napsat', 'NA-psat', '寫、傳訊息', 'to write / message'],
      ['zatím', 'ZA-tyeem', '先這樣、暫時', 'see you / for now'],
      ['super', 'SU-per', '太好了', 'great'],
      ['informatika', 'IN-for-ma-ti-ka', '資訊科學', 'computer science'],
      ['kousek odsud', 'KOU-sek OD-sud', '離這不遠', 'near here'],
    ],
    tip: '同輩之間一律 tykat（用 ty）。Tak zatím! 是朋友之間最自然的道別，比 Na shledanou 輕鬆。',
  },
  {
    day: 21, stage: 3, icon: '📅', scene: '邀約與婉拒',
    goal: '提出邀約、婉拒但保留下次、重新約時間',
    lines: [
      ['朋友', 'Nechceš jít v pátek na koncert?', 'NE-khtsesh', 'Do you want to go to a concert on Friday?', '週五要不要去聽演唱會？'],
      ['你', 'Rád bych, ale v pátek nemůžu.', 'raad bikh', 'I would love to, but I cannot on Friday.', '我很想去，但週五不行。'],
      ['朋友', 'Proč? Co děláš?', 'proch', 'Why? What are you doing?', '為什麼？你要做什麼？'],
      ['你', 'Mám zkoušku v pondělí, musím se učit.', 'U-chit', 'I have an exam on Monday, I need to study.', '我週一有考試，得唸書。'],
      ['朋友', 'Aha, tak jindy.', 'YIN-di', 'I see, another time then.', '這樣啊，那改天。'],
      ['你', 'Co takhle příští víkend?', 'TAK-hle', 'How about next weekend?', '下週末怎麼樣？'],
      ['朋友', 'To by šlo. V sobotu?', 'to bi shlo', 'That could work. Saturday?', '可以喔。星期六？'],
      ['你', 'Platí. Dej mi vědět kdy.', 'PLA-tyee', 'Deal. Let me know when.', '就這麼說定。再跟我說時間。'],
      ['朋友', 'V kolik se sejdeme?', 'SEY-de-me', 'What time shall we meet?', '我們幾點見？'],
      ['你', 'Co třeba v sedm před metrem?', 'TRZHE-ba', 'How about seven in front of the metro?', '七點在地鐵站前如何？'],
      ['朋友', 'Sedí. Vezmu s sebou kamarádku.', 'SE-dyee', 'Works. I will bring a friend.', '可以。我帶一個朋友來。'],
      ['你', 'Super, těším se!', 'TYE-sheem se', 'Great, looking forward to it!', '太好了，很期待！'],
      ['朋友', 'Já taky, tak v pátek!', '', 'Me too, see you Friday!', '我也是，週五見！'],
    ],
    words: [
      ['nechceš', 'NE-khtsesh', '你不想……嗎（邀約）', 'do you want to'],
      ['rád bych', 'raad bikh', '我很想（但……）', 'I would like to'],
      ['nemůžu', 'NE-moo-zhu', '我不行、我不能', 'I cannot'],
      ['učit se', 'U-chit se', '唸書', 'to study'],
      ['jindy', 'YIN-di', '改天', 'another time'],
      ['co takhle', 'tso TAK-hle', '……怎麼樣？', 'how about'],
      ['víkend', 'VEE-kend', '週末', 'weekend'],
      ['sobota', 'SO-bo-ta', '星期六', 'Saturday'],
      ['platí', 'PLA-tyee', '說定了', 'deal / it is on'],
      ['dát vědět', 'daat VYE-dyet', '通知一聲', 'to let know'],
      ['sejít se', 'SE-yeet se', '碰面', 'to meet up'],
      ['těšit se', 'TYE-shit se', '期待', 'to look forward to'],
    ],
    tip: '婉拒的公式：Rád bych, ale…（我很想，但是……）＋ 原因 ＋ Co takhle…?（改約）。直接說 Ne 會顯得很冷。',
  },
  {
    day: 22, stage: 4, icon: '📱', scene: '辦手機門號',
    goal: '買 SIM 卡、問資費、開通',
    lines: [
      ['你', 'Dobrý den, potřebuju SIM kartu s daty.', 'SIM KAR-tu s DA-ti', 'Hello, I need a SIM card with data.', '您好，我需要有網路的 SIM 卡。'],
      ['店員', 'Předplacenou, nebo tarif?', 'PRZHED-pla-tse-nou', 'Prepaid or a contract?', '預付卡還是月租？'],
      ['你', 'Předplacenou, budu tu jen půl roku.', 'pool RO-ku', 'Prepaid, I am only here for half a year.', '預付卡，我只待半年。'],
      ['店員', 'Kolik dat potřebujete?', 'KO-lik dat', 'How much data do you need?', '您需要多少數據？'],
      ['你', 'Aspoň deset gigabajtů měsíčně.', 'AS-ponye', 'At least ten gigabytes a month.', '一個月至少十 GB。'],
      ['店員', 'Máme balíček za dvě stě padesát.', 'BA-lee-chek', 'We have a package for 250.', '我們有 250 的方案。'],
      ['你', 'Dobře. Musím se registrovat?', 'RE-gis-tro-vat', 'Good. Do I have to register?', '好。需要實名登記嗎？'],
      ['店員', 'Ano, ukažte prosím pas.', 'U-kazh-te', 'Yes, please show your passport.', '要，請出示護照。'],
      ['你', 'Jak dlouho trvá aktivace?', 'AK-ti-va-tse', 'How long does activation take?', '開通要多久？'],
      ['店員', 'Do dvou hodin.', 'do dvou HO-dyin', 'Within two hours.', '兩小時內。'],
      ['你', 'A můžu volat do zahraničí?', 'ZA-hra-nyi-chee', 'And can I call abroad?', '可以打國際電話嗎？'],
      ['店員', 'V EU zdarma, mimo EU se připlácí.', 'PRZHI-plaa-tsee', 'Free in the EU, outside the EU costs extra.', '歐盟內免費，歐盟外要加錢。'],
      ['你', 'Rozumím, to mi stačí. Děkuju.', 'STA-chee', 'Understood, that is enough for me. Thanks.', '了解，這樣就夠了。謝謝。'],
    ],
    words: [
      ['potřebovat', 'PO-trzhe-bo-vat', '需要', 'to need'],
      ['předplacená', 'PRZHED-pla-tse-naa', '預付的', 'prepaid'],
      ['tarif', 'TA-rif', '資費方案', 'tariff / plan'],
      ['data', 'DA-ta', '行動網路數據', 'data'],
      ['půl roku', 'pool RO-ku', '半年', 'half a year'],
      ['aspoň', 'AS-ponye', '至少', 'at least'],
      ['měsíčně', 'MYE-seech-nye', '每月', 'monthly'],
      ['balíček', 'BA-lee-chek', '方案、包裹', 'package'],
      ['registrovat se', 'RE-gis-tro-vat se', '登記', 'to register'],
      ['ukázat', 'U-kaa-zat', '出示', 'to show'],
      ['aktivace', 'AK-ti-va-tse', '開通', 'activation'],
      ['zahraničí', 'ZA-hra-nyi-chee', '國外', 'abroad'],
    ],
    tip: '捷克的預付卡要實名登記（帶護照）。三大電信 O2、Vodafone、T-Mobile，學生方案問一下常有優惠。',
  },
  {
    day: 23, stage: 4, icon: '🏦', scene: '銀行開戶',
    goal: '開學生帳戶、問手續費、拿金融卡',
    lines: [
      ['你', 'Dobrý den, chtěl bych si založit studentský účet.', 'ZA-lo-zhit OO-chet', 'Hello, I would like to open a student account.', '您好，我想開學生帳戶。'],
      ['行員', 'Jaké doklady máte?', 'YA-kee DO-kla-di', 'What documents do you have?', '您有哪些文件？'],
      ['你', 'Pas, vízum a potvrzení o studiu.', '', 'Passport, visa and confirmation of study.', '護照、簽證和在學證明。'],
      ['行員', 'A potvrzení o adrese?', 'o A-dre-se', 'And proof of address?', '地址證明呢？'],
      ['你', 'Mám potvrzení z koleje.', 'z KO-le-ye', 'I have a confirmation from the dorm.', '我有宿舍開的證明。'],
      ['行員', 'Výborně. Vedení účtu je zdarma.', 'VE-de-nyee / ZDAR-ma', 'Great. The account has no monthly fee.', '很好。帳戶管理費免費。'],
      ['你', 'Kdy dostanu kartu?', 'KAR-tu', 'When will I get the card?', '我什麼時候拿到卡？'],
      ['行員', 'Pošleme ji do týdne na vaši adresu.', 'PO-shle-me', 'We will send it within a week to your address.', '一週內寄到您的地址。'],
      ['你', 'Je k tomu i mobilní aplikace?', 'MO-bil-nyee', 'Is there a mobile app for it?', '有手機 app 嗎？'],
      ['行員', 'Ano, stáhněte si ji a přihlaste se.', 'STAAH-nye-te', 'Yes, download it and log in.', '有，下載後登入即可。'],
      ['你', 'A poplatky za výběr z bankomatu?', 'VEE-byer', 'And fees for ATM withdrawals?', '提款手續費呢？'],
      ['行員', 'U našich bankomatů zdarma.', 'NA-shikh', 'Free at our ATMs.', '在我們的提款機免費。'],
      ['你', 'Výborně, děkuju za pomoc.', '', 'Excellent, thanks for your help.', '太好了，謝謝您的幫忙。'],
    ],
    words: [
      ['založit', 'ZA-lo-zhit', '開立、設立', 'to open / set up'],
      ['účet', 'OO-chet', '帳戶、帳單', 'account / bill'],
      ['doklad', 'DO-klad', '證件、文件', 'document'],
      ['adresa', 'A-dre-sa', '地址', 'address'],
      ['potvrzení', 'PO-tvr-ze-nyee', '證明', 'confirmation'],
      ['vedení účtu', 'VE-de-nyee OO-chtu', '帳戶管理費', 'account maintenance'],
      ['zdarma', 'ZDAR-ma', '免費', 'free of charge'],
      ['poslat', 'PO-slat', '寄送', 'to send'],
      ['do týdne', 'do TEED-ne', '一週內', 'within a week'],
      ['poplatek', 'PO-pla-tek', '手續費', 'fee'],
      ['stáhnout', 'STAAH-nout', '下載', 'to download'],
      ['výběr', 'VEE-byer', '提款', 'withdrawal'],
    ],
    tip: '地址證明最常見的就是宿舍或房東開的紙本。開戶前先問清楚要不要預約（objednat se）。',
  },
  {
    day: 24, stage: 4, icon: '👮', scene: '外國人警局登記',
    goal: '辦居留登記、聽懂還缺什麼、問下一步',
    lines: [
      ['你', 'Dobrý den, potřebuju se přihlásit k pobytu.', 'k PO-bi-tu', 'Hello, I need to register my stay.', '您好，我需要辦居留登記。'],
      ['職員', 'Máte objednávku na termín?', 'OB-yed-naav-ku', 'Do you have an appointment?', '您有預約嗎？'],
      ['你', 'Ano, na desátou hodinu.', 'DE-saa-tou', 'Yes, for ten o\'clock.', '有，十點。'],
      ['職員', 'Pas, vízum, potvrzení o ubytování a pojištění.', 'U-bi-to-vaa-nyee', 'Passport, visa, proof of accommodation and insurance.', '護照、簽證、住宿證明和保險。'],
      ['你', 'Tady je všechno. Něco chybí?', 'KHI-bee', 'Here is everything. Is anything missing?', '都在這裡。有缺什麼嗎？'],
      ['職員', 'Chybí kopie pasu. Můžete si ji udělat vedle.', 'KO-pi-ye', 'A copy of the passport is missing. You can make one next door.', '缺護照影本，隔壁可以印。'],
      ['你', 'Dobře. Co mám udělat pak?', 'pak', 'All right. What should I do afterwards?', '好。之後我要做什麼？'],
      ['職員', 'Počkejte, až vás zavoláme.', 'POCH-key-te', 'Wait until we call you.', '等我們叫您。'],
      ['職員', 'Vyplňte tuhle žádost, prosím.', 'ZHAA-dost', 'Fill in this application, please.', '請填這份申請書。'],
      ['你', 'Můžu se zeptat, co mám napsat sem?', 'NA-psat', 'May I ask what I should write here?', '請問這欄要填什麼？'],
      ['職員', 'Adresu ubytování v Praze.', 'U-bi-to-vaa-nyee', 'Your address in Prague.', '您在布拉格的住址。'],
      ['你', 'A kdy dostanu potvrzení?', 'PO-tvr-ze-nyee', 'And when will I get the confirmation?', '什麼時候拿到證明？'],
      ['職員', 'Hned, jakmile to zpracujeme.', 'ZPRA-tsu-ye-me', 'Right away, once we process it.', '我們處理完馬上給。'],
    ],
    words: [
      ['přihlásit se k pobytu', 'PRZHI-hlaa-sit se k PO-bi-tu', '辦居留登記', 'to register a stay'],
      ['objednávka', 'OB-yed-naav-ka', '預約', 'appointment'],
      ['termín', 'TER-meen', '時段、期限', 'appointment slot'],
      ['ubytování', 'U-bi-to-vaa-nyee', '住宿', 'accommodation'],
      ['pojištění', 'PO-yish-tye-nyee', '保險', 'insurance'],
      ['všechno', 'VSHEKH-no', '全部', 'everything'],
      ['chybět', 'KHI-byet', '缺少', 'to be missing'],
      ['kopie', 'KO-pi-ye', '影本', 'copy'],
      ['pak', 'pak', '然後', 'then'],
      ['počkat', 'POCH-kat', '等待', 'to wait'],
      ['žádost', 'ZHAA-dost', '申請書', 'application'],
      ['napsat', 'NA-psat', '寫', 'to write'],
    ],
    tip: '非歐盟學生抵達後通常 3 個工作天內要報到。所有文件都多印一份影本，捷克機關對紙本的執著超乎想像。',
  },
  {
    day: 25, stage: 4, icon: '💊', scene: '藥局買成藥',
    goal: '描述症狀、買到對的藥、問怎麼吃',
    lines: [
      ['你', 'Dobrý den, máte něco na bolest v krku?', 'BO-lest v KR-ku', 'Hello, do you have something for a sore throat?', '您好，有治喉嚨痛的藥嗎？'],
      ['藥師', 'Máte i teplotu?', 'TEP-lo-tu', 'Do you also have a fever?', '有發燒嗎？'],
      ['你', 'Trochu, asi sedmatřicet osm.', 'TRO-khu', 'A bit, about 37.8.', '有一點，大概 37.8。'],
      ['藥師', 'Zkuste tyhle pastilky a hodně pijte.', 'PAS-til-ki', 'Try these lozenges and drink a lot.', '試試這個含片，多喝水。'],
      ['你', 'Kolikrát denně?', 'KO-li-kraat DEN-nye', 'How many times a day?', '一天幾次？'],
      ['藥師', 'Třikrát denně po jídle.', 'TRZHI-kraat / po YEED-le', 'Three times a day after meals.', '一天三次，飯後。'],
      ['你', 'Je to na předpis?', 'na PRZHED-pis', 'Is it on prescription?', '需要處方箋嗎？'],
      ['藥師', 'Ne, volně prodejné.', 'VOL-nye PRO-dey-nee', 'No, over the counter.', '不用，是成藥。'],
      ['你', 'Máte i něco na rýmu?', 'REE-mu', 'Do you have something for a runny nose too?', '有治流鼻水的嗎？'],
      ['藥師', 'Tyhle kapky do nosu.', 'KAP-ki', 'These nose drops.', '這個鼻噴劑。'],
      ['你', 'Můžu to brát dohromady?', 'braat', 'Can I take them together?', '可以一起吃嗎？'],
      ['藥師', 'Ano, ale hodně odpočívejte.', 'OD-po-chee-vey-te', 'Yes, but rest a lot.', '可以，但要多休息。'],
      ['你', 'Budu. Kolik to dělá?', '', 'I will. How much is it?', '我會的。多少錢？'],
    ],
    words: [
      ['bolest', 'BO-lest', '疼痛', 'pain'],
      ['krk', 'krk', '喉嚨、脖子', 'throat / neck'],
      ['teplota', 'TEP-lo-ta', '體溫、發燒', 'temperature / fever'],
      ['trochu', 'TRO-khu', '一點點', 'a bit'],
      ['zkusit', 'ZKU-sit', '試試看', 'to try'],
      ['pastilka', 'PAS-til-ka', '含片', 'lozenge'],
      ['kolikrát', 'KO-li-kraat', '幾次', 'how many times'],
      ['denně', 'DEN-nye', '每天', 'daily'],
      ['předpis', 'PRZHED-pis', '處方箋', 'prescription'],
      ['volně prodejné', 'VOL-nye PRO-dey-nee', '成藥（免處方）', 'over the counter'],
      ['rýma', 'REE-ma', '流鼻水', 'runny nose'],
      ['odpočívat', 'OD-po-chee-vat', '休息', 'to rest'],
    ],
    tip: '藥要去 lékárna，drogerie（dm、Rossmann）只賣洗髮精日用品。Bolí mě …（我……痛）套用在任何部位。',
  },
  {
    day: 26, stage: 4, icon: '🩺', scene: '看醫生',
    goal: '掛號、說明症狀與過敏、聽懂醫囑',
    lines: [
      ['你', 'Dobrý den, jsem tu poprvé, jsem student.', 'PO-prvee', 'Hello, this is my first visit, I am a student.', '您好，我第一次來，我是學生。'],
      ['護理師', 'Kartičku pojišťovny, prosím.', 'PO-yish-tyov-ni', 'Your insurance card, please.', '請給我保險卡。'],
      ['醫生', 'Co vás trápí?', 'TRAA-pee', 'What is troubling you?', '哪裡不舒服？'],
      ['你', 'Bolí mě břicho už tři dny.', 'BRZHI-kho', 'My stomach has hurt for three days.', '我肚子痛三天了。'],
      ['醫生', 'Máte na něco alergii?', 'A-ler-gi-yi', 'Are you allergic to anything?', '您對什麼過敏嗎？'],
      ['你', 'Na penicilin.', '', 'To penicillin.', '盤尼西林。'],
      ['醫生', 'Předepíšu vám něco jiného.', 'PRZHE-de-pee-shu', 'I will prescribe you something else.', '我開別的藥給您。'],
      ['你', 'Děkuju. Můžu chodit do školy?', 'KHO-dit', 'Thank you. Can I go to school?', '謝謝。我可以去上課嗎？'],
      ['醫生', 'Kdy to začalo?', 'ZA-cha-lo', 'When did it start?', '什麼時候開始的？'],
      ['你', 'V pondělí, po jídle v menze.', 'MEN-ze', 'On Monday, after eating in the canteen.', '星期一，在學生餐廳吃完之後。'],
      ['醫生', 'Zvracel jste?', 'ZVRA-tsel', 'Have you vomited?', '有吐嗎？'],
      ['你', 'Ne, jenom mě bolí břicho.', 'BO-lee', 'No, my stomach just hurts.', '沒有，只是肚子痛。'],
      ['醫生', 'Dobře. Pijte hodně vody a přijďte za tři dny.', 'PRZHI-dye-te', 'All right. Drink lots of water and come back in three days.', '好。多喝水，三天後回診。'],
    ],
    words: [
      ['poprvé', 'PO-prvee', '第一次', 'for the first time'],
      ['pojišťovna', 'PO-yish-tyov-na', '保險公司', 'insurance company'],
      ['trápit', 'TRAA-pit', '困擾、不適', 'to trouble'],
      ['bolí mě', 'BO-lee mnye', '我……痛', 'it hurts'],
      ['břicho', 'BRZHI-kho', '肚子', 'stomach'],
      ['alergie', 'A-ler-gi-ye', '過敏', 'allergy'],
      ['předepsat', 'PRZHE-de-psat', '開藥', 'to prescribe'],
      ['jiný', 'YI-nee', '別的', 'other / different'],
      ['chodit', 'KHO-dit', '（經常）去', 'to go regularly'],
      ['dny', 'dni', '天（複數）', 'days'],
      ['začít', 'ZA-cheet', '開始', 'to start'],
      ['zvracet', 'ZVRA-tset', '嘔吐', 'to vomit'],
    ],
    tip: '全歐緊急電話 112 可以講英文。看醫生前先確認診所收不收你的保險（VZP 或商業保險）。',
  },
  {
    day: 27, stage: 4, icon: '📮', scene: '郵局寄包裹',
    goal: '寄包裹回台灣、問運費與時間',
    lines: [
      ['你', 'Dobrý den, chci poslat balík na Tchaj-wan.', 'BA-leek', 'Hello, I want to send a parcel to Taiwan.', '您好，我要寄包裹到台灣。'],
      ['職員', 'Kolik to váží?', 'VAA-zhee', 'How much does it weigh?', '多重？'],
      ['你', 'Asi dvě kila.', 'dvye KI-la', 'About two kilos.', '大約兩公斤。'],
      ['職員', 'Vyplňte celní prohlášení.', 'TSEL-nyee PRO-hlaa-she-nyee', 'Fill in the customs declaration.', '請填海關申報單。'],
      ['你', 'Kolik to bude stát a jak dlouho to potrvá?', 'PO-tr-vaa', 'How much will it cost and how long will it take?', '多少錢？要多久？'],
      ['職員', 'Osm set korun, asi tři týdny.', 'osm set', 'Eight hundred crowns, about three weeks.', '八百克朗，大約三週。'],
      ['你', 'Můžu to sledovat online?', 'SLE-do-vat', 'Can I track it online?', '可以線上追蹤嗎？'],
      ['職員', 'Ano, tady máte podací číslo.', 'PO-da-tsee CHEES-lo', 'Yes, here is your tracking number.', '可以，這是掛號號碼。'],
      ['你', 'Máte krabici na prodej?', 'KRA-bi-tsi', 'Do you sell boxes?', '有賣紙箱嗎？'],
      ['職員', 'Ano, tahle velikost stojí čtyřicet.', 'VE-li-kost', 'Yes, this size costs forty.', '有，這個尺寸 40 塊。'],
      ['你', 'Vezmu si ji. A pojistit to můžu?', 'PO-yis-tit', 'I will take it. And can I insure it?', '我要一個。可以保險嗎？'],
      ['職員', 'Můžete, do pěti tisíc korun.', 'PYE-ti TYI-seets', 'You can, up to five thousand crowns.', '可以，最高五千克朗。'],
      ['你', 'Tak ano, prosím.', '', 'Yes then, please.', '那就保，謝謝。'],
    ],
    words: [
      ['poslat', 'PO-slat', '寄送', 'to send'],
      ['balík', 'BA-leek', '包裹', 'parcel'],
      ['vážit', 'VAA-zhit', '重（多少）', 'to weigh'],
      ['kilo', 'KI-lo', '公斤', 'kilo'],
      ['celní prohlášení', 'TSEL-nyee PRO-hlaa-she-nyee', '海關申報單', 'customs declaration'],
      ['potrvat', 'PO-tr-vat', '需要多久', 'to take (time)'],
      ['sledovat', 'SLE-do-vat', '追蹤', 'to track'],
      ['podací číslo', 'PO-da-tsee CHEES-lo', '掛號號碼', 'tracking number'],
      ['známka', 'ZNAAM-ka', '郵票', 'stamp'],
      ['obálka', 'O-baal-ka', '信封', 'envelope'],
      ['krabice', 'KRA-bi-tse', '紙箱', 'box'],
      ['pojistit', 'PO-yis-tit', '投保', 'to insure'],
    ],
    tip: 'Česká pošta 常常大排長龍，先在 app 上抽號碼牌。寄回台灣填 celní prohlášení 是必要的。',
  },
  {
    day: 28, stage: 4, icon: '💇', scene: '剪頭髮',
    goal: '說明要剪多短、避免剪壞',
    lines: [
      ['你', 'Dobrý den, chtěl bych ostříhat.', 'O-strzhee-hat', 'Hello, I would like a haircut.', '您好，我想剪頭髮。'],
      ['理髮師', 'Máte objednáno?', 'OB-yed-naa-no', 'Do you have an appointment?', '您有預約嗎？'],
      ['你', 'Nemám, můžu počkat.', 'NE-maam', 'I do not, I can wait.', '沒有，我可以等。'],
      ['理髮師', 'Jak krátce to chcete?', 'KRAAT-tse', 'How short do you want it?', '要剪多短？'],
      ['你', 'Po stranách nakrátko, nahoře nechte delší.', 'na KRAAT-ko', 'Short on the sides, leave it longer on top.', '兩側短一點，上面留長。'],
      ['理髮師', 'A ofinu?', 'O-fi-nu', 'And the fringe?', '瀏海呢？'],
      ['你', 'Jenom trochu zkrátit, prosím.', 'ZKRAA-tit', 'Just trim it a little, please.', '稍微修一下就好。'],
      ['理髮師', 'Takhle je to dobrý?', 'TAK-hle', 'Is it good like this?', '這樣可以嗎？'],
      ['理髮師', 'Chcete umýt vlasy?', 'U-meet VLA-si', 'Do you want a wash?', '要洗頭嗎？'],
      ['你', 'Ano, prosím.', '', 'Yes, please.', '好，麻煩了。'],
      ['理髮師', 'A vzadu strojkem?', 'STROY-kem', 'And with clippers at the back?', '後面用電推嗎？'],
      ['你', 'Ano, ale ne moc nakrátko.', 'na KRAAT-ko', 'Yes, but not too short.', '好，但不要太短。'],
      ['理髮師', 'Jasně. Kolik to dělá? Čtyři sta.', '', 'Sure. How much is it? Four hundred.', '沒問題。多少錢？四百。'],
    ],
    words: [
      ['ostříhat', 'O-strzhee-hat', '剪髮', 'to cut hair'],
      ['objednáno', 'OB-yed-naa-no', '已預約', 'booked'],
      ['počkat', 'POCH-kat', '等', 'to wait'],
      ['krátce', 'KRAAT-tse', '短地', 'short'],
      ['po stranách', 'po STRA-naakh', '兩側', 'on the sides'],
      ['nahoře', 'NA-ho-rzhe', '上面', 'on top'],
      ['delší', 'DEL-shee', '比較長', 'longer'],
      ['ofina', 'O-fi-na', '瀏海', 'fringe / bangs'],
      ['zkrátit', 'ZKRAA-tit', '剪短、修短', 'to shorten'],
      ['takhle', 'TAK-hle', '這樣', 'like this'],
      ['umýt', 'U-meet', '洗', 'to wash'],
      ['strojek', 'STRO-yek', '電推剪', 'clippers'],
    ],
    tip: 'Jenom trochu（只要一點點）是保命符。剪壞在異鄉特別痛，講不清楚就直接給照片看。',
  },
  {
    day: 29, stage: 4, icon: '🏨', scene: '週末旅行訂房',
    goal: '訂房、確認入住時間、寄放行李',
    lines: [
      ['你', 'Dobrý den, máte volný pokoj na víkend?', 'VOL-nee PO-koy', 'Hello, do you have a room free for the weekend?', '您好，週末有空房嗎？'],
      ['櫃檯', 'Pro kolik osob?', 'O-sob', 'For how many people?', '幾位？'],
      ['你', 'Pro dva, na dvě noci.', 'na dvye NO-tsi', 'For two, for two nights.', '兩位，兩晚。'],
      ['櫃檯', 'Máme dvoulůžkový za tisíc dvě stě za noc.', 'DVOU-loozh-ko-vee', 'We have a double for 1200 a night.', '有雙人房，一晚 1200。'],
      ['你', 'Je v ceně snídaně?', 'v TSE-nye SNYEE-da-nye', 'Is breakfast included?', '含早餐嗎？'],
      ['櫃檯', 'Ano, od sedmi do desíti.', 'od SED-mi', 'Yes, from seven to ten.', '含，七點到十點。'],
      ['你', 'V kolik je check-in? Můžeme nechat zavazadla?', 'NE-khat', 'What time is check-in? Can we leave our luggage?', '幾點可以入住？可以先寄放行李嗎？'],
      ['櫃檯', 'Od dvou. Zavazadla si nechte tady.', 'od dvou', 'From two. Leave your luggage here.', '兩點後。行李放這裡。'],
      ['你', 'Je v okolí něco k jídlu?', 'O-ko-lee', 'Is there anywhere to eat nearby?', '附近有吃的嗎？'],
      ['櫃檯', 'Hned naproti je hospoda.', 'NA-pro-ti', 'There is a pub right opposite.', '對面就有一間酒館。'],
      ['你', 'Skvělé. A v kolik je check-out?', '', 'Great. And what time is check-out?', '太好了。退房幾點？'],
      ['櫃檯', 'Do jedenácti.', 'YE-de-naats-ti', 'By eleven.', '十一點前。'],
      ['你', 'Dobře, děkuju. Dobrou noc!', '', 'All right, thank you. Good night!', '好，謝謝。晚安！'],
    ],
    words: [
      ['volný', 'VOL-nee', '空的、有空的', 'free / vacant'],
      ['osoba', 'O-so-ba', '人（單位）', 'person'],
      ['noc', 'nots', '夜、晚', 'night'],
      ['dvoulůžkový', 'DVOU-loozh-ko-vee', '雙人房的', 'double (room)'],
      ['cena', 'TSE-na', '價格', 'price'],
      ['snídaně', 'SNYEE-da-nye', '早餐', 'breakfast'],
      ['v ceně', 'v TSE-nye', '含在價格內', 'included'],
      ['nechat', 'NE-khat', '留下、寄放', 'to leave'],
      ['zavazadlo', 'ZA-va-zad-lo', '行李', 'luggage'],
      ['od', 'od', '從……起', 'from'],
      ['okolí', 'O-ko-lee', '附近', 'surroundings'],
      ['naproti', 'NA-pro-ti', '對面', 'opposite'],
    ],
    tip: '布拉格出發 4 小時內可到維也納、德勒斯登、克拉科夫。RegioJet／FlixBus 常比火車便宜很多。',
  },
  {
    day: 30, stage: 4, icon: '🎓', scene: '道別與保持聯絡',
    goal: '完整表達感謝、道別、約下次見',
    lines: [
      ['你', 'Zítra odlétám domů.', 'OD-lee-taam DO-moo', 'I fly home tomorrow.', '我明天飛回家。'],
      ['朋友', 'Už? To uteklo rychle.', 'U-tek-lo RIKH-le', 'Already? That went fast.', '這麼快？時間過好快。'],
      ['你', 'Moc děkuju za všechno.', 'mots DYE-ku-yu', 'Thank you so much for everything.', '真的很謝謝你的一切。'],
      ['朋友', 'Bylo super tě poznat.', 'PO-znat', 'It was great to get to know you.', '認識你真的很棒。'],
      ['你', 'Budeme v kontaktu, napíšu ti.', 'v KON-tak-tu', 'We will stay in touch, I will message you.', '我們保持聯絡，我會傳訊息給你。'],
      ['朋友', 'Určitě! A přijeď zase.', 'PRZHI-yedye', 'Definitely! And come again.', '一定！要再來喔。'],
      ['你', 'Přijedu. Měj se hezky!', 'myey se HEZ-ki', 'I will. Take care!', '我會的。保重！'],
      ['朋友', 'Ty taky. Šťastnou cestu!', 'SHTYAST-nou TSES-tu', 'You too. Have a safe trip!', '你也是。一路順風！'],
      ['朋友', 'Napiš, až přistaneš.', 'PRZHI-sta-nesh', 'Text me when you land.', '降落了跟我說一聲。'],
      ['你', 'Určitě napíšu.', '', 'I definitely will.', '一定會。'],
      ['朋友', 'A příští rok přijeď zase, jo?', 'PRZHEESH-tyee rok', 'And come again next year, yeah?', '明年再來，好嗎？'],
      ['你', 'Slibuju. Bylo to nejlepší půl roku.', 'SLI-bu-yu', 'I promise. It was the best half year.', '我保證。這是最棒的半年。'],
      ['朋友', 'Opatruj se. Ahoj!', 'O-pa-truy se', 'Take care. Bye!', '保重。掰！'],
    ],
    words: [
      ['odlétat', 'OD-lee-tat', '起飛、飛走', 'to fly away'],
      ['domů', 'DO-moo', '回家', 'home(wards)'],
      ['utéct', 'U-teetst', '（時間）飛逝', 'to run away / fly by'],
      ['za všechno', 'za VSHEKH-no', '為了一切', 'for everything'],
      ['poznat', 'PO-znat', '認識', 'to get to know'],
      ['kontakt', 'KON-takt', '聯絡', 'contact'],
      ['určitě', 'UR-chi-tye', '一定', 'definitely'],
      ['přijet', 'PRZHI-yet', '（搭車）再來', 'to come again'],
      ['měj se hezky', 'myey se HEZ-ki', '保重', 'take care'],
      ['šťastnou cestu', 'SHTYAST-nou TSES-tu', '一路順風', 'have a safe trip'],
      ['přistát', 'PRZHI-staat', '降落', 'to land'],
      ['slíbit', 'SLEE-bit', '保證、答應', 'to promise'],
    ],
    tip: 'Šťastnou cestu! 是送人出發時的固定說法。捷克人道別時很常用 Měj se（保重），比 Na shledanou 溫暖。',
  },
];

const pad = (n) => String(n).padStart(2, '0');

/**
 * 展開成畫面與音檔用的格式。
 * id 直接當音檔檔名（public/audio/<id>.m4a），所以只能有 [a-z0-9-]。
 */
export const DIALOGUE_DAYS = DIALOGUES.map((entry) => {
  const base = `dlg-${pad(entry.day)}`;
  return {
    ...entry,
    id: base,
    stageName: DIALOGUE_STAGES.find((s) => s.id === entry.stage)?.name || '',
    lines: entry.lines.map(([who, cs, pron, en, zh], index) => ({
      who,
      cs,
      pron,
      en,
      zh,
      csId: `${base}-l${index}`,
      enId: `${base}-l${index}-en`,
    })),
    words: entry.words.map(([term, pron, zh, en], index) => ({
      id: `${base}-w${index}`,
      lang: 'cs',
      term,
      pron,
      zh,
      en,
      enId: `${base}-w${index}-en`,
      cat: entry.scene,
    })),
  };
});

export const TOTAL_DIALOGUE_DAYS = DIALOGUE_DAYS.length;

export function getDialogueDay(day) {
  const clamped = Math.min(Math.max(Number(day) || 1, 1), TOTAL_DIALOGUE_DAYS);
  return DIALOGUE_DAYS[clamped - 1];
}

/** 所有對話單字攤平，給測驗與收藏查表用 */
export const DIALOGUE_WORDS = DIALOGUE_DAYS.flatMap((d) => d.words);

/** 第一個還沒完成的天數 */
export function firstUnfinishedDialogue(doneDays) {
  const done = new Set(Array.isArray(doneDays) ? doneDays : []);
  for (let day = 1; day <= TOTAL_DIALOGUE_DAYS; day += 1) {
    if (!done.has(day)) return day;
  }
  return 1;
}
