/**
 * 英文 100 課文法（基礎 → 留學實戰）。與捷克文課程同一天並行。
 * 每課：{ id, stage, title, summary, body, examples:[[英文, 中文]], table?, tip? }
 */

export const EN_STAGES = [
  { id: 1, name: '第一階 · be 動詞與現在簡單式', range: '第 1–20 課' },
  { id: 2, name: '第二階 · 時態基礎與疑問句', range: '第 21–40 課' },
  { id: 3, name: '第三階 · 完成式與情態動詞', range: '第 41–60 課' },
  { id: 4, name: '第四階 · 被動、關係子句與間接引語', range: '第 61–80 課' },
  { id: 5, name: '第五階 · 條件句與學術實戰', range: '第 81–100 課' },
];

export const EN_GRAMMAR = [
  // ─────────── 第一階 ───────────
  { id: 'en-g-001', stage: 1, title: 'be 動詞：am / is / are', summary: '英文句子一定要有動詞，be 是最基本的那個。',
    body: 'I am、you/we/they are、he/she/it is。中文的「我是學生」可以省略動詞，英文不行。',
    examples: [['I am an exchange student.', '我是交換學生。'], ['She is from Prague.', '她來自布拉格。'], ['We are in the same class.', '我們在同一班。']],
    tip: '捷克語會省略主詞，英文不會——每個句子都要有主詞。' },
  { id: 'en-g-002', stage: 1, title: 'be 的否定與縮寫', summary: 'not 放在 be 後面，口語一律縮寫。',
    body: 'am not / is not (isn’t) / are not (aren’t)。口語與非正式書寫用縮寫，學術寫作則寫完整形。',
    examples: [['I’m not ready yet.', '我還沒準備好。'], ['He isn’t here today.', '他今天不在。'], ['They aren’t students.', '他們不是學生。']],
    tip: '報告和論文裡不要用縮寫，這是最容易被扣分的小地方。' },
  { id: 'en-g-003', stage: 1, title: 'be 的疑問句', summary: '把 be 動詞移到主詞前面。',
    body: 'Are you…? Is he…? 回答用 Yes, I am. / No, I’m not.（短答不要省略主詞）。',
    examples: [['Are you an exchange student?', '你是交換學生嗎？'], ['Is this seat free?', '這位子有人嗎？'], ['Yes, it is. / No, it isn’t.', '是的／不是。']],
    tip: '只回 Yes 會顯得很冷淡，加上主詞＋be 才自然。' },
  { id: 'en-g-004', stage: 1, title: '代名詞與所有格', summary: 'I–my–me、he–his–him 三欄一起背。',
    body: '主格（做主詞）、所有格（後面接名詞）、受格（做受詞或介系詞後）。',
    table: { head: ['主格', '所有格', '受格'], rows: [['I', 'my', 'me'], ['you', 'your', 'you'], ['he', 'his', 'him'], ['she', 'her', 'her'], ['we', 'our', 'us'], ['they', 'their', 'them']] },
    examples: [['This is my room.', '這是我的房間。'], ['Can you help me?', '你可以幫我嗎？'], ['I gave it to them.', '我把它給他們了。']],
    tip: 'between you and I 是錯的，介系詞後要用受格：between you and me。' },
  { id: 'en-g-005', stage: 1, title: '冠詞 a / an', summary: '第一次提到的單數可數名詞要加 a/an。',
    body: 'a 用在子音「音」前，an 用在母音「音」前——看發音不看拼字：an hour（h 不發音）、a university（唸 you）。',
    examples: [['I need a form.', '我需要一份表格。'], ['It takes an hour.', '那要一小時。'], ['She is a university student.', '她是大學生。']],
    tip: '捷克語沒有冠詞，所以這是你未來最容易漏掉的一項，寫完檢查一次。' },
  { id: 'en-g-006', stage: 1, title: '冠詞 the', summary: '雙方都知道是哪一個時用 the。',
    body: '再次提到、獨一無二（the sun）、有限定語（the book on the table）、最高級（the best）時用 the。',
    examples: [['I bought a book. The book was cheap.', '我買了一本書。那本書很便宜。'], ['Where is the toilet?', '廁所在哪裡？'], ['It’s the best café here.', '這是這裡最好的咖啡廳。']],
    tip: '判斷法：如果對方會問「哪一個？」就不能用 the。' },
  { id: 'en-g-007', stage: 1, title: '不加冠詞的情況', summary: '複數泛指、不可數泛指、多數專有名詞。',
    body: '泛指某類事物用複數不加冠詞（Students need sleep.）；不可數泛指也不加（Water is free.）；國家、城市、人名多半不加。',
    examples: [['Students get discounts.', '學生有折扣。'], ['I like coffee.', '我喜歡咖啡。'], ['She lives in Prague.', '她住在布拉格。']],
    tip: '例外要背：the Czech Republic、the Netherlands、the UK 都要加 the。' },
  { id: 'en-g-008', stage: 1, title: '名詞複數', summary: '-s / -es / 不規則。',
    body: '一般加 -s；s, x, ch, sh 結尾加 -es；子音+y 改 -ies；f/fe 常改 -ves。不規則：child→children, person→people, tooth→teeth。',
    examples: [['two classes', '兩堂課'], ['three countries', '三個國家'], ['many people', '很多人']],
    tip: 'people 本身就是複數，不要寫 peoples（那是「民族」的意思）。' },
  { id: 'en-g-009', stage: 1, title: '不可數名詞', summary: 'information, advice, luggage 沒有複數。',
    body: '常見不可數：information, advice, furniture, luggage, homework, research, money, bread。要計數就用 a piece of。',
    examples: [['I need some information.', '我需要一些資訊。'], ['That’s a useful piece of advice.', '那是很有用的建議。'], ['My luggage is heavy.', '我的行李很重。']],
    tip: 'informations、advices、homeworks 全都是錯的，這是台灣學生的經典錯誤。' },
  { id: 'en-g-010', stage: 1, title: 'this / that / these / those', summary: '近的用 this/these，遠的用 that/those。',
    body: '單數 this/that，複數 these/those。也可以指前面剛提過的整件事（That makes sense.）。',
    examples: [['This is my roommate.', '這是我室友。'], ['Those books are mine.', '那些書是我的。'], ['That’s a good point.', '這說得有道理。']],
    tip: '電話裡自我介紹說 This is Josh，不是 I am Josh。' },
  { id: 'en-g-011', stage: 1, title: 'there is / there are', summary: '表示「有」某物存在。',
    body: '單數 there is，複數 there are；否定 there isn’t / there aren’t。注意跟 have 的差別：have 是「某人擁有」。',
    examples: [['There is a supermarket nearby.', '附近有一家超市。'], ['There are two beds in the room.', '房間裡有兩張床。'], ['Is there wifi here?', '這裡有 wifi 嗎？']],
    tip: '中文的「有」對應兩個字：存在用 there is，擁有用 have。' },
  { id: 'en-g-012', stage: 1, title: 'have / has', summary: '擁有、以及構成完成式的助動詞。',
    body: 'I/you/we/they have、he/she/it has。英式口語常說 have got（I’ve got a question）。',
    examples: [['I have two lectures today.', '我今天有兩堂課。'], ['She has a Czech passport.', '她有捷克護照。'], ['Have you got a minute?', '你有空嗎？（英式）']],
    tip: '在歐洲 have got 非常常見，聽到不要以為是完成式。' },
  { id: 'en-g-013', stage: 1, title: '現在簡單式', summary: '習慣、事實、時間表。',
    body: '用來講常態與事實，不是「現在正在做」。時間表、課表也用現在簡單式。',
    examples: [['I study computer science.', '我讀資訊。'], ['The library opens at eight.', '圖書館八點開門。'], ['Water boils at 100 degrees.', '水在一百度沸騰。']],
    tip: '「我現在正在做」要用進行式，這兩個在中文都是「我在……」。' },
  { id: 'en-g-014', stage: 1, title: '第三人稱單數 -s', summary: 'he / she / it 後面動詞加 s。',
    body: '主詞是第三人稱單數時，動詞加 -s/-es。這是英文最常被忘記的規則。',
    examples: [['He works at the café.', '他在咖啡廳工作。'], ['She goes to the gym.', '她去健身房。'], ['It takes 20 minutes.', '那要二十分鐘。']],
    tip: '講話漏掉 -s 不會影響溝通，但寫作被扣分很痛，寫完掃一次主詞。' },
  { id: 'en-g-015', stage: 1, title: '現在簡單式否定', summary: 'don’t / doesn’t + 原形動詞。',
    body: '加了 doesn’t 之後主要動詞回到原形，不再加 -s。',
    examples: [['I don’t eat meat.', '我不吃肉。'], ['He doesn’t speak Czech.', '他不會說捷克語。'], ['They don’t open on Sundays.', '他們星期天不營業。']],
    tip: 'He doesn’t speaks 是最常見的錯，助動詞已經扛了時態。' },
  { id: 'en-g-016', stage: 1, title: '現在簡單式疑問句', summary: 'Do / Does + 主詞 + 原形。',
    body: '問句要把助動詞放句首，主要動詞維持原形。',
    examples: [['Do you have a student card?', '你有學生證嗎？'], ['Does this bus go to the centre?', '這班公車到市中心嗎？'], ['What time does it start?', '幾點開始？']],
    tip: '中文問句只加「嗎」，英文一定要動助動詞位置。' },
  { id: 'en-g-017', stage: 1, title: '頻率副詞的位置', summary: 'be 之後、一般動詞之前。',
    body: 'always, usually, often, sometimes, rarely, never。放在 be 動詞後面、一般動詞前面。',
    examples: [['I usually take the tram.', '我通常搭電車。'], ['She is always late.', '她總是遲到。'], ['I never skip breakfast.', '我從不跳過早餐。']],
    tip: 'never 已經是否定，不要再加 don’t。' },
  { id: 'en-g-018', stage: 1, title: '時間介系詞 in / on / at', summary: '大範圍 in、日期 on、時間點 at。',
    body: 'in ＋ 月份/年份/季節；on ＋ 星期/日期；at ＋ 幾點/節日名。',
    table: { head: ['介系詞', '用法', '例'], rows: [['in', '月、年、季', 'in September'], ['on', '日、星期', 'on Monday'], ['at', '時刻', 'at 8 p.m.']] },
    examples: [['The semester starts in October.', '學期十月開始。'], ['I have class on Tuesday.', '我星期二有課。'], ['Let’s meet at seven.', '我們七點見。']],
    tip: '例外：at night、in the morning、on Monday morning。' },
  { id: 'en-g-019', stage: 1, title: '地點介系詞 in / on / at', summary: '在裡面 in、在表面 on、在點位 at。',
    body: 'in ＋ 空間內部（in the room）；on ＋ 表面（on the table）；at ＋ 地點作為一個點（at the station）。',
    examples: [['I live in a dorm.', '我住在宿舍。'], ['Your keys are on the desk.', '你的鑰匙在桌上。'], ['I’m at the bus stop.', '我在公車站。']],
    tip: 'at school ＝在上學（活動），in the school ＝在校舍裡面。' },
  { id: 'en-g-020', stage: 1, title: '複習 1：完整自我介紹', summary: 'be ＋ 現在簡單式的整合。',
    body: '把前 19 課組合成三句自我介紹，這是抵達第一天最常講的內容。',
    examples: [['Hi, I’m Josh. I’m an exchange student from Taiwan.', '嗨，我是 Josh，來自台灣的交換學生。'], ['I study computer science and I live in the dorm.', '我讀資訊，住在宿舍。'], ['I don’t speak much Czech yet, but I’m learning.', '我捷克語還不太會，但正在學。']],
    tip: '最後那句 but I’m learning 會讓對方立刻對你有好感。' },

  // ─────────── 第二階 ───────────
  { id: 'en-g-021', stage: 2, title: '現在進行式', summary: 'be + V-ing：此刻正在發生。',
    body: '表達現在正在進行、或這陣子的暫時狀態。',
    examples: [['I’m waiting for the tram.', '我在等電車。'], ['She’s studying in the library.', '她在圖書館唸書。'], ['We’re staying here for a semester.', '我們在這待一個學期。']],
    tip: '暫時狀態也用進行式：I’m living in Prague this year.' },
  { id: 'en-g-022', stage: 2, title: '簡單式 vs 進行式', summary: '習慣 vs 此刻；狀態動詞不用進行式。',
    body: 'know, like, want, need, believe, belong 等狀態動詞通常不用進行式。',
    examples: [['I work at a café. / I’m working right now.', '我在咖啡廳工作。／我現在正在工作。'], ['I know the answer.', '我知道答案。（不說 I’m knowing）'], ['I’m loving it 是廣告用語，不是標準文法。', '——']],
    tip: '判斷法：能不能說「此刻正在」？不能就用簡單式。' },
  { id: 'en-g-023', stage: 2, title: '過去式的 be：was / were', summary: 'I/he/she/it was；you/we/they were。',
    body: '否定 wasn’t / weren’t，疑問把 was/were 移到主詞前。',
    examples: [['I was at the office yesterday.', '我昨天在辦公室。'], ['They were very helpful.', '他們很幫忙。'], ['Was it expensive?', '很貴嗎？']],
    tip: 'There was / There were 也照同樣規則。' },
  { id: 'en-g-024', stage: 2, title: '過去簡單式：規則動詞', summary: '動詞加 -ed。',
    body: '一般加 -ed；e 結尾加 -d；子音+y 改 -ied；短母音+單子音要雙寫（stop→stopped）。',
    examples: [['I arrived last week.', '我上週到的。'], ['We studied together.', '我們一起唸書。'], ['The tram stopped suddenly.', '電車突然停了。']],
    tip: '-ed 的發音有三種：/t/、/d/、/ɪd/，wanted 才唸出額外音節。' },
  { id: 'en-g-025', stage: 2, title: '不規則動詞', summary: '最高頻的 20 個先背。',
    body: 'go-went-gone、have-had-had、take-took-taken、get-got-got(ten)、see-saw-seen、write-wrote-written、come-came-come、do-did-done。',
    table: { head: ['原形', '過去', '過去分詞'], rows: [['go', 'went', 'gone'], ['take', 'took', 'taken'], ['write', 'wrote', 'written'], ['get', 'got', 'got/gotten'], ['see', 'saw', 'seen']] },
    examples: [['I went to Vienna last weekend.', '我上週末去了維也納。'], ['She took the early train.', '她搭了早班火車。'], ['I’ve written the essay.', '我已經寫完報告了。']],
    tip: '第三欄（過去分詞）之後學完成式和被動都會用到，一起背比較划算。' },
  { id: 'en-g-026', stage: 2, title: '過去式的否定與疑問', summary: 'didn’t / did + 原形。',
    body: '加了 did 之後主要動詞回原形，不再是過去式。',
    examples: [['I didn’t know that.', '我不知道那件事。'], ['Did you get my email?', '你收到我的信了嗎？'], ['Where did you go?', '你去了哪裡？']],
    tip: 'I didn’t went 是很常見的錯，did 已經表示過去了。' },
  { id: 'en-g-027', stage: 2, title: '過去進行式', summary: 'was/were + V-ing：某時正在進行。',
    body: '常和過去簡單式搭配：長動作用進行式，打斷它的短動作用簡單式。',
    examples: [['I was cooking when you called.', '你打來時我正在煮飯。'], ['They were waiting outside.', '他們在外面等。'], ['What were you doing at ten?', '你十點在做什麼？']],
    tip: 'when ＋ 簡單式、while ＋ 進行式，是最穩的搭配。' },
  { id: 'en-g-028', stage: 2, title: 'used to', summary: '過去的習慣，現在已經不做了。',
    body: 'used to ＋ 原形，表示過去常態但現在已改變。否定 didn’t use to。',
    examples: [['I used to live with my parents.', '我以前和父母同住。'], ['She used to drink a lot of coffee.', '她以前喝很多咖啡。'], ['I didn’t use to like beer.', '我以前不喜歡啤酒。']],
    tip: '別和 be used to（習慣於）搞混：I’m used to the cold.' },
  { id: 'en-g-029', stage: 2, title: '未來式 will', summary: '當下決定、預測、承諾。',
    body: 'will ＋ 原形。說話當下才決定的事、單純預測、給承諾都用 will。',
    examples: [['I’ll send you the file tonight.', '我今晚會把檔案寄給你。'], ['It will probably rain.', '大概會下雨。'], ['I’ll help you with that.', '我會幫你。']],
    tip: '寫信說「我會處理」用 I’ll，比 I am going to 更自然俐落。' },
  { id: 'en-g-030', stage: 2, title: '未來式 be going to', summary: '已經有的計畫、有跡象的預測。',
    body: '事先就決定好的計畫，或看到跡象做的預測。',
    examples: [['I’m going to apply for a residence permit.', '我打算申請居留許可。'], ['Look at those clouds — it’s going to rain.', '看那些雲，要下雨了。'], ['We’re going to travel in December.', '我們十二月要去旅行。']],
    tip: 'will＝當下決定，be going to＝早就打算好，考試最愛考這個差別。' },
  { id: 'en-g-031', stage: 2, title: '現在進行式表未來', summary: '已經安排好的行程。',
    body: '約好、訂好、排進行事曆的事，用現在進行式表示未來最自然。',
    examples: [['I’m meeting my supervisor at three.', '我三點跟指導教授碰面。'], ['We’re flying to Prague on the 25th.', '我們 25 號飛布拉格。'], ['She’s starting her internship next week.', '她下週開始實習。']],
    tip: '母語者講近期行程幾乎都用這個，而不是 will。' },
  { id: 'en-g-032', stage: 2, title: '時間連接詞', summary: 'when, while, before, after, until, as soon as。',
    body: '時間副詞子句裡不用 will，用現在式代替未來。',
    examples: [['I’ll call you when I arrive.', '我到了會打給你。'], ['Wait here until I come back.', '在這等到我回來。'], ['As soon as I finish, I’ll let you know.', '我一做完就通知你。']],
    tip: 'when I will arrive 是錯的——這是台灣學生非常常犯的錯。' },
  { id: 'en-g-033', stage: 2, title: 'can / could', summary: '能力、可能、請求。',
    body: 'can＝能力或允許；could＝過去的能力、或更客氣的請求。',
    examples: [['I can speak a little Czech.', '我會說一點捷克語。'], ['Could you repeat that, please?', '可以請你再說一次嗎？'], ['Can I ask a question?', '我可以問個問題嗎？']],
    tip: 'Could you…? 比 Can you…? 客氣一級，對教授和職員用它。' },
  { id: 'en-g-034', stage: 2, title: '祈使句', summary: '直接用原形動詞。',
    body: '省略主詞，直接原形。否定加 Don’t。加 please 可以軟化語氣。',
    examples: [['Fill in the form, please.', '請填表格。'], ['Don’t forget your passport.', '別忘了護照。'], ['Let’s take the tram.', '我們搭電車吧。']],
    tip: '單獨的祈使句在英文偏強硬，加 please 或改成問句比較安全。' },
  { id: 'en-g-035', stage: 2, title: 'Wh- 疑問句', summary: '疑問詞 + 助動詞 + 主詞 + 動詞。',
    body: 'what, where, when, who, why, how, which, whose。除了問主詞的情況，都要倒裝。',
    examples: [['Where do you live?', '你住哪裡？'], ['How long does it take?', '要花多久？'], ['Why did you choose Prague?', '你為什麼選布拉格？']],
    tip: 'How long（多久）、How far（多遠）、How often（多常）三個組合很實用。' },
  { id: 'en-g-036', stage: 2, title: '主詞疑問句', summary: '問主詞時不用 do。',
    body: '當疑問詞本身就是主詞時，語序不變，也不加助動詞。',
    examples: [['Who called you?', '誰打給你？'], ['What happened?', '發生什麼事？'], ['Which bus goes to the centre?', '哪班公車到市中心？']],
    tip: 'Who did call you? 只有強調時才這樣說，平常不用。' },
  { id: 'en-g-037', stage: 2, title: '附加問句', summary: '前肯定後否定，前否定後肯定。',
    body: '用來確認或尋求同意。英國人使用頻率極高。',
    examples: [['You’re from Taiwan, aren’t you?', '你來自台灣，對吧？'], ['It isn’t far, is it?', '不遠吧？'], ['She can help, can’t she?', '她可以幫忙，對吧？']],
    tip: '聽到 …, isn’t it? 只是在找認同，回 Yes/No 都可以，不用緊張。' },
  { id: 'en-g-038', stage: 2, title: '形容詞的順序', summary: '意見 → 大小 → 年齡 → 顏色 → 來源 → 材質。',
    body: '多個形容詞並列時有固定順序，母語者靠語感，我們靠口訣。',
    examples: [['a nice small old wooden table', '一張很棒的小舊木桌'], ['a beautiful old Czech building', '一棟美麗的古老捷克建築'], ['a cheap black backpack', '一個便宜的黑色背包']],
    tip: '順序錯了不會聽不懂，但母語者會覺得「怪怪的」。' },
  { id: 'en-g-039', stage: 2, title: '比較級與最高級', summary: '短的加 -er/-est，長的加 more/most。',
    body: '單音節加 -er/-est；三音節以上用 more/most；兩音節看情況。不規則：good→better→best，bad→worse→worst。',
    examples: [['Prague is cheaper than Vienna.', '布拉格比維也納便宜。'], ['This is the most useful app.', '這是最有用的 app。'], ['My Czech is getting better.', '我的捷克語越來越好了。']],
    tip: 'more cheaper 是雙重比較級，錯誤但很常見，注意別犯。' },
  { id: 'en-g-040', stage: 2, title: '複習 2：講一個過去的經驗', summary: '過去式 ＋ 時間連接詞的整合。',
    body: '面試、閒聊、課堂分享都會用到「講一段經歷」的能力。',
    examples: [['Last summer I worked as an intern at a startup.', '去年夏天我在新創公司實習。'], ['While I was there, I learned a lot about teamwork.', '在那期間我學到很多團隊合作。'], ['After that, I decided to study abroad.', '之後我決定出國唸書。']],
    tip: '用 Last…, While…, After that… 三個連接詞就能撐起一段完整敘述。' },

  // ─────────── 第三階 ───────────
  { id: 'en-g-041', stage: 3, title: '現在完成式', summary: 'have/has + 過去分詞。',
    body: '表示到現在為止的經驗、變化、或仍有影響的過去動作。不強調何時發生。',
    examples: [['I have been to Vienna twice.', '我去過維也納兩次。'], ['She has finished her thesis.', '她論文寫完了。'], ['We have known each other for years.', '我們認識好幾年了。']],
    tip: '中文的「了」有時是完成式，有時是過去式，別直接對譯。' },
  { id: 'en-g-042', stage: 3, title: '完成式 vs 過去簡單式', summary: '有沒有明確的過去時間點。',
    body: '句中一旦出現 yesterday, last week, in 2024 這種明確過去時間，就必須用過去簡單式。',
    examples: [['I have lost my keys.', '我鑰匙掉了（現在還沒找到）。'], ['I lost my keys yesterday.', '我昨天掉了鑰匙。'], ['Have you seen this film? — Yes, I saw it last year.', '你看過這部片嗎？—— 有，我去年看的。']],
    tip: '這是英文考試最愛考、留學生也最常錯的一組。' },
  { id: 'en-g-043', stage: 3, title: 'for 與 since', summary: 'for ＋ 時間長度，since ＋ 起點。',
    body: '兩者都和完成式搭配。for two years（兩年）／since 2024（從 2024 起）。',
    examples: [['I have lived here for three months.', '我在這住了三個月。'], ['She has been ill since Monday.', '她從星期一就病了。'], ['How long have you been here?', '你來多久了？']],
    tip: '中文都說「三個月了」，英文要分清楚 for 和 since。' },
  { id: 'en-g-044', stage: 3, title: 'already / yet / just', summary: '完成式的三個常用副詞。',
    body: 'already（已經，肯定句）、yet（還沒／了嗎，否定與疑問句尾）、just（剛剛）。',
    examples: [['I have already submitted it.', '我已經交了。'], ['Have you finished yet?', '你做完了嗎？'], ['She has just left.', '她剛離開。']],
    tip: 'yet 放句尾、already 放動詞前，位置錯了會很明顯。' },
  { id: 'en-g-045', stage: 3, title: 'ever / never：經驗', summary: 'Have you ever…? 是聊天神句。',
    body: 'ever 用在疑問句表示「曾經」，never 是否定的「從未」。',
    examples: [['Have you ever tried svíčková?', '你吃過捷克燉牛肉嗎？'], ['I have never been to Poland.', '我從沒去過波蘭。'], ['It’s the best beer I have ever had.', '這是我喝過最好的啤酒。']],
    tip: '認識新朋友時 Have you ever…? 幾乎可以無限延伸話題。' },
  { id: 'en-g-046', stage: 3, title: 'been 與 gone', summary: '去過（回來了）vs 去了（還沒回）。',
    body: 'has been to＝去過並且已回來；has gone to＝去了還在那裡。',
    examples: [['She has been to Brno.', '她去過布爾諾。'], ['She has gone to Brno.', '她去布爾諾了（人不在）。'], ['I’ve been there twice.', '我去過那裡兩次。']],
    tip: '一個字的差別會讓對方以為你人不在，講約會地點時要小心。' },
  { id: 'en-g-047', stage: 3, title: '現在完成進行式', summary: 'have been + V-ing：持續到現在的動作。',
    body: '強調動作持續的過程與時間長度，常和 for/since 一起用。',
    examples: [['I have been studying Czech for two months.', '我學捷克語兩個月了。'], ['It has been raining all day.', '雨下了一整天。'], ['She has been waiting for an hour.', '她等了一小時。']],
    tip: '強調「結果」用完成式，強調「持續多久」用完成進行式。' },
  { id: 'en-g-048', stage: 3, title: '過去完成式', summary: 'had + 過去分詞：過去的過去。',
    body: '兩件過去的事，先發生的那件用過去完成式。',
    examples: [['The train had already left when I arrived.', '我到的時候火車已經開走了。'], ['I had never seen snow before I came here.', '來這裡之前我沒看過雪。'], ['She said she had finished it.', '她說她已經做完了。']],
    tip: '只有需要區分先後時才用，濫用會讓句子變沉重。' },
  { id: 'en-g-049', stage: 3, title: 'must / have to', summary: '主觀的必須 vs 客觀的規定。',
    body: 'must＝說話者認為必須；have to＝外在規定。否定差很多：mustn’t＝禁止，don’t have to＝不必。',
    examples: [['You have to register within three days.', '你必須在三天內登記。（規定）'], ['I must call my parents.', '我一定要打給爸媽。（自己覺得）'], ['You don’t have to come.', '你不必來。']],
    tip: 'mustn’t 和 don’t have to 意思相反，用錯會造成誤會。' },
  { id: 'en-g-050', stage: 3, title: 'should / ought to', summary: '建議與應該。',
    body: 'should 是最常用的建議語氣，比 must 柔和很多。',
    examples: [['You should ask your supervisor.', '你應該問你的指導教授。'], ['I should have booked earlier.', '我應該早點訂的。'], ['Should I bring anything?', '我需要帶什麼嗎？']],
    tip: 'should have + p.p.＝當初應該做卻沒做，帶懊悔語氣。' },
  { id: 'en-g-051', stage: 3, title: 'may / might', summary: '可能性與正式的請求許可。',
    body: 'may/might＋原形表示「可能」；may 也用在正式的請求許可。',
    examples: [['It might snow tomorrow.', '明天可能會下雪。'], ['May I come in?', '我可以進來嗎？'], ['She may not be available.', '她可能沒空。']],
    tip: 'might 的可能性比 may 稍低，日常口語 might 更常見。' },
  { id: 'en-g-052', stage: 3, title: 'must / can’t 表推測', summary: '一定是 vs 不可能。',
    body: '除了「必須」，must 也表示有把握的推測；相反的推測用 can’t。',
    examples: [['You must be tired after the flight.', '飛完這趟你一定很累。'], ['That can’t be right.', '那不可能是對的。'], ['He must be at the library.', '他一定在圖書館。']],
    tip: '推測的否定不用 mustn’t，要用 can’t。' },
  { id: 'en-g-053', stage: 3, title: '情態動詞 + have + p.p.', summary: '對過去的推測與後悔。',
    body: 'must have（一定是）、might have（可能是）、should have（早該）、could have（本來可以）。',
    examples: [['I must have left it at home.', '我一定是把它忘在家裡了。'], ['You could have told me!', '你本來可以告訴我的！'], ['They might have missed the train.', '他們可能錯過火車了。']],
    tip: '口語中 have 會弱化成 /əv/，聽起來像 must of——但寫出來一定是 have。' },
  { id: 'en-g-054', stage: 3, title: 'would', summary: '禮貌、假設、過去的習慣。',
    body: 'Would you…?（禮貌請求）、I would like（想要）、would＋原形（過去反覆的習慣）。',
    examples: [['Would you mind opening the window?', '你介意開個窗嗎？'], ['I would like to apply for this course.', '我想申請這門課。'], ['We would go hiking every summer.', '我們以前每年夏天都去健行。']],
    tip: 'I would like 比 I want 客氣非常多，所有正式場合都用它。' },
  { id: 'en-g-055', stage: 3, title: 'some / any / much / many', summary: '可數與不可數的搭配。',
    body: 'some 用於肯定句與邀請；any 用於否定與疑問；many＋可數、much＋不可數；a lot of 兩者皆可。',
    examples: [['I have some questions.', '我有一些問題。'], ['Do you have any documents?', '你有任何文件嗎？'], ['There isn’t much time.', '沒剩多少時間。']],
    tip: '邀請或請求時用 some 比 any 自然：Would you like some coffee?' },
  { id: 'en-g-056', stage: 3, title: 'a few / a little / plenty of', summary: '少量與充足的表達。',
    body: 'a few＋可數（幾個）、a little＋不可數（一點）；few/little 不加 a 帶「很少、不夠」的負面語氣。',
    examples: [['I have a few friends here.', '我在這有幾個朋友。'], ['We have a little time left.', '我們還剩一點時間。'], ['Few students showed up.', '沒幾個學生出現。']],
    tip: 'a few＝正面（有幾個），few＝負面（幾乎沒有），差一個 a 差很多。' },
  { id: 'en-g-057', stage: 3, title: 'too / enough', summary: '太……／夠……',
    body: 'too＋形容詞（太），形容詞＋enough（夠），enough＋名詞（足夠的）。',
    examples: [['It’s too expensive for me.', '這對我來說太貴了。'], ['The room isn’t big enough.', '房間不夠大。'], ['I don’t have enough time.', '我沒有足夠的時間。']],
    tip: 'enough 放形容詞後面、名詞前面，位置剛好相反。' },
  { id: 'en-g-058', stage: 3, title: 'so / such', summary: '如此……以致於。',
    body: 'so＋形容詞/副詞；such＋（a）＋形容詞＋名詞。後面可接 that 子句。',
    examples: [['It was so cold that I stayed in.', '天太冷了，我就待在室內。'], ['It’s such a beautiful city.', '這真是個美麗的城市。'], ['She’s so kind.', '她人真好。']],
    tip: '記法：so 後面沒有名詞，such 後面有名詞。' },
  { id: 'en-g-059', stage: 3, title: 'both / either / neither', summary: '兩者都、任一、兩者都不。',
    body: 'both＋複數；either/neither＋單數；either…or…／neither…nor…。',
    examples: [['Both options are fine.', '兩個選項都可以。'], ['You can take either bus.', '兩班公車都可以搭。'], ['Neither of us speaks German.', '我們兩個都不會德文。']],
    tip: 'Neither 本身已是否定，不要再加 not。' },
  { id: 'en-g-060', stage: 3, title: '複習 3：寫一封正式 email', summary: '完成式＋情態動詞的實戰。',
    body: '寫信給教授或行政單位，是留學期間最高頻的英文輸出。',
    examples: [['Dear Professor Novák,', '親愛的 Novák 教授：'], ['I am writing to ask whether I could still enrol in your course.', '我來信想詢問是否還能加選您的課。'], ['I would be grateful for your advice. Kind regards, Josh', '感謝您的建議。祝好，Josh']],
    tip: '主旨具體、第一句就講重點、結尾用 Kind regards——這三點就贏過八成的信。' },

  // ─────────── 第四階 ───────────
  { id: 'en-g-061', stage: 4, title: '被動語態（現在式）', summary: 'be + 過去分詞：重點在動作本身。',
    body: '當「誰做的」不重要或不知道時使用。學術寫作大量使用被動。',
    examples: [['The forms are processed within ten days.', '表格會在十天內處理完。'], ['English is spoken here.', '這裡通英文。'], ['The data is stored securely.', '資料被安全儲存。']],
    tip: '公告、規定、說明書幾乎都是被動句，看懂它們很重要。' },
  { id: 'en-g-062', stage: 4, title: '被動語態（過去與完成）', summary: 'was/were + p.p.；has been + p.p.',
    body: '被動可以套用在任何時態，只要改變 be 的形式。',
    examples: [['My application was rejected.', '我的申請被拒絕了。'], ['The room has been cleaned.', '房間已經打掃過了。'], ['The results will be announced on Friday.', '結果週五公布。']],
    tip: 'will be + p.p. 是公告最常見的形式，先記起來。' },
  { id: 'en-g-063', stage: 4, title: '學術寫作中的被動', summary: '把焦點放在方法與結果。',
    body: '科學與社會科學寫作偏好被動，避免第一人稱。但近年也接受適度使用 we。',
    examples: [['The samples were collected in June.', '樣本於六月採集。'], ['It is generally assumed that…', '一般認為……'], ['The method was adapted from Novák (2023).', '此方法改編自 Novák（2023）。']],
    tip: '別整篇都被動，會很難讀；重點段落用主動反而清楚。' },
  { id: 'en-g-064', stage: 4, title: 'by ＋ 動作者', summary: '需要指出是誰做的時候。',
    body: '被動句加 by 說明執行者，但只有在這個資訊重要時才加。',
    examples: [['The essay was written by two students.', '這篇報告由兩位學生撰寫。'], ['The city was founded in the 9th century.', '這座城市建於九世紀。'], ['It was recommended by my supervisor.', '這是我指導教授推薦的。']],
    tip: '八成的被動句不需要 by，加太多反而囉唆。' },
  { id: 'en-g-065', stage: 4, title: '關係代名詞 who / which / that', summary: '把兩句話合成一句。',
    body: 'who 指人、which 指物、that 兩者皆可（限定用法）。',
    examples: [['The student who sits next to me is Czech.', '坐我旁邊的學生是捷克人。'], ['The course which I chose is in English.', '我選的課是英文授課。'], ['This is the app that everyone uses here.', '這是這裡大家都在用的 app。']],
    tip: '口語中 that 用得比 which 多，寫作則相反。' },
  { id: 'en-g-066', stage: 4, title: '限定 vs 非限定關係子句', summary: '有沒有逗號，意思差很多。',
    body: '沒有逗號＝限定（必要資訊）；有逗號＝補充說明（可刪除）。非限定不能用 that。',
    examples: [['My friend who lives in Brno is coming.', '我住在布爾諾的那個朋友要來。（我有多個朋友）'], ['My friend, who lives in Brno, is coming.', '我朋友（他住布爾諾）要來。（只有一個朋友）'], ['Prague, which is the capital, has 1.3 million people.', '布拉格是首都，有 130 萬人。']],
    tip: '寫作時逗號放錯會改變句意，這是改考卷時會被抓的細節。' },
  { id: 'en-g-067', stage: 4, title: 'whose / where / when 引導子句', summary: '所有、地點、時間的關係子句。',
    body: 'whose＝……的（所有）、where＝地點、when＝時間。',
    examples: [['The student whose laptop broke borrowed mine.', '筆電壞掉的那個學生借了我的。'], ['This is the café where we first met.', '這是我們第一次見面的咖啡廳。'], ['I remember the day when I arrived.', '我記得我抵達的那一天。']],
    tip: 'whose 可以用在人也可以用在物，不必改成 of which。' },
  { id: 'en-g-068', stage: 4, title: '省略關係代名詞', summary: '當它是受詞時可以拿掉。',
    body: '關係代名詞若在子句中當受詞，可以省略，母語者幾乎都會省。',
    examples: [['The book (that) I borrowed is due tomorrow.', '我借的書明天到期。'], ['The person (who) you met is my tutor.', '你遇到的那個人是我的導師。'], ['Everything (that) she said was true.', '她說的每件事都是真的。']],
    tip: '當主詞時不能省略：The student who lives here…（不能拿掉 who）。' },
  { id: 'en-g-069', stage: 4, title: '動名詞 V-ing', summary: '動詞當名詞用。',
    body: '可以當主詞、受詞或補語。介系詞後面一定接動名詞。',
    examples: [['Learning Czech takes time.', '學捷克語需要時間。'], ['I enjoy cooking.', '我喜歡做菜。'], ['Thank you for helping me.', '謝謝你幫我。']],
    tip: 'Thank you for help 是錯的，介系詞 for 後面要 helping。' },
  { id: 'en-g-070', stage: 4, title: '不定詞 to V', summary: '表達目的、意圖與未來性。',
    body: '常用在「為了」以及特定動詞後面（want, need, decide, hope, plan）。',
    examples: [['I came here to study.', '我來這裡是為了唸書。'], ['She decided to stay one more semester.', '她決定再待一學期。'], ['It’s hard to find a flat.', '找房子很難。']],
    tip: '目的用 to V 就好，不必寫 for to study（那是錯的）。' },
  { id: 'en-g-071', stage: 4, title: '接 -ing 還是 to V', summary: '動詞決定，要分組記。',
    body: '接 -ing：enjoy, finish, avoid, mind, suggest, practise。接 to V：want, need, decide, hope, agree, manage。兩者皆可但意思不同：stop / remember / forget。',
    examples: [['I stopped smoking.', '我戒菸了。'], ['I stopped to smoke.', '我停下來抽菸。'], ['Remember to lock the door.', '記得鎖門。']],
    tip: 'stop 那組是經典陷阱：stopped doing＝不做了，stopped to do＝停下來去做。' },
  { id: 'en-g-072', stage: 4, title: '介系詞 + V-ing', summary: '所有介系詞後面都接 -ing。',
    body: 'be interested in、look forward to、be good at、instead of、before/after ＋ V-ing。',
    examples: [['I’m looking forward to meeting you.', '我很期待見到你。'], ['She’s good at explaining things.', '她很會解釋事情。'], ['Before applying, check the deadline.', '申請前先確認截止日。']],
    tip: 'look forward to 的 to 是介系詞不是不定詞，後面永遠接 -ing。' },
  { id: 'en-g-073', stage: 4, title: '使役動詞', summary: 'make / let / have / get 的接法不同。',
    body: 'make/let/have ＋ 受詞 ＋ 原形；get ＋ 受詞 ＋ to V。',
    examples: [['The teacher made us rewrite it.', '老師讓我們重寫。'], ['Let me check.', '讓我確認一下。'], ['I got my friend to help me.', '我請朋友幫我。']],
    tip: 'have something done＝請人做某事：I had my laptop repaired.' },
  { id: 'en-g-074', stage: 4, title: '感官動詞', summary: 'see / hear / watch ＋ 原形或 -ing。',
    body: '接原形＝看到整個過程；接 -ing＝看到正在進行的片段。',
    examples: [['I saw him leave.', '我看到他離開（整個過程）。'], ['I saw him leaving.', '我看到他正要離開。'], ['I heard someone knocking.', '我聽到有人在敲門。']],
    tip: '差別很細，講錯不影響溝通，但閱讀時要看得懂。' },
  { id: 'en-g-075', stage: 4, title: '片語動詞：可分離與否', summary: '受詞是代名詞時一定要插進中間。',
    body: '可分離：turn on the light / turn it on（代名詞必須插中間）。不可分離：look after him（不能說 look him after）。',
    examples: [['Can you turn it off?', '你可以把它關掉嗎？'], ['I’ll pick you up at eight.', '我八點去接你。'], ['She looks after her sister.', '她照顧她妹妹。']],
    tip: 'turn off it 是錯的——代名詞永遠插在中間。' },
  { id: 'en-g-076', stage: 4, title: '學術情境常用片語動詞', summary: '課堂與行政最常聽到的一組。',
    body: 'hand in（繳交）、sign up for（報名）、fill in（填寫）、carry out（執行）、point out（指出）、come up with（想出）。',
    examples: [['Please hand in your assignment by Friday.', '請在週五前交作業。'], ['I signed up for the seminar.', '我報名了那堂研討課。'], ['They carried out a survey.', '他們做了一份問卷調查。']],
    tip: '正式寫作可以換成單字動詞：carry out → conduct、point out → indicate。' },
  { id: 'en-g-077', stage: 4, title: '間接引語', summary: '轉述別人的話，時態往後退一格。',
    body: '現在→過去、過去→過去完成、will→would。人稱與時間副詞也要調整。',
    examples: [['He said he was busy.', '他說他很忙。'], ['She told me she had already sent it.', '她告訴我她已經寄了。'], ['They said they would come.', '他們說他們會來。']],
    tip: 'say 後面不接人（say to me），tell 後面直接接人（tell me）。' },
  { id: 'en-g-078', stage: 4, title: '間接問句', summary: '嵌進句子後語序恢復正常。',
    body: '間接問句不用倒裝，也不用 do/does/did。',
    examples: [['Could you tell me where the office is?', '可以告訴我辦公室在哪嗎？'], ['I don’t know when it starts.', '我不知道什麼時候開始。'], ['Do you know if she is coming?', '你知道她會不會來嗎？']],
    tip: 'where is the office 放進句子要變成 where the office is，這點極常錯。' },
  { id: 'en-g-079', stage: 4, title: '委婉的請求與建議', summary: '把直接的話包起來。',
    body: 'Would it be possible to…? / I was wondering if…／It might be a good idea to…／Perhaps we could…',
    examples: [['Would it be possible to reschedule?', '有可能改期嗎？'], ['I was wondering if you could review my draft.', '不知道您是否能看一下我的草稿。'], ['It might be worth checking with the office.', '也許值得跟辦公室確認一下。']],
    tip: '英國與北歐的溝通文化非常吃這一套，直球容易被視為沒禮貌。' },
  { id: 'en-g-080', stage: 4, title: '複習 4：課堂口頭報告', summary: '把被動、關係子句、間接引語用進去。',
    body: '報告有固定骨架：開場 → 大綱 → 主體 → 結論 → 問答。',
    examples: [['Today I’m going to talk about three points.', '今天我要談三個重點。'], ['As Novák points out, the data was collected in 2023.', '如 Novák 指出，資料是 2023 年蒐集的。'], ['That’s all from me — happy to take questions.', '我報告到這裡，歡迎提問。']],
    tip: '最後一句準備好，可以把緊張的收尾變得很專業。' },

  // ─────────── 第五階 ───────────
  { id: 'en-g-081', stage: 5, title: '第一類條件句', summary: 'If ＋ 現在式, will ＋ 原形。',
    body: '真實、有可能發生的條件。if 子句用現在式表示未來。',
    examples: [['If it rains, we will stay in.', '如果下雨，我們就待在室內。'], ['If you need help, just ask.', '如果需要幫忙，儘管開口。'], ['I’ll let you know if anything changes.', '有任何變動我會通知你。']],
    tip: 'If it will rain 是錯的，if 子句不用 will。' },
  { id: 'en-g-082', stage: 5, title: '第二類條件句', summary: 'If ＋ 過去式, would ＋ 原形。',
    body: '與現在事實相反或不太可能的假設。be 動詞習慣用 were。',
    examples: [['If I had more time, I would travel more.', '如果我有更多時間，我會多旅行。'], ['If I were you, I would ask the professor.', '如果我是你，我會問教授。'], ['What would you do if you lost your passport?', '如果你護照掉了會怎麼辦？']],
    tip: 'If I were you 是給建議最安全的句型。' },
  { id: 'en-g-083', stage: 5, title: '第三類條件句', summary: 'If ＋ had p.p., would have p.p.',
    body: '與過去事實相反的假設，帶有後悔或慶幸。',
    examples: [['If I had booked earlier, it would have been cheaper.', '如果我早點訂就會便宜些。'], ['If she hadn’t helped me, I would have failed.', '要不是她幫我，我就被當了。'], ['We would have missed it if you hadn’t called.', '要不是你打來，我們就錯過了。']],
    tip: '這是英文裡最長的句型之一，寫出來比說出來容易，先從寫開始練。' },
  { id: 'en-g-084', stage: 5, title: '混合條件句', summary: '過去的條件、現在的結果。',
    body: 'If ＋ had p.p., would ＋ 原形：過去若如何，現在就會如何。',
    examples: [['If I had studied Czech earlier, I would understand more now.', '如果我早點學捷克語，現在就聽得懂更多。'], ['If we hadn’t moved, we would still live there.', '如果我們沒搬家，現在還住在那裡。'], ['If I had taken that course, I would have the credits.', '如果我修了那門課，現在就有學分了。']],
    tip: '看時間標記：earlier / now 一起出現時，多半是混合條件句。' },
  { id: 'en-g-085', stage: 5, title: 'I wish / If only', summary: '表達遺憾與願望。',
    body: '對現在不滿用過去式（I wish I had more time），對過去後悔用過去完成式（I wish I had known）。',
    examples: [['I wish I spoke better Czech.', '真希望我捷克語好一點。'], ['I wish I had known that earlier.', '真希望我早點知道。'], ['If only it were warmer.', '要是暖和一點就好了。']],
    tip: 'I wish 後面永遠往前推一格時態，這是唯一要記的規則。' },
  { id: 'en-g-086', stage: 5, title: '正式書寫的假設語氣', summary: 'suggest / recommend that ＋ 原形。',
    body: '在 suggest, recommend, insist, propose, request 之後的 that 子句，用動詞原形（不加 s）。',
    examples: [['The tutor suggested that he submit the draft early.', '導師建議他早點交草稿。'], ['We recommend that the deadline be extended.', '我們建議延長期限。'], ['They requested that she attend the meeting.', '他們要求她出席會議。']],
    tip: '看起來像文法錯誤，其實是正式英文的正確用法，論文裡很常見。' },
  { id: 'en-g-087', stage: 5, title: '倒裝句', summary: '否定副詞放句首要倒裝。',
    body: 'Never, Not only, Rarely, Little 放句首時，主詞與助動詞要對調。用於強調與正式書寫。',
    examples: [['Never have I seen such a long queue.', '我從沒看過這麼長的隊伍。'], ['Not only is it cheap, but it is also fast.', '它不只便宜，還很快。'], ['Rarely does he miss a lecture.', '他很少缺課。']],
    tip: '口說不用刻意使用，但寫作或閱讀學術文章會遇到。' },
  { id: 'en-g-088', stage: 5, title: '強調句型', summary: 'It is … that … 與 What … is …',
    body: '把想強調的成分放到 It is/was 之後；或用 What 開頭的名詞子句。',
    examples: [['It was the deadline that worried me.', '讓我擔心的是截止日。'], ['What I need is more time.', '我需要的是更多時間。'], ['It is this point that matters most.', '最重要的正是這一點。']],
    tip: '報告中想突出重點時很好用，比全部用底線有效。' },
  { id: 'en-g-089', stage: 5, title: '學術軟化語氣 hedging', summary: '不要把話說死。',
    body: '用 may, might, tend to, appear to, suggest, relatively, largely 讓主張保守。這是歐美學術寫作的核心禮儀。',
    examples: [['The results suggest that…', '結果顯示……（而非證明）'], ['This may be partly explained by…', '這也許部分可以由……解釋'], ['The data tend to support this view.', '數據傾向支持這個觀點。']],
    tip: '把 proves 改成 suggests，整篇文章的專業度會立刻提升。' },
  { id: 'en-g-090', stage: 5, title: '連接與過渡詞', summary: '讓段落之間有邏輯。',
    body: '對比：however, in contrast；補充：moreover, in addition；因果：therefore, as a result；舉例：for instance；結論：overall, in conclusion。',
    examples: [['However, the sample was small.', '然而，樣本數偏少。'], ['Moreover, the cost was lower.', '此外，成本較低。'], ['Overall, the approach works well.', '整體而言，這個方法可行。']],
    tip: 'However 後面要逗號，而且不能像 but 一樣直接連兩個子句。' },
  { id: 'en-g-091', stage: 5, title: '轉述動詞', summary: 'argue, claim, suggest, note 有不同語氣。',
    body: '中性：state, note, report；有立場：argue, claim（暗示有爭議）；謹慎：suggest, indicate。',
    examples: [['Novák (2023) argues that…', 'Novák（2023）主張……'], ['The report notes that…', '該報告指出……'], ['Some scholars claim that…', '有些學者聲稱……']],
    tip: 'claim 帶懷疑意味，引用你認同的來源時別用它。' },
  { id: 'en-g-092', stage: 5, title: '改寫與摘要', summary: 'paraphrase 是避免抄襲的核心技能。',
    body: '改寫＝換字＋換結構＋仍要標註來源。只換幾個同義字仍算抄襲。',
    examples: [['Original: The policy reduced costs significantly.', '原文'], ['Paraphrase: Costs fell markedly after the policy was introduced (Novák, 2023).', '改寫版'], ['In other words, the approach saves money.', '換句話說，這個做法能省錢。']],
    tip: '歐洲大學對抄襲零容忍，交換生被退學的案例多半栽在這裡。' },
  { id: 'en-g-093', stage: 5, title: '正式 vs 非正式用語', summary: '同一個意思，兩種說法。',
    body: 'get → obtain／receive；a lot of → a considerable number of；find out → discover；kids → children；stuff → materials。',
    examples: [['We obtained the data from the university.', '我們自校方取得資料。'], ['A considerable number of students applied.', '相當多學生提出申請。'], ['The materials are available online.', '材料可線上取得。']],
    tip: '口語照舊，寫作換成正式版——不用兩邊都改。' },
  { id: 'en-g-094', stage: 5, title: 'Email 的開頭與結尾慣例', summary: '歐洲學術圈的標準格式。',
    body: '正式：Dear Professor X, ／ Dear Sir or Madam, 結尾 Kind regards / Best regards。半正式：Hi X, 結尾 Best / Thanks。',
    examples: [['Dear Dr Nováková, I hope this email finds you well.', '親愛的 Nováková 博士：希望您一切安好。'], ['I am writing regarding the course registration.', '我來信是關於選課事宜。'], ['Thank you in advance. Kind regards, Josh', '先謝謝您。祝好，Josh']],
    tip: '歐洲人普遍比美式更正式，第一封信寧可保守一點。' },
  { id: 'en-g-095', stage: 5, title: '婉拒與協商', summary: '拒絕但不失禮。',
    body: '先感謝 → 說明原因 → 提替代方案。避免直接說 No, I can’t。',
    examples: [['Thanks for the invite, but I have a deadline that day.', '謝謝邀請，不過那天我有截止日。'], ['I’d love to, but could we do it next week instead?', '我很想去，不過可以改下週嗎？'], ['Would Thursday work for you?', '星期四你方便嗎？']],
    tip: 'Would … work for you? 是協商時間最好用的句子。' },
  { id: 'en-g-096', stage: 5, title: '課堂討論發言句型', summary: '加入討論、表達同意與異議。',
    body: '插話：Can I just add something? 同意：That’s a good point. 異議：I see your point, but…',
    examples: [['Can I add something to that?', '我可以補充一點嗎？'], ['I see what you mean, but I’d argue that…', '我懂你的意思，不過我認為……'], ['Building on what Anna said…', '延續 Anna 說的……']],
    tip: '第三句是研討課的高級技巧：接住別人的話再延伸，教授會記住你。' },
  { id: 'en-g-097', stage: 5, title: '聽不懂時的求助句', summary: '別點頭裝懂。',
    body: '請對方重說、放慢、換句話說、或確認理解。這是留學生最該練熟的一組。',
    examples: [['Sorry, could you say that again?', '抱歉，可以再說一次嗎？'], ['Could you speak a bit more slowly, please?', '可以說慢一點嗎？'], ['So, if I understand correctly, you mean…', '所以如果我理解正確，你的意思是……']],
    tip: '第三句最強：既確認了理解，又展現你在認真聽。' },
  { id: 'en-g-098', stage: 5, title: '台灣人常見英文錯誤', summary: '一次修正六個高頻錯。',
    body: '① 漏第三人稱 -s ② informations／advices ③ when I will arrive ④ discuss about（discuss 不加 about）⑤ I very like it（改 I really like it）⑥ open/close the light（改 turn on/off）。',
    examples: [['✗ He don’t know. → ✓ He doesn’t know.', '他不知道。'], ['✗ discuss about it → ✓ discuss it', '討論它'], ['✗ I very like it → ✓ I really like it', '我很喜歡']],
    tip: '這六個改掉，你的英文聽起來會立刻乾淨一階。' },
  { id: 'en-g-099', stage: 5, title: '自我推銷與面試句型', summary: '實習、打工、研究職都用得到。',
    body: '結構：現在的身分 → 相關經驗 → 具體成果 → 為什麼是你。用數字說話。',
    examples: [['I’m currently an exchange student in computer science.', '我目前是資訊系交換生。'], ['I built a data pipeline that cut processing time by 40%.', '我做過一條資料流程，把處理時間縮短四成。'], ['I’d bring both technical skills and a cross-cultural perspective.', '我能帶來技術能力與跨文化視角。']],
    tip: '歐洲面試不喜歡誇張，具體數字比形容詞有力得多。' },
  { id: 'en-g-100', stage: 5, title: '結業：如何持續進步', summary: '100 天之後的英文練法。',
    body: '輸入：每天讀一篇英文新聞或論文摘要。輸出：每週寫一封英文信、參加一次討論。修正：把講不出來的句子記下來查。語言是習慣，不是知識。',
    examples: [['I try to read one article a day.', '我試著每天讀一篇文章。'], ['I keep a list of phrases I want to use.', '我會記下想用的句子。'], ['Making mistakes is part of the process.', '犯錯是過程的一部分。']],
    tip: '在捷克，英文是你和全世界同學的共同語言——用得越多，進步越快。' },
];
