/**
 * 捷克文 100 課文法（零基礎 → A2）。100 天課程每天上一課，順序不可調動。
 *
 * 每課：{ id, stage, title, summary, body, examples:[[捷克, 中文]], table?, tip? }
 */

export const CZ_STAGES = [
  { id: 1, name: '第一階 · 發音與最基本的句子', range: '第 1–20 課' },
  { id: 2, name: '第二階 · 動詞現在式與第四格', range: '第 21–40 課' },
  { id: 3, name: '第三階 · 過去式與地點方向', range: '第 41–60 課' },
  { id: 4, name: '第四階 · 完整七格與動詞體', range: '第 61–80 課' },
  { id: 5, name: '第五階 · 條件式、比較與實戰', range: '第 81–100 課' },
];

export const CZ_GRAMMAR = [
  // ─────────── 第一階：發音與最基本的句子 ───────────
  {
    id: 'cs-g-001', stage: 1,
    title: '捷克語怎麼唸：寫什麼就唸什麼',
    summary: '沒有不發音的字母，重音永遠在第一個音節。',
    body: '捷克語是「所見即所讀」的語言：每個字母固定一個音，不像英文的 through / though。唯一要記的規則是重音永遠落在第一個音節，而且重音不影響母音長短——長短由字母上的撇號決定。',
    examples: [['Ahoj!', '嗨！'], ['Dobrý den.', '您好。'], ['Děkuji.', '謝謝。']],
    tip: '看到再長的字也不要怕：Nejneobhospodařovávatelnějšímu 也是照字母一個一個唸。',
  },
  {
    id: 'cs-g-002', stage: 1,
    title: '長音符號 čárka：á é í ó ú ů ý',
    summary: '撇號代表把母音拉長，長短會改變字義。',
    body: '母音上的撇號（čárka）表示唸長一倍。ú 和 ů 都唸長 u，差別只在拼字位置：ú 用在字首，ů 用在字中或字尾。長短是辨義的，不是裝飾。',
    examples: [['byt / být', '公寓 ／ 是'], ['dráha / drahá', '軌道 ／ 昂貴的'], ['úterý, dům', '星期二、房子']],
    tip: '台灣學生最常忽略長音，結果 "Mám" 唸成 "Mam"，聽起來像在含滷蛋。刻意拉長一倍就對了。',
  },
  {
    id: 'cs-g-003', stage: 1,
    title: 'háček 小帽子：č š ž ě ň ť ď',
    summary: 'ˇ 把子音變成「捲舌／顎化」的音。',
    body: 'háček（小帽子）會改變子音：č＝ㄑ（church）、š＝ㄕ（shop）、ž＝法文 j（vision）、ň＝ny、ť＝ty、ď＝dy。母音上的 ě 則讓前面的子音變軟：mě 唸 mnye、tě 唸 tye。',
    examples: [['čaj, škola, žena', '茶、學校、女人'], ['děkuji, těší mě', '謝謝、幸會'], ['neděle', '星期日']],
    tip: 'ě 不是「e 的變體」而是「軟化記號」，dě/tě/ně 一律唸成 dye/tye/nye。',
  },
  {
    id: 'cs-g-004', stage: 1,
    title: '傳說中的 ř',
    summary: '全世界只有捷克語有的音，先用「rzh」近似。',
    body: 'ř 是捲舌 r 加上 ž 的摩擦音，同時發出。捷克小孩也要練到六、七歲。初學者可以先唸成 rzh（如 Dvořák＝DVOR-zhaak），當地人完全聽得懂，而且會很驚喜。',
    examples: [['řeka', '河'], ['přítel', '朋友'], ['dobře', '好、不錯']],
    tip: '練法：先唸長長的 rrrr，中途把舌尖放鬆一點點讓氣流磨擦，就會出現 ř 的雛形。',
  },
  {
    id: 'cs-g-005', stage: 1,
    title: '捷克語沒有 a / the',
    summary: '沒有冠詞，語序也比英文自由。',
    body: '捷克語沒有冠詞，「一本書」和「那本書」都是 kniha，靠上下文與語序表達。語序自由是因為字尾（格）已經標示了誰是主詞誰是受詞，但一般語序仍是「主詞—動詞—受詞」。',
    examples: [['Mám knihu.', '我有一本書。'], ['Kniha je na stole.', '書在桌上。'], ['Tu knihu mám.', '那本書我有。（強調）']],
    tip: '把英文的 a/the 直接丟掉，是台灣學生最快能上手的一件事。',
  },
  {
    id: 'cs-g-006', stage: 1,
    title: '動詞 být（是）的現在式',
    summary: '第一個必須背起來的動詞變化。',
    body: 'být 是最不規則但最常用的動詞。捷克語動詞字尾已經標示人稱，所以主詞代名詞通常省略：不用說 Já jsem，說 Jsem 就好。',
    table: { head: ['人稱', '形式', '中文'], rows: [['já', 'jsem', '我是'], ['ty', 'jsi', '你是'], ['on/ona/ono', 'je', '他/她/它是'], ['my', 'jsme', '我們是'], ['vy', 'jste', '你們／您是'], ['oni', 'jsou', '他們是']] },
    examples: [['Jsem student.', '我是學生。'], ['Jsi z Tchaj-wanu?', '你來自台灣嗎？'], ['Je to daleko.', '那很遠。']],
    tip: '女生說「我是學生」要用 studentka：Jsem studentka.',
  },
  {
    id: 'cs-g-007', stage: 1,
    title: '人稱代名詞與「省略主詞」',
    summary: 'já ty on ona my vy oni——但通常不說出口。',
    body: '主詞代名詞只在強調或對比時才出現。vy 同時是「你們」和禮貌的「您」，對陌生人、老師、店員一律用 vy（vykat）。',
    examples: [['Mluvím česky.', '我說捷克語。'], ['Já mluvím česky, on ne.', '我說捷克語，他不會。（強調）'], ['Odkud jste?', '您從哪裡來？']],
    tip: '一直說 já 會顯得很自我中心，捷克人聽起來怪怪的。',
  },
  {
    id: 'cs-g-008', stage: 1,
    title: '是非疑問句：只要提高語調',
    summary: '不用助動詞，語調上揚就是問句。',
    body: '捷克語問句不需要 do/does 這類助動詞，也不一定要調換語序，把句尾語調拉高即可。若要更明顯，可以把動詞放到句首。',
    examples: [['Mluvíte anglicky?', '您會說英文嗎？'], ['Je to volné?', '這位子空著嗎？'], ['Máte tašku?', '你們有袋子嗎？']],
    tip: '回答「是」用 Ano（正式）或 Jo（口語）；「不是」用 Ne。',
  },
  {
    id: 'cs-g-009', stage: 1,
    title: '否定：動詞前面黏一個 ne-',
    summary: 'ne- 直接寫在動詞前面，不分開。',
    body: '捷克語的否定極簡單：把 ne- 加在動詞前，連在一起寫。而且捷克語用「雙重否定」——否定詞和動詞都要否定。',
    examples: [['Nerozumím.', '我不懂。'], ['Nevím.', '我不知道。'], ['Nikdo nic neví.', '沒有人知道任何事。']],
    tip: '用英文邏輯想「雙重否定＝肯定」會全錯，捷克語是否定到底。',
  },
  {
    id: 'cs-g-010', stage: 1,
    title: '動詞 mít（有）的現在式',
    summary: '第二個必背動詞，也用來表達年齡與感受。',
    body: 'mít 除了「擁有」，還用在很多固定句型：mít hlad（餓）、mít čas（有空）、mít rád（喜歡）、je mi … let（年齡則用 být）。',
    table: { head: ['人稱', '形式'], rows: [['já', 'mám'], ['ty', 'máš'], ['on/ona', 'má'], ['my', 'máme'], ['vy', 'máte'], ['oni', 'mají']] },
    examples: [['Mám hlad.', '我餓了。'], ['Nemáš čas?', '你沒空嗎？'], ['Máme zkoušku.', '我們有考試。']],
    tip: '否定同樣是加 ne-：nemám, nemáš, nemá…',
  },
  {
    id: 'cs-g-011', stage: 1,
    title: '名詞有三個性別',
    summary: '看字尾就能猜出陽性、陰性、中性。',
    body: '每個名詞都有性別，決定形容詞與動詞過去式的形式。多數情況看字尾即可判斷：子音結尾＝陽性，-a 結尾＝陰性，-o／-e／-í 結尾＝中性。少數例外要個別記（例如 -ost 結尾是陰性）。',
    table: { head: ['性別', '典型字尾', '例子'], rows: [['陽性 m', '子音', 'student, dům, klíč'], ['陰性 f', '-a, -e, -ost', 'káva, židle, radost'], ['中性 n', '-o, -e, -í', 'pivo, moře, nádraží']] },
    examples: [['dobrý student', '好學生（陽）'], ['dobrá káva', '好咖啡（陰）'], ['dobré pivo', '好啤酒（中）']],
    tip: '學新名詞時一定要連性別一起記，之後所有變格都靠它。',
  },
  {
    id: 'cs-g-012', stage: 1,
    title: 'To je… ／ To jsou…（這是……）',
    summary: '萬用的介紹句型，to 不隨性別變化。',
    body: '指認事物時，一律用中性的 to，不管後面的名詞是什麼性別。複數用 to jsou。',
    examples: [['To je moje kamarádka.', '這是我的朋友（女）。'], ['To jsou moji spolužáci.', '這些是我的同學。'], ['Co je to?', '這是什麼？']],
    tip: '別因為後面是陰性名詞就把 to 改成 ta，介紹句永遠用 to。',
  },
  {
    id: 'cs-g-013', stage: 1,
    title: '基本疑問詞：kdo, co, kde, kdy, jak, proč',
    summary: '六個疑問詞就能問出九成的事。',
    body: '疑問詞放句首，後面接動詞。注意 kde（在哪裡，靜止）和 kam（去哪裡，移動）是兩個不同的字。',
    examples: [['Kde je záchod?', '廁所在哪裡？'], ['Kam jdeš?', '你要去哪裡？'], ['Proč? Protože musím.', '為什麼？因為我必須。']],
    tip: 'Co prosím? ＝「你說什麼？」比 Co? 有禮貌得多。',
  },
  {
    id: 'cs-g-014', stage: 1,
    title: '形容詞要跟著名詞變性別',
    summary: '硬變化：-ý（陽）／-á（陰）／-é（中）。',
    body: '形容詞必須與名詞的性別一致。大部分形容詞是「硬變化」，字尾 -ý/-á/-é；少部分是「軟變化」，三性都用 -í（例如 moderní）。',
    examples: [['dobrý den', '好日子（陽）'], ['dobrá káva', '好咖啡（陰）'], ['dobré ráno', '早安（中）']],
    tip: '學到形容詞就順手練三種形式，之後遇到變格才不會卡住。',
  },
  {
    id: 'cs-g-015', stage: 1,
    title: '數字 1–10 與「一」的性別',
    summary: 'jeden / jedna / jedno 會跟著名詞變。',
    body: '只有「1」和「2」有性別：jeden（陽）／jedna（陰）／jedno（中）；dva（陽）／dvě（陰、中）。3 以上不分性別。',
    examples: [['jeden student, jedna káva, jedno pivo', '一個學生、一杯咖啡、一杯啤酒'], ['dva bratři, dvě sestry', '兩個兄弟、兩個姊妹'], ['tři piva, prosím', '請給我三杯啤酒']],
    tip: '點餐時最常用：Jedno pivo, prosím.（pivo 是中性，所以是 jedno）',
  },
  {
    id: 'cs-g-016', stage: 1,
    title: '5 以上的數字要接複數第二格',
    summary: 'pět piv、šest korun——名詞會變形。',
    body: '這是捷克語很特別的規則：1 接單數、2–4 接複數主格、5 以上接複數第二格。剛開始只要背常用組合就好。',
    table: { head: ['數量', '形式', '例'], rows: [['1', '單數', 'jedno pivo'], ['2–4', '複數主格', 'dvě piva'], ['5+', '複數第二格', 'pět piv']] },
    examples: [['dvě kávy / pět káv', '兩杯咖啡／五杯咖啡'], ['tři koruny / sto korun', '三克朗／一百克朗'], ['čtyři dny / deset dní', '四天／十天']],
    tip: '菜單和收據上滿滿都是這個規則，多看幾次就內化了。',
  },
  {
    id: 'cs-g-017', stage: 1,
    title: '問價錢：Kolik to stojí?',
    summary: 'stát 這個動詞同時是「站」和「值多少」。',
    body: 'Kolik（多少）＋ to（它）＋ stojí（值）。回答時金額後面接 korun（複數第二格）。也可以問 Kolik to bude?（總共多少）。',
    examples: [['Kolik to stojí?', '這多少錢？'], ['Sto padesát korun.', '一百五十克朗。'], ['Kolik to bude celkem?', '總共多少？']],
    tip: '捷克價格寫成 150 Kč 或 150,- ；小數點用逗號。',
  },
  {
    id: 'cs-g-018', stage: 1,
    title: '星期與「在星期幾」',
    summary: 'v + 星期，星期一是一週的開始。',
    body: '「在星期幾」用 v ＋ 星期名稱的第四格，但實務上多數星期名詞形式變化很小，可先整組背下來。',
    examples: [['v pondělí', '在星期一'], ['ve středu', '在星期三'], ['o víkendu', '在週末']],
    tip: 'středa → ve středu、neděle → v neděli 這兩個會變，其他大致不變。',
  },
  {
    id: 'cs-g-019', stage: 1,
    title: '幾點鐘',
    summary: 'Kolik je hodin? 與 v + 數字 + hodin。',
    body: '問時間用 Kolik je hodin?（現在幾點）。回答用 Je jedna hodina／Jsou dvě hodiny／Je pět hodin，正好呼應 1／2-4／5+ 的規則。',
    examples: [['Kolik je hodin?', '現在幾點？'], ['Je půl třetí.', '兩點半。（字面：三點的一半）'], ['Přednáška začíná v devět.', '課九點開始。']],
    tip: 'půl 的邏輯是「往下一個整點的一半」：půl třetí＝2:30，不是 3:30。這點超容易搞錯。',
  },
  {
    id: 'cs-g-020', stage: 1,
    title: '複習 1：完整自我介紹',
    summary: '把前 19 課串成一段能實際用的話。',
    body: '用 být＋mít＋否定＋疑問詞，你已經可以做完整的自我介紹並反問對方。到宿舍第一天就是講這一段。',
    examples: [['Ahoj, jmenuji se Josh. Jsem z Tchaj-wanu.', '嗨，我叫 Josh，來自台灣。'], ['Jsem výměnný student a bydlím na koleji.', '我是交換學生，住在宿舍。'], ['Mluvím jen trochu česky. A ty?', '我只會一點捷克語。你呢？']],
    tip: '把這三句練到不用想就能說出口，比多背 50 個單字有用。',
  },

  // ─────────── 第二階：動詞現在式與第四格 ───────────
  {
    id: 'cs-g-021', stage: 2,
    title: '動詞現在式的三大類',
    summary: '看第一人稱字尾：-ám / -ím / -u。',
    body: '捷克語動詞依現在式變化分三類：第一類 -ám（dělám）、第二類 -ím（mluvím）、第三類 -u/-i（piju, čtu）。查字典時記下第一人稱形式，整組變化就跟著出來。',
    table: { head: ['類別', '原形', '我', '你', '他'], rows: [['I', 'dělat', 'dělám', 'děláš', 'dělá'], ['II', 'mluvit', 'mluvím', 'mluvíš', 'mluví'], ['III', 'pít', 'piju', 'piješ', 'pije']] },
    examples: [['Co děláš?', '你在做什麼？'], ['Mluvím česky.', '我說捷克語。'], ['Piju kafe.', '我在喝咖啡。']],
    tip: '捷克語沒有進行式，「我做」和「我正在做」同一個形式。',
  },
  {
    id: 'cs-g-022', stage: 2,
    title: '第一類動詞 -at → -ám',
    summary: '最規則、最好學的一組。',
    body: '原形 -at 的動詞多半屬於這類：dělat, čekat, hledat, ptát se, znát, dávat。字尾依序是 -ám, -áš, -á, -áme, -áte, -ají。',
    table: { head: ['人稱', 'dělat'], rows: [['já', 'dělám'], ['ty', 'děláš'], ['on', 'dělá'], ['my', 'děláme'], ['vy', 'děláte'], ['oni', 'dělají']] },
    examples: [['Čekám na tramvaj.', '我在等電車。'], ['Hledáme tuhle adresu.', '我們在找這個地址。'], ['Co děláte zítra?', '你們明天做什麼？']],
    tip: '第三人稱複數是 -ají 不是 -ámí，這裡最常寫錯。',
  },
  {
    id: 'cs-g-023', stage: 2,
    title: '第二類動詞 -it / -et → -ím',
    summary: 'mluvit, bydlet, rozumět 都屬這類。',
    body: '字尾 -ím, -íš, -í, -íme, -íte, -í(-ejí)。注意第三人稱單數和複數常常同形，要靠主詞判斷。',
    table: { head: ['人稱', 'mluvit'], rows: [['já', 'mluvím'], ['ty', 'mluvíš'], ['on', 'mluví'], ['my', 'mluvíme'], ['vy', 'mluvíte'], ['oni', 'mluví']] },
    examples: [['Bydlím v Praze.', '我住在布拉格。'], ['Nerozumím dobře.', '我聽不太懂。'], ['Vidíš to?', '你看到了嗎？']],
    tip: 'rozumět 的他們＝rozumějí，這類 -et 動詞複數會多一個 -ejí。',
  },
  {
    id: 'cs-g-024', stage: 2,
    title: '第三類 -ovat → -uju',
    summary: '外來語動詞幾乎都是這一類。',
    body: '-ovat 結尾的動詞（studovat, pracovat, rezervovat, kontrolovat）變成 -uju, -uješ, -uje, -ujeme, -ujete, -ujou。正式書寫用 -uji / -ují。',
    examples: [['Studuju informatiku.', '我讀資訊。'], ['Pracuju na koleji.', '我在宿舍打工。'], ['Rezervujeme stůl.', '我們訂位。']],
    tip: '口語 -uju／書面 -uji，兩種都對，寫報告用 -uji 比較穩。',
  },
  {
    id: 'cs-g-025', stage: 2,
    title: 'jít 還是 jet？走路去 vs 搭車去',
    summary: '捷克語一定要區分「用腳」和「用工具」。',
    body: 'jít＝步行前往（jdu, jdeš, jde），jet＝搭交通工具前往（jedu, jedeš, jede）。這是台灣學生最常忽略的區別。',
    examples: [['Jdu do školy.', '我走路去學校。'], ['Jedu do Brna.', '我（搭車）去布爾諾。'], ['Jdeme na pivo?', '要不要去喝一杯？']],
    tip: '從台北到布拉格只能用 letět（飛）或 jet，絕對不能用 jít，除非你真的想用走的。',
  },
  {
    id: 'cs-g-026', stage: 2,
    title: 'chtít（想要）',
    summary: '不規則但超高頻，直接整組背。',
    body: 'chci, chceš, chce, chceme, chcete, chtějí。後面可以接名詞（第四格）或動詞原形。禮貌一點會用條件式 chtěl bych（第 81 課）。',
    examples: [['Chci kávu.', '我要咖啡。'], ['Nechceš jít s námi?', '你不跟我們一起去嗎？'], ['Co chcete dělat?', '你們想做什麼？']],
    tip: '直接說 Chci… 在店裡有點衝，加個 prosím 或用 Dám si… 更自然。',
  },
  {
    id: 'cs-g-027', stage: 2,
    title: 'moct / muset / smět：能、必須、可以',
    summary: '情態動詞後面接原形動詞。',
    body: 'moct（能力／可能）：můžu, můžeš, může…；muset（必須）：musím, musíš…；smět（獲准）：smím, smíš…。否定 nemusím 是「不必」，不是「不可以」。',
    examples: [['Můžu platit kartou?', '我可以刷卡嗎？'], ['Musím jít na úřad.', '我必須去公家機關。'], ['Nemusíš čekat.', '你不必等。']],
    tip: '「不可以」要說 nesmíš，說成 nemusíš 意思會完全相反。',
  },
  {
    id: 'cs-g-028', stage: 2,
    title: 'umět / znát / vědět：三種「知道」',
    summary: '會技能、認識人事物、知道事實。',
    body: 'umět＝學會某項能力（會說捷克語、會游泳）；znát＝認識人、地方、東西；vědět＝知道一件事實，後面常接 že 或疑問詞。',
    examples: [['Umím trochu česky.', '我會一點捷克語。'], ['Znáš tu restauraci?', '你知道那家餐廳嗎？'], ['Nevím, kde to je.', '我不知道那在哪裡。']],
    tip: '「我不知道」是 Nevím，不是 Neznám。講錯會變成「我不認識它」。',
  },
  {
    id: 'cs-g-029', stage: 2,
    title: '第四格（akuzativ）：動作的對象',
    summary: '受詞要變形，這是第一個要學的格。',
    body: '捷克語用字尾標示句子成分。及物動詞（mít, chtít, vidět, dát si, koupit）後面的受詞要用第四格。先掌握最常見的陰性 -a → -u。',
    examples: [['Mám kávu.', '我有咖啡。（káva → kávu）'], ['Vidím tramvaj.', '我看到電車。'], ['Dám si vodu.', '我要水。']],
    tip: '菜單上是 káva，你要點的時候變成 kávu——不是打錯字，是變格。',
  },
  {
    id: 'cs-g-030', stage: 2,
    title: '陰性名詞第四格：-a → -u',
    summary: '最好記的一條變格規則。',
    body: '以 -a 結尾的陰性名詞，第四格一律把 -a 換成 -u。以 -e 結尾的陰性名詞（židle, restaurace）第四格不變。',
    table: { head: ['主格', '第四格', '中文'], rows: [['káva', 'kávu', '咖啡'], ['voda', 'vodu', '水'], ['polévka', 'polévku', '湯'], ['restaurace', 'restauraci', '餐廳']] },
    examples: [['Dám si polévku.', '我要一份湯。'], ['Hledám zastávku.', '我在找站牌。'], ['Máš jízdenku?', '你有車票嗎？']],
    tip: '點餐幾乎都是陰性食物名詞，練熟這條就能點一半的菜單。',
  },
  {
    id: 'cs-g-031', stage: 2,
    title: '陽性第四格：有生命 vs 無生命',
    summary: '有生命的加 -a，無生命的不變。',
    body: '陽性名詞分「有生命」（人、動物）和「無生命」。有生命第四格加 -a（student → studenta）；無生命維持原形（dům → dům）。',
    examples: [['Vidím studenta.', '我看到一個學生。'], ['Mám klíč.', '我有鑰匙。（無生命不變）'], ['Znám toho profesora.', '我認識那位教授。']],
    tip: '這也是為什麼 Mám psa（我有一隻狗）要加 -a，Mám byt（我有公寓）不用。',
  },
  {
    id: 'cs-g-032', stage: 2,
    title: '中性名詞第四格：完全不變',
    summary: 'pivo → pivo，最輕鬆的一格。',
    body: '中性名詞（-o, -e, -í 結尾）的第一格和第四格永遠相同，不必做任何事。',
    examples: [['Dám si pivo.', '我要一杯啤酒。'], ['Mám auto.', '我有車。'], ['Vidím nádraží.', '我看到火車站。']],
    tip: '所以你在捷克講的第一句完整句子 Dám si pivo 其實已經用到第四格了。',
  },
  {
    id: 'cs-g-033', stage: 2,
    title: '點餐句型：Dám si…',
    summary: '進餐廳只要會這一句就活得下去。',
    body: 'dát si 是反身動詞，字面是「給自己」，功能等於英文的 I will have。後面接第四格。結帳說 Zaplatím, prosím.',
    examples: [['Dám si guláš a velké pivo.', '我要燉牛肉和一杯大啤酒。'], ['Dáme si dvě kávy.', '我們要兩杯咖啡。'], ['Zaplatím, prosím.', '我要結帳。']],
    tip: '服務生不會主動送帳單，不開口就會一直坐到打烊。',
  },
  {
    id: 'cs-g-034', stage: 2,
    title: '形容詞的第四格',
    summary: '形容詞跟著名詞一起變。',
    body: '陰性 -á → -ou（velká → velkou）；中性不變；陽性無生命不變、有生命 -ý → -ého。',
    examples: [['Dám si velkou kávu.', '我要一杯大咖啡。'], ['Mám nové kolo.', '我有一台新腳踏車。'], ['Znám toho nového studenta.', '我認識那個新來的學生。']],
    tip: '「大杯啤酒」是 velké pivo（中性不變），「大杯咖啡」是 velkou kávu，別混在一起。',
  },
  {
    id: 'cs-g-035', stage: 2,
    title: '反身動詞 se 與 si',
    summary: 'se ＝自己（受詞），si ＝給自己（間接）。',
    body: '很多動詞固定帶 se 或 si：jmenovat se（叫做）、učit se（學習）、dát si（點餐）、koupit si（買給自己）。se/si 幾乎總是放在句子的第二個位置。',
    examples: [['Jmenuji se Josh.', '我叫 Josh。'], ['Učím se česky.', '我在學捷克語。'], ['Koupil jsem si kolo.', '我買了一台腳踏車。']],
    tip: '第二位規則：Já se jmenuji…（se 在第二位），不是 Já jmenuji se。',
  },
  {
    id: 'cs-g-036', stage: 2,
    title: '頻率副詞與位置',
    summary: 'vždycky, často, někdy, nikdy 放動詞前。',
    body: '頻率副詞通常放在動詞前面。nikdy（從不）必須搭配否定動詞——又是雙重否定。',
    examples: [['Vždycky piju kávu ráno.', '我早上總是喝咖啡。'], ['Často chodím do knihovny.', '我常去圖書館。'], ['Nikdy nejím maso.', '我從不吃肉。']],
    tip: 'Nikdy jím maso 是錯的，一定要 Nikdy nejím。',
  },
  {
    id: 'cs-g-037', stage: 2,
    title: 'rád / ráda ＋ 動詞：我喜歡做某事',
    summary: 'rád 會跟著說話者的性別變。',
    body: '「喜歡做某事」用 rád（男）／ráda（女）＋ 動詞現在式，不是加原形。這是捷克語很特別的結構。',
    examples: [['Rád vařím.', '我喜歡做菜。（男生說）'], ['Ráda cestuju.', '我喜歡旅行。（女生說）'], ['Rádi chodíme na výlety.', '我們喜歡去小旅行。']],
    tip: '呱呱說 rád、花花說 ráda，講錯會立刻被聽出來。',
  },
  {
    id: 'cs-g-038', stage: 2,
    title: 'mít rád vs líbit se',
    summary: '長期喜好 vs 當下覺得好看好聽。',
    body: 'mít rád＝長期喜歡某人事物（後接第四格）；líbit se＝看到／聽到當下覺得喜歡（句型是「某物 líbí se 我」，人用第三格 mi）。',
    examples: [['Mám rád pivo.', '我喜歡啤酒。'], ['Líbí se mi Praha.', '我喜歡布拉格（覺得漂亮）。'], ['Líbí se ti to?', '你喜歡嗎？']],
    tip: '對人說 Líbíš se mi 意思是「我對你有感覺」，不是普通的喜歡，用錯會很尷尬。',
  },
  {
    id: 'cs-g-039', stage: 2,
    title: '句子裡的語序：第二位規則',
    summary: 'se, si, jsem, mi, to 這些小詞黏在第二位。',
    body: '捷克語語序自由，但「短小詞」（clitics）有固定順序，永遠擠在句子的第二個位置，順序是：助動詞 → se/si → 代名詞。',
    examples: [['Včera jsem se učil česky.', '我昨天學了捷克語。'], ['Dneska se mi to nelíbí.', '我今天不喜歡這個。'], ['Ráno jsem si koupil rohlík.', '我早上買了一個麵包。']],
    tip: '句首放時間詞（Včera, Dneska, Ráno）是最安全的起手式，後面接 jsem se 就對了。',
  },
  {
    id: 'cs-g-040', stage: 2,
    title: '複習 2：在餐廳與商店存活',
    summary: '把第四格＋動詞現在式用出來。',
    body: '到這裡你已經可以完成一整套點餐與購物對話：問價、點餐、要收據、結帳。',
    examples: [['Dobrý den, dám si polévku a velké pivo.', '您好，我要一份湯和一杯大啤酒。'], ['Kolik to stojí? Můžu platit kartou?', '多少錢？可以刷卡嗎？'], ['Zaplatím, prosím. Účtenku, prosím.', '我要結帳，請給我收據。']],
    tip: '把這組對話錄音下來自己聽，比默背有效十倍。',
  },

  // ─────────── 第三階：過去式與地點方向 ───────────
  {
    id: 'cs-g-041', stage: 3,
    title: '過去式：動詞加 -l，男女不同',
    summary: 'dělal / dělala / dělalo ＋ jsem。',
    body: '捷克語過去式＝「動詞去掉 -t 加 -l」＋ být 的現在式當助動詞。而且要依主詞性別選 -l（男）／-la（女）／-lo（中）。第三人稱不加助動詞。',
    table: { head: ['主詞', '形式'], rows: [['já（男）', 'dělal jsem'], ['já（女）', 'dělala jsem'], ['ty（男）', 'dělal jsi'], ['on', 'dělal'], ['ona', 'dělala'], ['my', 'dělali jsme']] },
    examples: [['Byl jsem v Praze.', '我去過布拉格。（男）'], ['Byla jsem doma.', '我在家。（女）'], ['Včera pršelo.', '昨天下雨了。']],
    tip: '呱呱說 byl jsem、花花說 byla jsem——捷克語沒辦法隱藏性別。',
  },
  {
    id: 'cs-g-042', stage: 3,
    title: '過去式的助動詞位置',
    summary: 'jsem / jsi 永遠在第二位，第三人稱不用。',
    body: '助動詞 jsem, jsi, jsme, jste 必須放在句子的第二個位置，不能放句首。第三人稱單複數（on/ona/oni）不用助動詞。',
    examples: [['Včera jsem byl v kině.', '我昨天去了電影院。'], ['Kde jsi byla?', '你（女）去哪了？'], ['Oni přišli pozdě.', '他們遲到了。']],
    tip: 'Jsem byl v kině 是錯的；動詞或時間詞要先出場。',
  },
  {
    id: 'cs-g-043', stage: 3,
    title: '過去式的否定',
    summary: 'ne- 加在 -l 動詞上，助動詞不變。',
    body: '否定一樣是在主要動詞前加 ne-，助動詞 jsem/jsi 保持不變。',
    examples: [['Nebyl jsem tam.', '我沒去那裡。'], ['Nerozuměla jsem.', '我（女）沒聽懂。'], ['Nic jsem neřekl.', '我什麼都沒說。']],
    tip: '雙重否定照舊：Nic jsem neřekl（沒有什麼我沒說）＝我什麼都沒說。',
  },
  {
    id: 'cs-g-044', stage: 3,
    title: '第六格（lokál）：在哪裡',
    summary: '只跟介系詞一起出現的格：v, na, o, po。',
    body: '表達「在某處」用 v／na ＋ 第六格。陰性 -a → -ě/-e，中性 -o → -ě/-u，陽性多半加 -ě/-u。第六格永遠有介系詞，不會單獨出現。',
    table: { head: ['主格', '第六格', '中文'], rows: [['škola', 've škole', '在學校'], ['Praha', 'v Praze', '在布拉格'], ['kolej', 'na koleji', '在宿舍'], ['nádraží', 'na nádraží', '在車站']] },
    examples: [['Bydlím na koleji.', '我住在宿舍。'], ['Jsem ve škole.', '我在學校。'], ['Sejdeme se na náměstí.', '我們在廣場碰面。']],
    tip: 'Praha → v Praze 的 h→z 是規則變化，不是不同的城市。',
  },
  {
    id: 'cs-g-045', stage: 3,
    title: '國家與城市的位置說法',
    summary: 'v Česku, na Slovensku, na Tchaj-wanu。',
    body: '多數國家用 v，但島嶼與部分地區慣用 na。台灣是 na Tchaj-wanu（島），斯洛伐克也是 na Slovensku（歷史用法）。',
    examples: [['Jsem z Tchaj-wanu.', '我來自台灣。'], ['Studuju v Česku.', '我在捷克讀書。'], ['Byli jsme na Slovensku.', '我們去了斯洛伐克。']],
    tip: '捷克的正式國名是 Česká republika，日常說 Česko；Czechia 就是它的英文。',
  },
  {
    id: 'cs-g-046', stage: 3,
    title: 'v 還是 na？',
    summary: '封閉空間用 v，開放平面與活動用 na。',
    body: 'v＝在裡面（v restauraci, v bytě）；na＝在表面／在活動場合（na univerzitě, na koncertě, na poště）。很多要靠習慣記，先背常用組合。',
    examples: [['v obchodě', '在店裡'], ['na univerzitě', '在大學'], ['na poště', '在郵局']],
    tip: '學校用 ve škole，但大學用 na univerzitě——沒道理，就是習慣。',
  },
  {
    id: 'cs-g-047', stage: 3,
    title: '第二格（genitiv）：「的」與所有',
    summary: '最常出現的格，也是介系詞大本營。',
    body: '第二格表示所屬（誰的）、部分（一杯的），並跟隨 do, z, od, bez, u, vedle, blízko 等介系詞。陽性加 -a/-u，陰性 -a → -y，中性 -o → -a。',
    examples: [['klíč od pokoje', '房間的鑰匙'], ['sklenice vody', '一杯水'], ['bez cukru', '不加糖']],
    tip: '咖啡店必用：s mlékem（加牛奶，第七格）vs bez cukru（不加糖，第二格）。',
  },
  {
    id: 'cs-g-048', stage: 3,
    title: '第二格介系詞群：do / z / od / bez / u',
    summary: '「進入、出來、從某人、沒有、在旁邊」。',
    body: 'do＝進入（do školy）、z＝從裡面出來（z Prahy）、od＝從某人／某時（od kamaráda）、bez＝沒有、u＝在……旁邊或某人家。',
    examples: [['Jdu do knihovny.', '我去圖書館。'], ['Jsem z Tchaj-wanu.', '我來自台灣。'], ['Bydlím u kamaráda.', '我住在朋友家。']],
    tip: '「去哪裡」的 do 和「在哪裡」的 v 是一對，記成一組最有效率。',
  },
  {
    id: 'cs-g-049', stage: 3,
    title: 'kam vs kde：移動還是靜止',
    summary: 'do/na＋第四格（去），v/na＋第六格（在）。',
    body: '捷克語嚴格區分方向和位置。問「去哪裡」用 kam，答 do/na；問「在哪裡」用 kde，答 v/na。同一個地點會有兩種形式。',
    table: { head: ['地點', '去（kam）', '在（kde）'], rows: [['škola', 'do školy', 've škole'], ['Praha', 'do Prahy', 'v Praze'], ['kolej', 'na kolej', 'na koleji']] },
    examples: [['Kam jdeš? Do školy.', '你去哪？學校。'], ['Kde jsi? Ve škole.', '你在哪？學校。'], ['Jedu na nádraží.', '我要去火車站。']],
    tip: '搞混會被聽成「我在去學校裡面」這種怪句子，但捷克人通常還是懂。',
  },
  {
    id: 'cs-g-050', stage: 3,
    title: '問路完整句型',
    summary: 'Jak se dostanu…? ＋ 方位詞。',
    body: '最實用的問路句是 Jak se dostanu na/do …?（我怎麼到……？）。回答會用 rovně（直走）、doleva（左轉）、doprava（右轉）、první ulice（第一條街）。',
    examples: [['Jak se dostanu na Karlův most?', '我要怎麼去查理大橋？'], ['Jděte rovně a pak doleva.', '直走然後左轉。'], ['Je to daleko? Asi deset minut pěšky.', '很遠嗎？走路大約十分鐘。']],
    tip: '手機沒電時就靠這三句，記得先說 Promiňte。',
  },
  {
    id: 'cs-g-051', stage: 3,
    title: '第三格（dativ）：給某人',
    summary: '間接受詞，也用在「對我來說」。',
    body: '第三格表示動作的接受者。陽性加 -ovi/-u，陰性 -a → -ě，中性 -o → -u。代名詞常用縮寫 mi（給我）、ti（給你）、mu（給他）、jí（給她）。',
    examples: [['Dej mi to, prosím.', '請把那個給我。'], ['Napsal jsem kamarádovi.', '我寫訊息給朋友。'], ['Je mi zima.', '我覺得冷。（字面：對我來說冷）']],
    tip: 'Je mi 20 let（我 20 歲）、Je mi špatně（我不舒服）都是第三格句型。',
  },
  {
    id: 'cs-g-052', stage: 3,
    title: '要用第三格的動詞',
    summary: 'rozumět, pomáhat, volat, děkovat, líbit se。',
    body: '有些動詞的受詞不是第四格而是第三格，必須個別記：rozumět（懂某人）、pomáhat（幫某人）、děkovat（謝某人）、volat（打電話給某人）。',
    examples: [['Nerozumím ti.', '我不懂你的意思。'], ['Pomůžeš mi?', '你能幫我嗎？'], ['Děkuju vám.', '謝謝您。']],
    tip: 'Děkuju vám（第三格）不是 Děkuju vás，這個錯誤外國人天天犯。',
  },
  {
    id: 'cs-g-053', stage: 3,
    title: '身體不舒服：Bolí mě…',
    summary: '看醫生一定會用到的句型。',
    body: '結構是「痛的部位（主詞）＋ bolí ＋ 我（第四格 mě）」。多個部位用 bolí 的複數 bolí（同形）。',
    examples: [['Bolí mě hlava.', '我頭痛。'], ['Bolí mě v krku.', '我喉嚨痛。'], ['Je mi špatně.', '我不舒服／想吐。']],
    tip: '藥局櫃檯直接說 Bolí mě … , máte na to něco?（有藥嗎？）就能買到成藥。',
  },
  {
    id: 'cs-g-054', stage: 3,
    title: '第七格（instrumentál）：用……／和……',
    summary: '工具、交通方式、s ＋ 同伴。',
    body: '第七格表示「用某工具」或「與某人一起」（配 s）。陽性加 -em，陰性 -a → -ou，中性 -o → -em。',
    examples: [['Jedu autobusem.', '我搭公車。'], ['Píšu perem.', '我用筆寫。'], ['Jdu tam s kamarádem.', '我和朋友一起去。']],
    tip: '交通工具不加介系詞：jedu metrem，不是 jedu s metrem。',
  },
  {
    id: 'cs-g-055', stage: 3,
    title: 's ＋ 第七格：跟誰一起',
    summary: '咖啡加牛奶也是這個格。',
    body: 's（跟、加）後面接第七格。點餐時「加什麼」就用它：s mlékem（加奶）、se šlehačkou（加鮮奶油）。',
    examples: [['Kávu s mlékem, prosím.', '請給我加牛奶的咖啡。'], ['Byl jsem tam s Květou.', '我和 Květa 一起去的。'], ['Mluvím s profesorem.', '我在跟教授說話。']],
    tip: 's 遇到 s/z/š/ž 開頭的字會變成 se（se sestrou），只是為了好唸。',
  },
  {
    id: 'cs-g-056', stage: 3,
    title: '天氣句型',
    summary: '無主詞句：Prší. Sněží. Je zima.',
    body: '天氣句多半沒有主詞，直接用第三人稱動詞或 je ＋ 副詞。Je zima（很冷）、Je teplo（很暖）、Prší（下雨）、Sněží（下雪）。',
    examples: [['Venku prší.', '外面在下雨。'], ['V zimě tady hodně sněží.', '這裡冬天常下雪。'], ['Je mi zima.', '我覺得冷。（加 mi 就變成人的感受）']],
    tip: 'Je zima 是「天氣冷」，Je mi zima 是「我冷」——差一個 mi。',
  },
  {
    id: 'cs-g-057', stage: 3,
    title: '月份與日期',
    summary: 'v lednu（在一月）、prvního ledna（一月一日）。',
    body: '「在某月」用 v ＋ 第六格（v lednu, v únoru）。日期用序數第二格＋月份第二格：prvního ledna＝一月一日。捷克月份名都是斯拉夫本土詞，很有畫面。',
    examples: [['Semestr začíná v září.', '學期九月開始。'], ['Přijedu dvacátého srpna.', '我八月二十日到。'], ['Narodil jsem se v květnu.', '我五月出生。']],
    tip: 'listopad（十一月）＝「落葉」，květen（五月）＝「花開」，用意思記比死背快。',
  },
  {
    id: 'cs-g-058', stage: 3,
    title: '年齡與時間長度',
    summary: 'Je mi 25 let. / na jeden semestr.',
    body: '年齡用「Je mi ＋ 數字 ＋ let」（第三格＋複數第二格）。時間長度用 na ＋ 第四格表示預計停留多久。',
    examples: [['Je mi dvacet pět let.', '我二十五歲。'], ['Jsem tu na jeden semestr.', '我在這裡待一個學期。'], ['Kolik ti je?', '你幾歲？']],
    tip: '1 用 rok、2-4 用 roky、5 以上用 let，又是那條數量規則。',
  },
  {
    id: 'cs-g-059', stage: 3,
    title: '一天的行程怎麼說',
    summary: '用時間副詞把動詞串起來。',
    body: '先講時間（Ráno / Odpoledne / Večer），再接動詞，助動詞放第二位。這是最自然的敘事順序。',
    examples: [['Ráno jsem šel na přednášku.', '我早上去上課。'], ['Odpoledne jsem se učil v knihovně.', '下午我在圖書館唸書。'], ['Večer jsme byli na pivu.', '晚上我們去喝啤酒。']],
    tip: 'být na pivu（去喝一杯）是固定說法，用第六格。',
  },
  {
    id: 'cs-g-060', stage: 3,
    title: '複習 3：講一個過去的週末',
    summary: '過去式＋地點＋方向的整合練習。',
    body: '把第 41–59 課組合起來，講一段三到四句的週末敘述，這已經是 A2 的口說水準。',
    examples: [['O víkendu jsem jel do Brna.', '我週末去了布爾諾。'], ['Byli jsme v muzeu a pak na obědě.', '我們去了博物館，然後吃午餐。'], ['Vrátil jsem se v neděli večer.', '我星期天晚上回來的。']],
    tip: '寫下來、唸三次、錄音——這一課的效果來自開口，不是閱讀。',
  },

  // ─────────── 第四階：完整七格與動詞體 ───────────
  {
    id: 'cs-g-061', stage: 4,
    title: '七個格總覽',
    summary: '一張表看懂捷克語的骨架。',
    body: '捷克語有七個格，每個格回答一個問題。學到這裡你已經用過 1、2、3、4、6、7 格，第五格（呼格）只用在叫人。',
    table: { head: ['格', '問題', '用途', '例（káva）'], rows: [['1 主格', 'kdo/co', '主詞', 'káva'], ['2 屬格', 'koho/čeho', '的、沒有', 'kávy'], ['3 與格', 'komu/čemu', '給某人', 'kávě'], ['4 賓格', 'koho/co', '受詞', 'kávu'], ['5 呼格', '—', '叫人', 'kávo!'], ['6 位格', 'o kom/čem', '在、關於', 'kávě'], ['7 工具格', 'kým/čím', '用、和', 'kávou']] },
    examples: [['Káva je dobrá.', '咖啡很好。（1）'], ['Dám si kávu.', '我要咖啡。（4）'], ['Mluvíme o kávě.', '我們在聊咖啡。（6）']],
    tip: '不用一次背完。母語者小孩也是先聽熟句子，再自然歸納出表格。',
  },
  {
    id: 'cs-g-062', stage: 4,
    title: '陽性硬變化完整表（student）',
    summary: '有生命陽性的七格。',
    body: '學會一個模板，其他同類名詞都照抄：profesor, kamarád, doktor 都是這一組。',
    table: { head: ['格', '單數', '複數'], rows: [['1', 'student', 'studenti'], ['2', 'studenta', 'studentů'], ['3', 'studentovi', 'studentům'], ['4', 'studenta', 'studenty'], ['6', 'studentovi', 'studentech'], ['7', 'studentem', 'studenty']] },
    examples: [['Znám toho studenta.', '我認識那個學生。'], ['Mluvil jsem se studentem.', '我跟那個學生說過話。'], ['Je to kniha studenta.', '這是那個學生的書。']],
    tip: '無生命陽性（dům, klíč）差別只在第四格不加 -a。',
  },
  {
    id: 'cs-g-063', stage: 4,
    title: '陰性 -a 完整表（káva）',
    summary: '最常用的陰性模板。',
    body: 'žena, škola, kniha, restaurace 幾乎都照這個走（-e 結尾的略有差異）。',
    table: { head: ['格', '單數', '複數'], rows: [['1', 'káva', 'kávy'], ['2', 'kávy', 'káv'], ['3', 'kávě', 'kávám'], ['4', 'kávu', 'kávy'], ['6', 'kávě', 'kávách'], ['7', 'kávou', 'kávami']] },
    examples: [['Dvě kávy, prosím.', '兩杯咖啡。'], ['Pět káv.', '五杯咖啡。（複數第二格）'], ['Kávu s mlékem.', '加牛奶的咖啡。']],
    tip: '菜單上寫 káva，你點的時候是 kávu，兩杯是 kávy——同一杯咖啡三種臉。',
  },
  {
    id: 'cs-g-064', stage: 4,
    title: '中性 -o 完整表（pivo）',
    summary: '中性最單純，1＝4 永遠相同。',
    body: 'auto, okno, město 都照這個模板。',
    table: { head: ['格', '單數', '複數'], rows: [['1/4', 'pivo', 'piva'], ['2', 'piva', 'piv'], ['3', 'pivu', 'pivům'], ['6', 'pivu / pivě', 'pivech'], ['7', 'pivem', 'pivy']] },
    examples: [['Jedno pivo.', '一杯啤酒。'], ['Dvě piva.', '兩杯啤酒。'], ['Pět piv.', '五杯啤酒。']],
    tip: 'Pět piv 是捷克酒吧最常聽到的一句，順便把複數第二格練起來。',
  },
  {
    id: 'cs-g-065', stage: 4,
    title: '複數主格：-i / -y / -a',
    summary: '陽性有生命 -i、陰性 -y、中性 -a。',
    body: '複數主格依性別：陽性有生命 -i（studenti）、陽性無生命與陰性 -y（domy, kávy）、中性 -a（piva）。形容詞也跟著變。',
    examples: [['Moji spolužáci jsou milí.', '我的同學們很友善。'], ['Ty knihy jsou drahé.', '那些書很貴。'], ['Ta piva jsou studená.', '那些啤酒是冰的。']],
    tip: '陽性有生命複數常有子音變化：student→studenti、Čech→Češi。',
  },
  {
    id: 'cs-g-066', stage: 4,
    title: '複數的其他格：先抓規律',
    summary: '-ům（3）、-ech/-ách（6）、-y/-ami（7）。',
    body: '複數變格比單數規律得多：第三格幾乎都是 -ům/-ám，第六格 -ech/-ách，第七格 -y/-ami。先記這三個字尾，正確率就很高。',
    examples: [['Píšu kamarádům.', '我寫給朋友們。'], ['Mluvíme o zkouškách.', '我們在聊考試。'], ['Jedu s kamarády.', '我跟朋友們一起去。']],
    tip: '聽到 -ám / -ách / -ami 就知道是複數，理解口語很有幫助。',
  },
  {
    id: 'cs-g-067', stage: 4,
    title: '動詞體（vid）：完成 vs 未完成',
    summary: '捷克語沒有時態變化，改用「體」表達完成與否。',
    body: '每個動作大多有一對動詞：未完成體（過程、習慣、反覆）與完成體（一次完成、有結果）。psát＝在寫，napsat＝寫完。這是捷克語最核心也最難的概念。',
    table: { head: ['未完成', '完成', '意思'], rows: [['psát', 'napsat', '寫'], ['dělat', 'udělat', '做'], ['číst', 'přečíst', '讀'], ['kupovat', 'koupit', '買']] },
    examples: [['Psal jsem e-mail.', '我在寫信（過程）。'], ['Napsal jsem e-mail.', '我把信寫完了。'], ['Každý den píšu.', '我每天寫。（習慣用未完成）']],
    tip: '習慣、重複、進行中 → 未完成；一次性、有結果 → 完成。',
  },
  {
    id: 'cs-g-068', stage: 4,
    title: '常見的體對照組',
    summary: '前綴或字幹變化構成一對。',
    body: '完成體通常由「未完成體＋前綴」構成（dělat→udělat），有時是字幹改變（dávat→dát）。學新動詞時把一對一起記。',
    examples: [['Učím se česky.', '我在學捷克語。（過程）'], ['Naučil jsem se sto slov.', '我學會了一百個字。（結果）'], ['Kupuju lístky online.', '我都在網路買票。（習慣）']],
    tip: '字典會標 ned.（未完成）／dok.（完成），查字典時順手看一眼。',
  },
  {
    id: 'cs-g-069', stage: 4,
    title: '未來式（一）：budu ＋ 原形',
    summary: '只能搭配未完成體動詞。',
    body: 'budu, budeš, bude, budeme, budete, budou ＋ 未完成體原形，表示未來持續或反覆的動作。',
    examples: [['Budu se učit česky.', '我會（持續）學捷克語。'], ['Budeme bydlet v Praze.', '我們會住在布拉格。'], ['Co budeš dělat zítra?', '你明天要做什麼？']],
    tip: 'být 自己的未來就是 budu（我會在），不需要再加原形。',
  },
  {
    id: 'cs-g-070', stage: 4,
    title: '未來式（二）：完成體的現在形＝未來',
    summary: 'Napíšu ti. ＝我會寫給你。',
    body: '完成體動詞沒有現在式（因為動作還沒完成），它的「現在形」表達的就是未來。這是捷克語最漂亮的邏輯之一。',
    examples: [['Napíšu ti zítra.', '我明天寫給你。'], ['Koupím to.', '我會買。'], ['Přijdu v osm.', '我八點會到。']],
    tip: '想說「我會做完」就用完成體現在形，不要再加 budu（Budu napsat 是錯的）。',
  },
  {
    id: 'cs-g-071', stage: 4,
    title: '命令式',
    summary: 'Pojď! Dej! Nedělej to!',
    body: '命令式由現在式字幹加字尾構成（-ø, -i, -ej）。對朋友用單數，對陌生人加 -te（Pojďte, Dejte）。否定命令用未完成體。',
    examples: [['Pojď sem!', '過來！'], ['Dejte mi to, prosím.', '請把那個給我。'], ['Nedělej si starosti.', '別擔心。']],
    tip: '加了 prosím，命令式就變成禮貌的請求，捷克人日常大量使用。',
  },
  {
    id: 'cs-g-072', stage: 4,
    title: '禮貌請求的層級',
    summary: '從 Dej mi 到 Mohl byste…',
    body: '禮貌程度由低到高：Dej mi…（朋友）→ Dejte mi, prosím（一般）→ Můžete mi…?（客氣）→ Mohl byste mi…?（很客氣，條件式）。',
    examples: [['Můžete mluvit pomaleji?', '您可以說慢一點嗎？'], ['Mohl byste mi pomoct?', '您能幫我一下嗎？（男生說）'], ['Mohla byste to zopakovat?', '您能再說一次嗎？（女生說）']],
    tip: '在公家機關、銀行用最高一級，成功率明顯比較高。',
  },
  {
    id: 'cs-g-073', stage: 4,
    title: '移動動詞的前綴',
    summary: 'jít 加前綴就變出十幾個動詞。',
    body: 'při-（來到）、od-（離開）、vy-（出去）、v-（進入）、pře-（穿越）。同一套前綴也可以套在 jet 上。',
    table: { head: ['動詞', '意思'], rows: [['přijít', '到達'], ['odejít', '離開'], ['vyjít', '出去'], ['přejít', '穿越'], ['přijet', '（搭車）抵達']] },
    examples: [['Přijdu v šest.', '我六點到。'], ['Odešel před hodinou.', '他一小時前離開了。'], ['Přejdi ulici.', '穿越那條街。']],
    tip: '看懂前綴，捷克語的詞彙量會突然翻倍。',
  },
  {
    id: 'cs-g-074', stage: 4,
    title: '反身被動 se',
    summary: 'Jak se to řekne? 東西怎麼被說。',
    body: '用 se 表達沒有明確主詞的動作，相當於英文的被動或 people say。這在告示、說明、日常問句裡非常常見。',
    examples: [['Jak se to řekne česky?', '這個捷克語怎麼說？'], ['Tady se nekouří.', '這裡禁菸。'], ['Kde se platí?', '在哪裡付錢？']],
    tip: '看到告示牌上的 se，多半就是「規定／慣例」的意思。',
  },
  {
    id: 'cs-g-075', stage: 4,
    title: '人稱代名詞的格變化',
    summary: 'mě / mi / tě / ti / ho / mu / jí。',
    body: '代名詞也要變格：第四格 mě, tě, ho, ji, nás, vás；第三格 mi, ti, mu, jí, nám, vám。短形式（mi, ti, ho）放在句子第二位。',
    table: { head: ['人稱', '第四格', '第三格'], rows: [['já', 'mě', 'mi'], ['ty', 'tě', 'ti'], ['on', 'ho', 'mu'], ['ona', 'ji', 'jí'], ['vy', 'vás', 'vám']] },
    examples: [['Vidím tě.', '我看到你。'], ['Dám ti to.', '我把它給你。'], ['Děkuju vám.', '謝謝您。']],
    tip: 'mě（第四格）和 mi（第三格）發音接近但不同，講錯多半仍能懂。',
  },
  {
    id: 'cs-g-076', stage: 4,
    title: '小詞的排列順序',
    summary: '助動詞 → se/si → 第三格 → 第四格。',
    body: '當一句話裡有好幾個小詞時，順序是固定的：jsem → se/si → mi/ti → to。全部擠在第二個位置。',
    examples: [['Včera jsem si to koupil.', '我昨天買了那個。'], ['Já jsem se mu omluvil.', '我向他道歉了。'], ['Dneska se mi to nelíbí.', '我今天不喜歡這個。']],
    tip: '把「jsem si to」當成一個聲音塊背下來，比理解規則快。',
  },
  {
    id: 'cs-g-077', stage: 4,
    title: '指示代名詞 ten / ta / to',
    summary: '捷克語的「那個」，口語中極常出現。',
    body: 'ten（陽）／ta（陰）／to（中）也要跟著格變化：toho, tomu, tom, tím…。口語中常用來代替冠詞的功能。',
    examples: [['Ten student je z Brna.', '那個學生來自布爾諾。'], ['Znám tu restauraci.', '我知道那家餐廳。'], ['O tom nevím.', '關於那件事我不知道。']],
    tip: '捷克人講話很愛加 ten/ta/to，聽起來像英文的 the，但語法上不是冠詞。',
  },
  {
    id: 'cs-g-078', stage: 4,
    title: '所有格代名詞的變化',
    summary: 'můj / moje / mého…',
    body: 'můj（陽）／moje（陰、中）也會依格變化：mého, mému, mém, mým。tvůj, náš, váš 同理；jeho（他的）和 její（她的）中 jeho 不變。',
    examples: [['To je můj klíč.', '這是我的鑰匙。'], ['Znáš moji kamarádku?', '你認識我朋友（女）嗎？'], ['Bydlím u svého kamaráda.', '我住在我朋友那裡。']],
    tip: '講「自己的」時捷克語用 svůj，例如 Mám svůj klíč（我有我自己的鑰匙）。',
  },
  {
    id: 'cs-g-079', stage: 4,
    title: '連接詞：že, protože, když, aby',
    summary: '把兩個句子接起來。',
    body: 'že＝that（Myslím, že…）、protože＝因為、když＝當……時、aby＝為了／希望某人做某事。捷克語從句前一律加逗號。',
    examples: [['Myslím, že to je dobré.', '我覺得那很好。'], ['Nepřišel, protože byl nemocný.', '他沒來，因為生病了。'], ['Chci, abys přišel.', '我希望你來。']],
    tip: '捷克語的逗號規則很嚴格：只要有從句就要逗號，寫作業別漏。',
  },
  {
    id: 'cs-g-080', stage: 4,
    title: '複習 4：寫一則捷克語訊息',
    summary: '把體、未來式、連接詞用在真實訊息裡。',
    body: '傳訊息給捷克同學，是驗收前 79 課最實際的方式。',
    examples: [['Ahoj, promiň, budu mít zpoždění.', '嗨，抱歉，我會遲到。'], ['Přijdu asi v půl sedmé, protože mi ujela tramvaj.', '我大概六點半到，因為電車跑掉了。'], ['Napíšu ti, až tam budu.', '我到了再傳訊息給你。']],
    tip: 'až＝「等到……時」，講未來的時間點不用 když，用 až。',
  },

  // ─────────── 第五階：條件式、比較與實戰 ───────────
  {
    id: 'cs-g-081', stage: 5,
    title: '條件式：bych, bys, by',
    summary: 'Chtěl bych… 是禮貌的萬用開場。',
    body: '條件式＝過去分詞（-l/-la）＋ bych/bys/by/bychom/byste/by。用來表達「我想要／我會」的委婉語氣，是所有正式場合的標配。',
    table: { head: ['人稱', '形式'], rows: [['já', 'bych'], ['ty', 'bys'], ['on/ona', 'by'], ['my', 'bychom'], ['vy', 'byste'], ['oni', 'by']] },
    examples: [['Chtěl bych si objednat.', '我想要點餐。（男）'], ['Chtěla bych se zeptat.', '我想請問一下。（女）'], ['Mohli byste mi pomoct?', '你們能幫我嗎？']],
    tip: '辦居留、開戶、跟教授講話，開頭用 Chtěl(a) bych 就對了。',
  },
  {
    id: 'cs-g-082', stage: 5,
    title: '四種請求說法的場合',
    summary: '知道什麼時候該用哪一級。',
    body: '朋友：Dej mi…／Můžeš…? 一般服務業：Dejte mi, prosím／Můžete…? 公家機關與教授：Mohl(a) bych…?／Mohl(a) byste…? 書信：Chtěl(a) bych Vás požádat o…',
    examples: [['Můžeš mi půjčit nabíječku?', '你可以借我充電器嗎？'], ['Můžete mi to napsat?', '您可以幫我寫下來嗎？'], ['Chtěl bych Vás požádat o potvrzení.', '我想向您申請一份證明。']],
    tip: '書信裡的 Vás/Vám 大寫是禮貌，捷克人很在意這個細節。',
  },
  {
    id: 'cs-g-083', stage: 5,
    title: 'kdyby：假設句',
    summary: '如果……的話，我就……',
    body: 'kdyby ＝ když ＋ by，用在與現實相反或不確定的假設。兩個子句都用條件式。',
    examples: [['Kdybych měl čas, jel bych do Vídně.', '如果我有時間，我就去維也納。'], ['Kdyby pršelo, zůstaneme doma.', '如果下雨，我們就待在家。'], ['Kdybys chtěl, můžeme jít spolu.', '如果你想，我們可以一起去。']],
    tip: 'kdyby 跟人稱合體：kdybych, kdybys, kdyby, kdybychom, kdybyste。',
  },
  {
    id: 'cs-g-084', stage: 5,
    title: '比較級：-ší / -ejší',
    summary: '更大、更好、更便宜。',
    body: '多數形容詞加 -ější/-ší 構成比較級。不規則的要背：dobrý→lepší（更好）、špatný→horší（更糟）、velký→větší（更大）、malý→menší（更小）。',
    examples: [['Tohle je levnější.', '這個比較便宜。'], ['Praha je větší než Brno.', '布拉格比布爾諾大。'], ['Mám lepší nápad.', '我有更好的主意。']],
    tip: '「比」用 než，語序和中文一樣直覺。',
  },
  {
    id: 'cs-g-085', stage: 5,
    title: '最高級：nej- ＋ 比較級',
    summary: '直接在比較級前面加 nej-。',
    body: '最高級規則超簡單：比較級前加 nej-。lepší→nejlepší、větší→největší、levnější→nejlevnější。',
    examples: [['To je nejlepší pivo v Praze.', '這是布拉格最好的啤酒。'], ['Kde je nejbližší bankomat?', '最近的提款機在哪？'], ['Nejlevnější jízdenka stojí 30 korun.', '最便宜的票要 30 克朗。']],
    tip: 'nejbližší（最近的）在問路時每天都會用到。',
  },
  {
    id: 'cs-g-086', stage: 5,
    title: '比較句型與同級比較',
    summary: 'než（比）、jako（像）、stejně jako（一樣）。',
    body: '比較用 než；相似用 jako；同等程度用 stejně ＋ 副詞 ＋ jako。',
    examples: [['Je to dražší než v Taipei.', '這比台北貴。'], ['Mluví česky jako rodilý mluvčí.', '他捷克語說得像母語者。'], ['Je to stejně dobré jako doma.', '這和家裡一樣好。']],
    tip: '想稱讚人就用第二句，捷克人聽了會很開心。',
  },
  {
    id: 'cs-g-087', stage: 5,
    title: '副詞的比較級',
    summary: 'dobře→líp、hodně→víc、málo→míň。',
    body: '副詞比較級不規則的最常用：líp（更好地）、víc（更多）、míň（更少）、dřív（更早）、později（更晚）。',
    examples: [['Mluvte prosím pomaleji.', '請說慢一點。'], ['Dneska se cítím líp.', '我今天感覺好一點。'], ['Přijď dřív.', '早點來。']],
    tip: 'Mluvte pomaleji 幾乎是留學第一個月的口頭禪。',
  },
  {
    id: 'cs-g-088', stage: 5,
    title: '關係代名詞 který',
    summary: '「……的那個」，要配合性別與格。',
    body: 'který/která/které 引導關係子句，性別數跟著前面的名詞，格則由子句中的角色決定。前面一定要加逗號。',
    examples: [['To je ten student, který bydlí vedle.', '那就是住隔壁的學生。'], ['Kniha, kterou čtu, je česká.', '我在讀的那本書是捷克文的。'], ['Restaurace, kde jsme byli, byla drahá.', '我們去的那家餐廳很貴。']],
    tip: '講不出來時可以用 kde/co 簡化，母語者也常這樣偷懶。',
  },
  {
    id: 'cs-g-089', stage: 5,
    title: '間接問句',
    summary: 'Nevím, kde to je.',
    body: '把疑問句放進另一個句子時，語序保持不變（捷克語不像英文要換語序），前面加逗號。',
    examples: [['Nevím, kde je nádraží.', '我不知道車站在哪。'], ['Můžete mi říct, kdy to začíná?', '您能告訴我幾點開始嗎？'], ['Zeptám se, jestli to jde.', '我會問問看行不行。']],
    tip: 'jestli＝whether／if（是否），問是非問題時用它。',
  },
  {
    id: 'cs-g-090', stage: 5,
    title: '序數與日期完整說法',
    summary: 'prvního, druhého, třetího…',
    body: '日期用序數第二格＋月份第二格。序數本身像形容詞一樣變格。',
    examples: [['Dnes je prvního září.', '今天是九月一日。'], ['Přijedu patnáctého srpna.', '我八月十五日到。'], ['Zkouška je dvacátého třetího ledna.', '考試是一月二十三日。']],
    tip: '捷克日期寫法是 1. 9. 2026（日.月.年），跟美式相反，別看錯機票。',
  },
  {
    id: 'cs-g-091', stage: 5,
    title: '時間點與時間段',
    summary: 'za hodinu（一小時後）／před hodinou（一小時前）。',
    body: 'za ＋ 第四格＝多久之後；před ＋ 第七格＝多久之前；od…do…＝從……到……。',
    examples: [['Přijdu za deset minut.', '我十分鐘後到。'], ['Přijel jsem před týdnem.', '我一週前到的。'], ['Úřad má otevřeno od osmi do čtyř.', '機關從八點開到四點。']],
    tip: '公家機關的 úřední hodiny（辦公時間）常常很短又不連續，先查再去。',
  },
  {
    id: 'cs-g-092', stage: 5,
    title: '常見動詞前綴的意思',
    summary: 'na-, vy-, za-, po-, do- 各有邏輯。',
    body: 'na-（完成一定量：napsat）、vy-（往外／徹底：vyplnit 填寫）、za-（開始／短暫：zavolat 打個電話）、po-（稍微：počkat 等一下）、do-（做到底：dodělat 做完）。',
    examples: [['Vyplňte prosím formulář.', '請填寫表格。'], ['Zavolám ti.', '我會打給你。'], ['Počkej chvíli.', '等一下。']],
    tip: 'Vyplnit formulář（填表）是辦居留最常聽到的動詞組合。',
  },
  {
    id: 'cs-g-093', stage: 5,
    title: '名詞化字尾：-ost, -ství, -ní',
    summary: '看字尾就能猜詞性和意思。',
    body: '-ost 把形容詞變成抽象名詞（rychlý→rychlost 速度），永遠是陰性；-ství 表示領域或機構（zdravotnictví 醫療體系）；-ní/-ení 常是動作名詞（bydlení 居住）。',
    examples: [['Možnost ubytování na koleji.', '住宿舍的可能性。'], ['Zdravotní pojištění je povinné.', '健康保險是強制的。'], ['Povolení k pobytu.', '居留許可。']],
    tip: '公文全是這種字，認得字尾就能猜出七成意思。',
  },
  {
    id: 'cs-g-094', stage: 5,
    title: '書面語 vs 口語',
    summary: 'spisovná čeština vs obecná čeština。',
    body: '捷克語有明顯的雙層：書面／正式的標準捷克語，和波希米亞地區的日常口語。兩者差在字尾：-ý→-ej（dobrý→dobrej）、-é→-ý（dobré→dobrý）、動詞 -ji→-ju。',
    examples: [['Standard: To je dobré pivo.', '（書面）這啤酒不錯。'], ['Obecná: To je dobrý pivo.', '（口語）這啤酒不錯。'], ['Standard: Studuji. / Obecná: Studuju.', '我在讀書。']],
    tip: '聽力聽的是口語，寫作業寫的是書面語——兩套都要認得，但只要會說一套。',
  },
  {
    id: 'cs-g-095', stage: 5,
    title: '口語常見縮音',
    summary: '母語者實際講話的樣子。',
    body: 'jsem→sem、jsi→seš、jestli→jesli、nějaký→ňákej、dneska（＝dnes）。聽不懂常常不是單字不會，而是縮音沒認出來。',
    examples: [['Seš tady?', '你在這嗎？（＝Jsi tady?）'], ['Sem se ztratil.', '我迷路了。（＝Jsem se ztratil）'], ['Dneska mám volno.', '我今天有空。']],
    tip: '自己講可以照標準語，但耳朵一定要習慣這些縮音。',
  },
  {
    id: 'cs-g-096', stage: 5,
    title: '正式電子郵件格式',
    summary: '給教授與行政人員的固定套路。',
    body: '開頭 Dobrý den, / Vážený pane profesore,；結尾 S pozdravem ＋ 你的名字。稱呼裡的職稱要用第五格（呼格）：pane profesore, paní doktorko。',
    examples: [['Vážená paní profesorko,', '敬愛的教授（女）：'], ['Chtěl bych se zeptat na termín zkoušky.', '我想請問考試日期。'], ['S pozdravem, Josh An', '敬祝安好，Josh An']],
    tip: '捷克學術界很重視稱謂，把職稱寫對比信寫得漂亮更重要。',
  },
  {
    id: 'cs-g-097', stage: 5,
    title: '公家機關實戰句型',
    summary: '外國人警局、學校教務處通用。',
    body: '準備好三句：說明來意、詢問文件、確認下一步。多數承辦人不講英文，但只要你開口講捷克語，態度會軟很多。',
    examples: [['Dobrý den, jsem student a potřebuji se přihlásit k pobytu.', '您好，我是學生，需要辦居留登記。'], ['Jaké doklady potřebujete?', '您需要哪些文件？'], ['Co mám udělat dál?', '我接下來要做什麼？']],
    tip: '所有文件都多印一份，捷克機關對紙本的執著超乎想像。',
  },
  {
    id: 'cs-g-098', stage: 5,
    title: '台灣人最常犯的六個錯',
    summary: '一次修正，等於少走半年冤枉路。',
    body: '① 長音不夠長 ② 忘記性別（rád/ráda）③ 用 neznám 代替 nevím ④ Děkuju vás（應為 vám）⑤ 忘記雙重否定 ⑥ 該用 jet 卻用 jít。',
    examples: [['✗ Neznám. → ✓ Nevím.', '我不知道。'], ['✗ Děkuju vás. → ✓ Děkuju vám.', '謝謝您。'], ['✗ Nikdy jím maso. → ✓ Nikdy nejím maso.', '我從不吃肉。']],
    tip: '把這六條寫在便條紙貼在書桌上，一個月內就能改掉。',
  },
  {
    id: 'cs-g-099', stage: 5,
    title: '把 100 天串起來：三分鐘自我介紹',
    summary: '從姓名、來歷到未來計畫。',
    body: '用現在式講身分、過去式講經歷、未來式與條件式講計畫——這就是完整的 A2 口說。',
    examples: [['Jmenuji se Josh a jsem z Tchaj-wanu.', '我叫 Josh，來自台灣。'], ['Studoval jsem informatiku a teď jsem tady na výměnném pobytu.', '我讀資訊，現在在這裡交換。'], ['Rád bych se naučil líp česky a procestoval Evropu.', '我想把捷克語學得更好，並旅行歐洲。']],
    tip: '把這段練到滾瓜爛熟，開學第一週會用上至少十次。',
  },
  {
    id: 'cs-g-100', stage: 5,
    title: '結業：接下來怎麼繼續',
    summary: '100 天之後的自學路線。',
    body: '你已經有 A2 的骨架。接下來靠三件事持續：每天讀一則捷克新聞標題、每週跟一個捷克人講十分鐘、把不會的字丟進單字本。語言不是學完的，是用出來的。',
    examples: [['Učím se česky každý den.', '我每天學捷克語。'], ['Ještě dělám chyby, ale nevadí.', '我還會犯錯，但沒關係。'], ['Bez chyb se to naučit nedá.', '不犯錯是學不會的。']],
    tip: '捷克人對願意講他們語言的外國人非常寬容——錯著錯著就會了。',
  },
];
