export const PALETTES = {
  dragon: {
    K: '#331515',
    k: '#8d6e63',
    W: '#ffffff',
    G: '#f5f5f5',
    R: '#8b0000',
    O: '#ff9a76',
    B: '#000000',
    Z: '#81d4fa',
    z: '#ffffff',
  },
  env: {
    D: '#3e2723',
    L: '#5d4037',
    T: '#795548',
    S: '#1a0f0d',
    r: '#a52a2a',
    b: '#2c3e50',
    y: '#f1c40f',
    g: '#27ae60',
    w: '#ecf0f1',
    p: '#8e44ad',
    o: '#e67e22',
    W: '#ffffff',
    coffee: '#3e2723',
    paper: '#fdf5e6',
    '-': '#d1d5db',
    R: '#c0392b',
    C: '#7dd3fc',
    H: '#bae6fd',
    Y: '#fde047',
    U: '#0284c7',
    V: '#38bdf8',
  },
};

export const SPRITES = {
  dragonSit: [
    '......R...R......',
    '......R...R......',
    '....kkKKKKKkk....',
    '...kKWWWWWWWKk...',
    '..kKWWWWWWWWWKk..',
    '.kKWWWWWWWWWWWKk.',
    '.KWWKWWWWWWWKWWK.',
    '.KWWKWWKKKWWKWWK.',
    'KKWOOWWWWWOWOWKK.',
    'KKWOOWWWWWOWOWKK.',
    '.KWWWWWWWWWWWK...',
    '.KGGGGGGGGGGGK...',
    '..KKKKKKKKKKK....',
    '.....K...K.......',
  ].join('\n'),
  dragonRun1: [
    '......R...R......',
    '....kkKKKKKkk....',
    '..kKWWWWWWWWWKk..',
    '.kKWWWWWWWWWWWKk.',
    '.KWWKWWWWWWWKWWK.',
    '.KWWKWWKKKWWKWWK.',
    'KKWOOWWWWWOWOWKK.',
    '.KWWWWWWWWWWWK...',
    '.KGGGGGGGGGGGK...',
    '..KKKKKKKKKKK....',
    '...K.......K.....',
  ].join('\n'),
  dragonRun2: [
    '......R...R......',
    '....kkKKKKKkk....',
    '..kKWWWWWWWWWKk..',
    '.kKWWWWWWWWWWWKk.',
    '.KWWKWWWWWWWKWWK.',
    '.KWWKWWKKKWWKWWK.',
    '.KWOOWWWWWOWOWK..',
    '.KWWWWWWWWWWWK...',
    '.KGGGGGGGGGGGK...',
    '..KKKKKKKKKKK....',
    '.....K...K.......',
  ].join('\n'),
  dragonSleep: [
    '........R.....R.......',
    '......RRR...RRR.......',
    '........R.....R.......',
    '.....KKKKKKKKKKKKK....',
    '...KKWWWWWWWWWWWWWKK..',
    '..KWWWWWWWWWWWWWWWWWK.',
    '..KWWWWKKKWWWWWKKKWWK.',
    '.KWWWWWWWWWWWWWWWWWZZK',
    '.KWWWOOOOWWKWWOOOOZWZK',
    'KKWWWOOOOWWWWWWOOOOZZK',
    'KWWWWWWWWWWWWWWWWWWKK.',
    '.KKKKKKKKKKKKKKKKKKK..',
  ].join('\n'),
  redBook: [
    '.......S.......',
    '.WWWWWWWWWWWWW.',
    'WwwwwwwSwwwwwwW',
    'W--w--wS--w--wW',
    'WwwwwwwSwwwwwwW',
    'W--w--wS--w--wW',
    'RRRRRRRRRRRRRRR',
    '.SSSSSSSSSSSSS.',
  ].join('\n'),
  coffeeCupDetailed: [
    '...........',
    '..WWWWW....',
    '.WcccccW...',
    'WcccccccWW.',
    'WcccccccW.W',
    '.WWWWWWW.W.',
    '..WWWWW.W..',
    '...........',
  ].join('\n'),
  zzz: [
    '.........zzzzz',
    '............z.',
    '...........z..',
    '..........z...',
    '.........zzzzz',
    '..............',
    '.....zzzz.....',
    '.......z......',
    '......z.......',
    '.....zzzz.....',
    '..............',
    '..zzz.........',
    '....z.........',
    '...z..........',
    '..zzz.........',
  ].join('\n'),
};
