/**
 * 龍龍旅行社：年底「捷克 → 奧地利 → 瑞典」旅行的參考資料。
 *
 * 2026-09 查證。票價、時刻、營業日每年都會變：
 * - `verify: true` 的項目畫面上會標「出發前再確認」
 * - 有日期窗口的活動寫在 TRIP_EVENTS，行程表會拿出發日自動比對有沒有開
 * 新增資料時沒把握的一律標 verify，寧可多標。
 *
 * 照片與座標（tools/trip/build_places.mjs 產生 tripPlaces.json）：
 * - wiki：'語言:條目名'，取條目的授權照片與座標
 * - geo：OpenStreetMap 查詢字串，座標以它為準（餐廳、車站這類條目座標不準的地方）
 * - pin: false：全市通用或沒有固定地點（交通票、節慶、菜色），不上地圖
 * - imageNote: '示意'：照片不是那個地方本身（例如用菜色照代表餐廳）
 * - to：交通項目的目的地城市（座標是出發地點）
 */

/**
 * keywords 用來從行程表的文字判斷那天在哪個城市（一律小寫）
 * wikivoyage：英文 Wikivoyage 的頁面，第一頁是介紹頁的城市連結；後面可以加一日遊的小鎮
 *   （大城市的分區頁 tools/trip/fetch_wikivoyage.mjs 會自己找）
 */
export const TRIP_CITIES = [
  { key: 'prague', center: [50.0875, 14.4213], flag: '🇨🇿', name: '布拉格', local: 'Praha', keywords: ['布拉格', 'praha', 'prague'], wikivoyage: ['Prague', 'Kutná Hora'] },
  { key: 'krumlov', center: [48.8127, 14.3175], flag: '🇨🇿', name: '庫倫洛夫', local: 'Český Krumlov', keywords: ['庫倫洛夫', 'ck 小鎮', 'ck小鎮', 'krumlov'], wikivoyage: ['Český Krumlov'] },
  { key: 'vienna', center: [48.2082, 16.3738], flag: '🇦🇹', name: '維也納', local: 'Wien', keywords: ['維也納', 'wien', 'vienna'], wikivoyage: ['Vienna'] },
  { key: 'salzburg', center: [47.8009, 13.0448], flag: '🇦🇹', name: '薩爾斯堡', local: 'Salzburg', keywords: ['薩爾斯堡', 'salzburg'], wikivoyage: ['Salzburg', 'Oberndorf bei Salzburg and Laufen (Bavaria)'] },
  { key: 'hallstatt', center: [47.5622, 13.6493], flag: '🇦🇹', name: '哈修塔特', local: 'Hallstatt', keywords: ['哈修塔特', 'hallstatt'], wikivoyage: ['Hallstatt'] },
  { key: 'stockholm', center: [59.3293, 18.0686], flag: '🇸🇪', name: '斯德哥爾摩', local: 'Stockholm', keywords: ['斯德哥爾摩', 'stockholm'], wikivoyage: ['Stockholm'] },
  {
    key: 'lapland',
    // 阿比斯庫和基律納相距約 90 公里，中心點取在兩地之間只為了全程地圖好看
    center: [68.12, 19.4],
    flag: '🇸🇪',
    name: '阿比斯庫・基律納',
    local: 'Abisko / Kiruna',
    keywords: ['阿比斯庫', '基律納', 'abisko', 'kiruna', '北極圈', '極光'],
    // 冰旅館在 Jukkasjärvi，Wikivoyage 另外一頁
    wikivoyage: ['Abisko and Björkliden', 'Kiruna', 'Jukkasjärvi'],
  },
  { key: 'narvik', center: [68.4385, 17.4272], flag: '🇳🇴', name: '納爾維克', local: 'Narvik', keywords: ['納爾維克', 'narvik'], wikivoyage: ['Narvik'] },
];

/** 只寫到國家的日子（例如「🇨🇿 → 🇦🇹 奧地利」）也要能畫進路線摘要 */
export const TRIP_COUNTRIES = [
  { key: 'cz', flag: '🇨🇿', name: '捷克', keywords: ['捷克'] },
  { key: 'at', flag: '🇦🇹', name: '奧地利', keywords: ['奧地利', 'austria'] },
  { key: 'se', flag: '🇸🇪', name: '瑞典', keywords: ['瑞典', 'sweden'] },
  { key: 'no', flag: '🇳🇴', name: '挪威', keywords: ['挪威', 'norway'] },
];

export const TRIP_CATEGORIES = [
  { key: 'move', label: '交通', emoji: '🚆' },
  { key: 'fun', label: '景點', emoji: '🎡' },
  { key: 'food', label: '美食', emoji: '🍽️' },
  { key: 'stay', label: '住宿', emoji: '🏨' },
];

/** 交通頁依「哪一段路」分組，比依城市分好找 */
export const TRIP_LEGS = [
  { key: 'arrive', title: '抵達布拉格', hint: '機場 → 市區' },
  { key: 'cz-at', title: '布拉格 → 奧地利', hint: '火車、巴士或門到門小巴' },
  { key: 'at', title: '奧地利城市之間', hint: '維也納、薩爾斯堡、哈修塔特' },
  { key: 'at-se', title: '奧地利 → 瑞典', hint: '飛斯德哥爾摩' },
  { key: 'north', title: '斯德哥爾摩 → 北極圈', hint: '夜車或飛機' },
  { key: 'lapland', title: '北極圈當地移動', hint: '阿比斯庫、基律納、納爾維克' },
  { key: 'home', title: '回程', hint: '從北極圈飛出去' },
  { key: 'city', title: '市區交通票', hint: '每個城市怎麼買票' },
];

/** 城市之間怎麼移動、大概多久；地圖用來標示跨城市的那一段（minutes 用於加總） */
export const TRIP_CITY_LINKS = [
  { a: 'prague', b: 'vienna', icon: '🚆', text: '火車約 4 小時 15 分', minutes: 255 },
  { a: 'prague', b: 'salzburg', icon: '🚆', text: '火車約 5.5 小時（林茨轉車）', minutes: 330 },
  { a: 'prague', b: 'krumlov', icon: '🚌', text: '巴士約 3 小時', minutes: 180 },
  { a: 'krumlov', b: 'hallstatt', icon: '🚐', text: '門到門小巴約 3 小時', minutes: 180 },
  { a: 'vienna', b: 'salzburg', icon: '🚆', text: '火車約 2 小時 30 分', minutes: 150 },
  { a: 'salzburg', b: 'hallstatt', icon: '🚌', text: '公車或火車＋渡輪約 2–2.5 小時', minutes: 135 },
  { a: 'hallstatt', b: 'vienna', icon: '🚆', text: '渡輪＋火車約 4 小時', minutes: 240 },
  { a: 'vienna', b: 'stockholm', icon: '✈️', text: '直飛約 2 小時 20 分（不含機場來回）', minutes: 140 },
  { a: 'stockholm', b: 'lapland', icon: '🚆', text: '夜車約 17 小時，或飛基律納約 1.5 小時', minutes: 1020 },
  { a: 'lapland', b: 'narvik', icon: '🚆', text: '景觀火車約 1.5–2 小時', minutes: 105 },
];

/**
 * 有營業期間的活動。cities 對應 TRIP_CITIES；keywords 用於不屬於單一城市的事（夜車）。
 * weekdays：只在這些星期幾開（0 = 週日）。end 為 null 代表之後都有。
 * openText／closedText：預設是「這天有開」「這天沒開（期間）」，不適合的才另外寫。
 */
export const TRIP_EVENTS = [
  {
    id: 'prague-market',
    cities: ['prague'],
    icon: '🎄',
    name: '布拉格聖誕市集',
    start: '2026-11-28',
    end: '2027-01-06',
    note: '老城廣場、瓦茨拉夫廣場，每天 10:00–22:00',
  },
  {
    id: 'vienna-rathaus',
    cities: ['vienna'],
    icon: '🎄',
    name: '維也納市政廳聖誕市集',
    start: '2026-11-13',
    end: '2026-12-26',
    note: '12/24 只開到 18:30',
  },
  {
    id: 'vienna-schoenbrunn',
    cities: ['vienna'],
    icon: '🎄',
    name: '美泉宮聖誕新年市集',
    start: '2026-11-06',
    end: '2027-01-06',
  },
  {
    id: 'salzburg-market',
    cities: ['salzburg'],
    icon: '🎄',
    name: '薩爾斯堡聖誕市集',
    start: '2026-11-19',
    end: '2027-01-01',
    note: '12/24 只開到 15:00',
  },
  {
    id: 'hallstatt-market',
    cities: ['hallstatt'],
    icon: '🎄',
    name: '哈修塔特聖誕市集（一年只開一天）',
    start: '2026-12-08',
    end: '2026-12-08',
  },
  {
    id: 'stockholm-gamlastan',
    cities: ['stockholm'],
    icon: '🎄',
    name: '斯德哥爾摩老城聖誕市集',
    start: '2026-11-21',
    end: '2026-12-23',
    note: '依往年推估，官方公布後再確認',
    verify: true,
  },
  {
    id: 'stockholm-skansen',
    cities: ['stockholm'],
    icon: '🎄',
    name: 'Skansen 聖誕市集',
    start: '2026-11-27',
    end: '2026-12-20',
    weekdays: [5, 6, 0],
    note: '只有週五～週日',
  },
  {
    id: 'vienna-prater',
    cities: ['vienna'],
    icon: '🎡',
    name: '普拉特摩天輪冬季市集',
    start: '2026-11-20',
    end: '2027-01-06',
  },
  {
    id: 'hellbrunn-advent',
    cities: ['salzburg'],
    icon: '🎄',
    name: '海布倫宮聖誕市集',
    start: '2026-11-19',
    end: '2026-12-24',
    weekdays: [0, 2, 3, 4, 5, 6],
    note: '週一休息；12/24 只到 14:00',
  },
  {
    id: 'night-train-direct',
    keywords: ['夜車'],
    icon: '🚆',
    name: 'SJ 夜車直達北極圈',
    start: '2026-12-13',
    end: null,
    openText: '直達，不用在 Boden 轉車',
    closedText: '12/13 前夜車只開到 Boden，要轉白天的區間車',
  },
  {
    id: 'aurora-sky-station',
    cities: ['lapland'],
    icon: '🌌',
    name: '極光站夜間行程',
    start: '2026-10-19',
    end: '2027-03-27',
    openText: '這天有營業',
  },
  {
    id: 'icehotel',
    cities: ['lapland'],
    icon: '🧊',
    name: 'ICEHOTEL 37 冰旅館',
    start: '2026-12-11',
    end: null,
    openText: '已開幕',
    closedText: '12/11 才開幕，之前只有全年開的 ICEHOTEL 365',
  },
];

/** 'MM-DD' → 那天要注意的事 */
export const TRIP_HOLIDAYS = {
  '12-24': '平安夜：歐洲的「除夕」，商店餐廳中午過後陸續關門，交通改假日班次',
  '12-25': '聖誕節：大部分商店、景點休息',
  '12-26': '聖誕節第二天：捷克、奧地利、瑞典都放假',
  '12-31': '跨年夜：餐廳多半要訂位，景點提早關',
  '01-01': '元旦：商店、景點大多休息',
};

export const DEFAULT_TRIP_TITLE = '捷克—奧地利—瑞典（和安一起）';

/** 照 Notion「捷克—德國—瑞典(和安一起)」最新版（Day 3 已改成奧地利） */
export const DEFAULT_TRIP_DAYS = [
  { id: 'd1', place: '🇨🇿 布拉格', plan: '抵達、老城區、聖誕市集' },
  { id: 'd2', place: '🇨🇿 布拉格', plan: '布拉格城堡、查理大橋' },
  { id: 'd3', place: '🇨🇿 → 🇦🇹 奧地利', plan: '' },
  { id: 'd4', place: '', plan: '' },
  { id: 'd5', place: '', plan: '' },
  { id: 'd6', place: '', plan: '飛往瑞典' },
  { id: 'd7', place: '', plan: '火車' },
  { id: 'd8', place: '', plan: '瑞典' },
  { id: 'd9', place: '', plan: '瑞典' },
  { id: 'd10', place: '', plan: '回程' },
  { id: 'd11', place: '', plan: '' },
  { id: 'd12', place: '', plan: '' },
  { id: 'd13', place: '', plan: '' },
];

/** 還沒排的天數的走法建議；from 是要套用到的起始 Day（1 起算） */
export const ROUTE_SUGGESTIONS = [
  {
    id: 'at-vienna',
    group: '奧地利 3 天',
    from: 3,
    title: 'A. 維也納慢慢玩',
    summary: '只換一次城市，冬天最輕鬆，晚上逛市集最方便。',
    pros: '移動最少、晚上活動多',
    cons: '看不到湖區雪景',
    days: [
      { place: '🇨🇿 布拉格 → 🇦🇹 維也納', plan: '火車約 4 小時，晚上逛市政廳聖誕市集' },
      { place: '🇦🇹 維也納', plan: '美泉宮＋市集、聖史蒂芬主教座堂、咖啡館' },
      { place: '🇦🇹 維也納', plan: '美景宮看《吻》、霍夫堡，晚上歌劇院站票' },
    ],
  },
  {
    id: 'at-lakes',
    group: '奧地利 3 天',
    from: 3,
    title: 'B. CK 小鎮＋哈修塔特',
    summary: '最有童話感的走法，但每天都在移動。',
    pros: '兩個最美的小鎮一次看完',
    cons: '移動時間長，哈修塔特住宿貴又少',
    days: [
      { place: '🇨🇿 布拉格 → 庫倫洛夫', plan: '巴士約 3 小時，下午逛 CK 小鎮、住城裡' },
      { place: '庫倫洛夫 → 🇦🇹 哈修塔特', plan: '門到門小巴約 3 小時，傍晚湖邊散步' },
      { place: '🇦🇹 哈修塔特 → 維也納', plan: '渡輪＋火車約 4 小時，晚上逛市政廳聖誕市集' },
    ],
  },
  {
    id: 'at-salzburg',
    group: '奧地利 3 天',
    from: 3,
    title: 'C. 薩爾斯堡＋湖區一日遊',
    summary: '住薩爾斯堡當據點，市集和雪山湖景都有。',
    pros: '住宿比較便宜、行程有彈性',
    cons: '第一天坐車最久',
    days: [
      { place: '🇨🇿 布拉格 → 🇦🇹 薩爾斯堡', plan: '火車在林茨轉車約 5.5 小時，晚上逛主教座堂廣場市集' },
      { place: '🇦🇹 哈修塔特（一日遊）', plan: '公車或火車＋渡輪約 2–2.5 小時，傍晚回薩爾斯堡' },
      { place: '🇦🇹 薩爾斯堡 → 維也納', plan: '上午要塞看雪山，火車約 2.5 小時到維也納，晚上逛市集' },
    ],
  },
  {
    id: 'se-train',
    group: '瑞典 5 天',
    from: 6,
    title: '夜車北上看極光（照原本 Day 7 坐火車）',
    summary: '夜車同時是交通和一晚住宿，醒來就在北極圈。',
    pros: '省一晚住宿，夜車本身就是體驗',
    cons: '12/13 前要在 Boden 轉車',
    days: [
      { place: '🇦🇹 維也納 → 🇸🇪 斯德哥爾摩', plan: '直飛約 2 小時 20 分，下午逛老城 Gamla Stan 聖誕市集' },
      { place: '🇸🇪 斯德哥爾摩', plan: '瓦薩沉船博物館、fika，傍晚搭 SJ 夜車北上' },
      { place: '🇸🇪 阿比斯庫', plan: '中午前後到站，晚上極光站 Aurora Sky Station' },
      { place: '🇸🇪 阿比斯庫・基律納', plan: '狗拉雪橇、冰旅館 ICEHOTEL' },
      { place: '🇸🇪 基律納 → 回程', plan: '基律納飛斯德哥爾摩約 1.5 小時，轉機回程' },
    ],
  },
  {
    id: 'se-fly',
    group: '瑞典 5 天',
    from: 6,
    title: '直飛基律納，極光多看一晚',
    summary: '不坐 17 小時的車，換一晚在北極圈追極光。',
    pros: '追極光的晚上從 2 晚變 3 晚',
    cons: '多一段機票錢，少了夜車體驗',
    days: [
      { place: '🇦🇹 維也納 → 🇸🇪 斯德哥爾摩', plan: '直飛約 2 小時 20 分，下午逛老城聖誕市集，晚上吃 julbord' },
      { place: '🇸🇪 斯德哥爾摩 → 基律納', plan: '早上飛基律納約 1.5 小時，接駁到阿比斯庫，晚上極光站' },
      { place: '🇸🇪 阿比斯庫', plan: '峽谷步道、狗拉雪橇，晚上再追一次極光' },
      { place: '🇸🇪 基律納', plan: '冰旅館 ICEHOTEL、薩米文化和馴鹿' },
      { place: '🇸🇪 基律納 → 回程', plan: '早班機飛斯德哥爾摩轉機回程' },
    ],
  },
];

/** 行程表側欄「出發前必看」 */
export const TRIP_NOTICES = [
  {
    icon: '🚆',
    title: '夜車 12/13 才恢復直達',
    text: '2026 年 4 月起，斯德哥爾摩往納爾維克的夜車只開到 Boden，要轉白天的區間車；12/13 換新時刻表後，SJ 恢復每天直達，臥鋪不用換車。坐夜車那天在 12/13 之前的話，要把轉車時間算進去。',
  },
  {
    icon: '🎄',
    title: '各地聖誕市集收攤日不一樣',
    text: '布拉格開到 1/6；維也納市政廳 12/26 收、美泉宮到 1/6；薩爾斯堡到 1/1；斯德哥爾摩老城 12/23 就收；哈修塔特只有 12/8 一天。',
  },
  {
    icon: '🔒',
    title: '12/24–26 很多地方休息',
    text: '平安夜中午過後商店和餐廳陸續關門，大眾運輸改假日班次。這幾天的餐廳、景點要先查好、先訂位。',
  },
  {
    icon: '🌑',
    title: '北極圈 12 月是極夜',
    text: '12 月中阿比斯庫、基律納整天沒有日出，只有中午前後幾小時藍色的天光。氣溫常在 -10°C 上下，寒流會到 -25°C 以下。看極光靠的是晴天，行程多留一晚比較保險。',
  },
  {
    icon: '🛂',
    title: '入境：EES 已上路，ETIAS 可能延後',
    text: '申根區邊境已經改用 EES 拍照、按指紋，第一次入境排隊會比較久。ETIAS 原訂 2026 年底上路，但 2026 年 7 月官方拿掉了日期，可能延到 2027；從台灣直接飛來的人出發前再查一次。',
  },
  {
    icon: '💳',
    title: '三種貨幣',
    text: '捷克克朗 CZK、歐元 EUR、瑞典克朗 SEK（去納爾維克還有挪威克朗 NOK）。瑞典幾乎全面刷卡；捷克的小攤子偶爾只收現金。',
  },
];

const TRANSPORT = [
  // ── 抵達布拉格 ──
  {
    id: 'mv-prg-59',
    to: 'prague',
    wiki: 'en:Trolleybuses in Prague',
    geo: 'Letiště Václava Havla Praha',
    leg: 'arrive',
    city: 'prague',
    name: '59 號無軌電車 → 地鐵 A 線',
    local: 'Trolejbus 59 → Metro A',
    desc: '機場出來搭 59 號（2024 年取代原本的 119 公車）到 Nádraží Veleslavín，轉地鐵 A 線進市中心。一張 90 分鐘票全程通用，最便宜。',
    cost: '90 分鐘票 46 Kč（app）／50 Kč（紙本）',
    time: '到老城約 40 分鐘',
    verify: true,
    map: 'Nádraží Veleslavín',
    links: [{ label: 'PID 票價', url: 'https://pid.cz/en/tickets/' }],
  },
  {
    id: 'mv-prg-ae',
    to: 'prague',
    wiki: 'en:Václav Havel Airport Prague',
    leg: 'arrive',
    city: 'prague',
    name: 'AE 機場快線 → 中央車站',
    local: 'Airport Express',
    desc: '直達布拉格中央車站（Praha hlavní nádraží），行李多、或住瓦茨拉夫廣場附近最方便。2026 年起票價從 100 漲到 200 Kč，可以直接跟司機刷卡買票。',
    tips: ['24 小時、72 小時票不能搭 AE'],
    cost: '200 Kč／人',
    time: '約 35 分鐘',
    verify: true,
    map: 'Praha hlavní nádraží',
    links: [{ label: '機場官網', url: 'https://www.prg.aero/airport-express-ae' }],
  },
  // ── 布拉格 → 奧地利 ──
  {
    id: 'mv-prg-vie',
    to: 'vienna',
    wiki: 'en:Railjet',
    geo: 'Praha hlavní nádraží',
    leg: 'cz-at',
    city: 'prague',
    name: '火車：布拉格 → 維也納',
    local: 'Praha hl.n. → Wien Hbf',
    desc: 'ČD／ÖBB 的 Railjet 一天約 9 班，RegioJet 約 4 班，中央車站直達維也納中央車站，是這趟最省事的一段。',
    tips: ['RegioJet 比較便宜但班次少；Railjet 車廂比較新', '越早買越便宜，當天買可能要 €50 以上'],
    cost: '提早買約 €15–40',
    time: '約 4 小時 15 分',
    verify: true,
    links: [
      { label: 'ČD', url: 'https://www.cd.cz/en/' },
      { label: 'RegioJet', url: 'https://regiojet.com/' },
    ],
  },
  {
    id: 'mv-prg-szg',
    to: 'salzburg',
    wiki: 'en:Salzburg Hauptbahnhof',
    geo: 'Praha hlavní nádraží',
    imageNote: '示意',
    leg: 'cz-at',
    city: 'prague',
    name: '火車：布拉格 → 薩爾斯堡',
    local: 'via Linz',
    desc: '沒有直達車，通常在林茨（Linz）轉一次車。',
    cost: '提早買約 €20 起',
    time: '約 5.5 小時',
    verify: true,
    links: [{ label: 'ÖBB', url: 'https://www.oebb.at/en/' }],
  },
  {
    id: 'mv-prg-ck',
    to: 'krumlov',
    wiki: 'en:Český Krumlov',
    pin: false,
    leg: 'cz-at',
    city: 'prague',
    imageNote: '示意',
    name: '巴士：布拉格 → 庫倫洛夫',
    local: 'Praha → Český Krumlov',
    desc: 'RegioJet、FlixBus 都有直達巴士，比火車少轉一次車（火車要在 České Budějovice 轉）。',
    time: '約 3 小時',
    verify: true,
    links: [{ label: 'RegioJet', url: 'https://regiojet.com/' }],
  },
  {
    id: 'mv-ck-shuttle',
    to: 'hallstatt',
    wiki: 'en:Český Krumlov',
    imageNote: '示意',
    leg: 'cz-at',
    city: 'krumlov',
    name: '門到門小巴：CK 小鎮 → 哈修塔特／薩爾斯堡',
    local: 'CK Shuttle',
    desc: '從布拉格或庫倫洛夫的旅館直接載到哈修塔特、薩爾斯堡、維也納，中間不用自己轉車，很適合「布拉格 → CK 小鎮 → 奧地利」的走法。',
    tips: ['依路線和人數報價，旺季要提早預約'],
    time: '庫倫洛夫 → 哈修塔特約 3 小時',
    verify: true,
    links: [{ label: 'CK Shuttle', url: 'https://www.ckshuttle.cz/' }],
  },
  // ── 奧地利城市之間 ──
  {
    id: 'mv-vie-szg',
    to: 'salzburg',
    wiki: 'en:Wien Hauptbahnhof',
    geo: 'Wien Hauptbahnhof',
    leg: 'at',
    city: 'vienna',
    name: '火車：維也納 ↔ 薩爾斯堡',
    local: 'ÖBB Railjet / WESTbahn',
    desc: '兩家公司都有開、班次很多，直達不用轉車。ÖBB 的 Sparschiene 特價票越早買越便宜。',
    time: '約 2 小時 30 分',
    verify: true,
    links: [{ label: 'ÖBB', url: 'https://www.oebb.at/en/' }],
  },
  {
    id: 'mv-szg-hal',
    to: 'hallstatt',
    wiki: 'en:Hallstätter See',
    geo: 'Salzburg Hauptbahnhof',
    imageNote: '示意',
    leg: 'at',
    city: 'salzburg',
    name: '薩爾斯堡 → 哈修塔特',
    local: 'Bus 150 / 火車＋渡輪',
    desc: '公車 150 到 Bad Ischl 再轉 542／543；或搭火車到 Hallstatt 站，再坐渡輪過湖到小鎮。冬天班次少，出發前先查好回程末班車。',
    time: '約 2–2.5 小時',
    verify: true,
    links: [{ label: 'ÖBB', url: 'https://www.oebb.at/en/' }],
  },
  {
    id: 'mv-hal-vie',
    to: 'vienna',
    wiki: 'en:Hallstätter See',
    leg: 'at',
    city: 'hallstatt',
    geo: 'Hallstatt Bahnhof',
    imageNote: '示意',
    name: '哈修塔特 → 維也納',
    local: 'Schiff + Zug',
    desc: '先坐渡輪到對岸的 Hallstatt 火車站，在 Attnang-Puchheim 轉 Railjet 到維也納。',
    time: '約 4 小時',
    verify: true,
    links: [{ label: 'ÖBB', url: 'https://www.oebb.at/en/' }],
  },
  {
    id: 'mv-vie-airport',
    to: 'vienna',
    wiki: 'en:Vienna International Airport',
    leg: 'at',
    city: 'vienna',
    name: '維也納市區 ↔ 機場',
    local: 'ÖBB / S7 / CAT',
    desc: 'ÖBB 火車或 S7 通勤火車最便宜，從中央車站到機場約 15–25 分鐘；CAT 機場快線直達 Wien Mitte 只要 16 分鐘，但票價貴好幾倍。',
    time: '約 15–25 分鐘',
    verify: true,
  },
  // ── 奧地利 → 瑞典 ──
  {
    id: 'mv-vie-arn',
    to: 'stockholm',
    wiki: 'en:Austrian Airlines',
    geo: 'Flughafen Wien-Schwechat',
    leg: 'at-se',
    city: 'vienna',
    name: '飛機：維也納 → 斯德哥爾摩',
    local: 'VIE → ARN',
    desc: 'Austrian Airlines 和 Ryanair 有直飛 Arlanda 機場；SAS、Norwegian 多半要在哥本哈根轉機。',
    tips: ['Ryanair 的行李、選位都另外收費，比價時要算進去'],
    time: '飛行約 2 小時 20 分',
    verify: true,
    links: [
      { label: 'Austrian', url: 'https://www.austrian.com/' },
      { label: 'Ryanair', url: 'https://www.ryanair.com/' },
    ],
  },
  {
    id: 'mv-arn-city',
    to: 'stockholm',
    wiki: 'en:Arlanda Express',
    geo: 'Stockholm Arlanda Airport',
    leg: 'at-se',
    city: 'stockholm',
    name: 'Arlanda 機場 → 斯德哥爾摩市區',
    local: 'Arlanda Express / Pendeltåg',
    desc: 'Arlanda Express 18 分鐘到中央車站，單程約 340 SEK（網路提早買、兩人同行有優惠）；通勤火車 pendeltåg 約 40 分鐘，SL 票加機場站費，便宜不少。',
    time: '18–40 分鐘',
    verify: true,
    links: [
      { label: 'Arlanda Express', url: 'https://www.arlandaexpress.com/' },
      { label: 'SL', url: 'https://sl.se/en' },
    ],
  },
  // ── 斯德哥爾摩 → 北極圈 ──
  {
    id: 'mv-night-train',
    to: 'lapland',
    wiki: 'en:Iron Ore Line',
    geo: 'Stockholm Centralstation',
    imageNote: '示意',
    leg: 'north',
    city: 'stockholm',
    name: 'SJ 夜車：斯德哥爾摩 → 阿比斯庫／基律納／納爾維克',
    local: 'Nattåg Stockholm – Narvik',
    desc: '傍晚從斯德哥爾摩中央車站出發，睡一晚，隔天中午前後到阿比斯庫、下午到終點納爾維克。車上有座位、6 人臥鋪（liggvagn）、3 人臥鋪，和附衛浴的 1–2 人包廂。',
    tips: [
      '2026 年 4 月起這班車只開到 Boden，要換白天的區間車；12/13 新時刻表起 SJ 恢復每天直達，臥鋪不用換車',
      '阿比斯庫有兩站：Abisko Turiststation（極光站、STF 山屋）和 Abisko Östra（村子），別下錯站',
      '臥鋪最先賣完，開賣就訂',
      '你們 Notion 裡的 Threads 資料：座位約 500–1000 SEK，臥鋪依等級 800–2000 SEK',
    ],
    cost: '座位約 500–1000 SEK／臥鋪 800–2000 SEK',
    time: '到阿比斯庫約 17 小時、納爾維克約 19 小時',
    event: 'night-train-direct',
    verify: true,
    links: [{ label: 'SJ', url: 'https://www.sj.se/en' }],
  },
  {
    id: 'mv-fly-krn',
    to: 'lapland',
    wiki: 'en:Kiruna Airport',
    geo: 'Stockholm Arlanda Airport',
    leg: 'north',
    city: 'stockholm',
    name: '飛機：斯德哥爾摩 → 基律納（不坐夜車的話）',
    local: 'ARN → KRN',
    desc: 'SAS、Norwegian 直飛約 1 小時 35 分。2026 年 10 月起 SAS 加開晚班北上、早班南下，可以跟國際線當天銜接。機場巴士配合航班進基律納市區，12–3 月還有機場直送阿比斯庫的接駁車。',
    time: '飛行約 1 小時 35 分',
    verify: true,
    links: [
      { label: 'SAS', url: 'https://www.flysas.com/' },
      { label: 'Norwegian', url: 'https://www.norwegian.com/' },
    ],
  },
  // ── 北極圈當地 ──
  {
    id: 'mv-krn-abisko',
    to: 'lapland',
    wiki: 'en:Kiruna Central Station',
    leg: 'lapland',
    city: 'lapland',
    name: '基律納 ↔ 阿比斯庫',
    local: 'Kiruna – Abisko',
    desc: '火車約 1–1.5 小時，也有公車和機場接駁車。自駕約 1.5–2 小時，但冬天路面結冰、天又黑，不熟雪地開車不建議。基律納火車站在市區外約 6 公里，有配合班次的免費接駁巴士。',
    time: '約 1–1.5 小時',
    verify: true,
    links: [{ label: 'Kiruna Lappland', url: 'https://kirunalapland.se/en/' }],
  },
  {
    id: 'mv-ofoten',
    to: 'narvik',
    wiki: 'en:Ofoten Line',
    geo: 'Abisko turiststation',
    leg: 'lapland',
    city: 'lapland',
    name: '景觀火車：阿比斯庫 → 納爾維克',
    local: 'Ofotbanen',
    desc: '從瑞典的高原一路下到挪威的峽灣，是北歐最美的鐵道路段之一。',
    time: '約 1.5–2 小時',
    verify: true,
  },
  // ── 回程 ──
  {
    id: 'mv-krn-home',
    to: 'lapland',
    wiki: 'en:Kiruna Airport',
    leg: 'home',
    city: 'lapland',
    name: '基律納 → 斯德哥爾摩 → 轉機',
    local: 'KRN → ARN',
    desc: 'SAS、Norwegian 約 1 小時 35 分回 Arlanda 再轉機；SAS 冬季有早班南下，可以當天接上長程航班。',
    time: '約 1 小時 35 分',
    verify: true,
  },
  {
    id: 'mv-evenes',
    to: 'narvik',
    wiki: 'en:Harstad/Narvik Airport, Evenes',
    leg: 'home',
    city: 'narvik',
    name: '從納爾維克回程',
    local: 'Harstad/Narvik Evenes',
    desc: '最近的機場是 Evenes（EVE），在納爾維克外約 80 公里，機場巴士 1 小時多，通常飛奧斯陸再轉機。',
    time: '機場巴士 1 小時多',
    verify: true,
  },
  // ── 市區交通票 ──
  {
    id: 'mv-prague-pid',
    wiki: 'en:Prague Metro',
    pin: false,
    leg: 'city',
    city: 'prague',
    name: '布拉格：PID 大眾運輸票',
    local: 'PID Lítačka',
    desc: '地鐵、電車、公車共用一套票，用 PID Lítačka app 買比較便宜；紙本票上車要先打票，被查到沒票罰得很重。',
    cost: '30 分 36 Kč／90 分 46 Kč／24 小時 140 Kč／72 小時 340 Kč（app 價）',
    verify: true,
    links: [{ label: 'PID', url: 'https://pid.cz/en/tickets/' }],
  },
  {
    id: 'mv-vienna-wl',
    wiki: 'en:Vienna U-Bahn',
    pin: false,
    leg: 'city',
    city: 'vienna',
    name: '維也納：Wiener Linien 交通票',
    local: 'WienMobil',
    desc: '地鐵、電車、公車同一套票；待 2–3 天買 24／48／72 小時票最划算，用 WienMobil app 買。',
    verify: true,
    links: [{ label: 'Wiener Linien', url: 'https://www.wienerlinien.at/' }],
  },
  {
    id: 'mv-stockholm-sl',
    wiki: 'en:Stockholm Metro',
    pin: false,
    leg: 'city',
    city: 'stockholm',
    name: '斯德哥爾摩：SL 交通',
    local: 'SL',
    desc: '地鐵、公車、渡輪共用 SL 票，可以直接用信用卡或手機感應進站（一人一張卡），或在 SL app 買 24／72 小時票。',
    verify: true,
    links: [{ label: 'SL', url: 'https://sl.se/en' }],
  },
];

const SIGHTS = [
  // ── 布拉格 ──
  {
    id: 'fun-prg-market',
    wiki: 'en:Old Town Square',
    city: 'prague',
    name: '老城廣場聖誕市集',
    local: 'Staroměstské náměstí',
    desc: '布拉格最大的聖誕市集，26 公尺高的聖誕樹在開幕日 11/28 傍晚 16:30 點燈；瓦茨拉夫廣場、和平廣場也有市集。',
    tips: ['熱紅酒 svařák、烤香腸必吃', '烤火腿（Pražská šunka）按重量計價，點之前先問清楚總價'],
    when: '2026/11/28–2027/1/6，每天 10:00–22:00',
    event: 'prague-market',
    map: 'Staroměstské náměstí',
    links: [{ label: 'Prague City Tourism', url: 'https://prague.eu/en/' }],
  },
  {
    id: 'fun-prg-orloj',
    wiki: 'en:Prague astronomical clock',
    city: 'prague',
    name: '天文鐘＋舊市政廳塔',
    local: 'Pražský orloj',
    desc: '整點有使徒人偶出來報時；爬上舊市政廳塔可以俯瞰整個聖誕市集和提恩教堂。',
    time: '1 小時',
    map: 'Prague Astronomical Clock',
  },
  {
    id: 'fun-prg-castle',
    wiki: 'en:Prague Castle',
    city: 'prague',
    name: '布拉格城堡',
    local: 'Pražský hrad',
    desc: '聖維特主教座堂、舊皇宮、黃金巷都在裡面，買聯票一次看完。冬天下午 4 點多天就黑了，建議早上去。',
    time: '半天',
    verify: true,
    map: 'Prague Castle',
    links: [{ label: '官網', url: 'https://www.hrad.cz/en' }],
  },
  {
    id: 'fun-prg-charles',
    wiki: 'en:Charles Bridge',
    city: 'prague',
    name: '查理大橋',
    local: 'Karlův most',
    desc: '白天擠滿人，清晨 7–8 點最美也最好拍；從城堡一路往下走過小城區，就會接到橋上。',
    time: '30 分鐘',
    map: 'Charles Bridge',
  },
  {
    id: 'fun-prg-malastrana',
    wiki: 'en:Lennon Wall',
    city: 'prague',
    name: '小城區＋約翰藍儂牆',
    local: 'Malá Strana',
    desc: '城堡山腳下的巴洛克街區，巷弄和咖啡館很好逛，藍儂牆就在查理大橋橋頭附近。',
    time: '1–2 小時',
    map: 'Lennon Wall Prague',
  },
  {
    id: 'fun-prg-klementinum',
    wiki: 'en:Clementinum',
    city: 'prague',
    name: '克萊門特學院圖書館',
    local: 'Klementinum',
    desc: '常被稱為世界最美的圖書館之一，跟著導覽在門口看巴洛克藏書廳，最後爬上天文塔看老城的屋頂。',
    time: '1 小時',
    verify: true,
    map: 'Klementinum',
  },
  {
    id: 'fun-prg-kutna',
    wiki: 'en:Sedlec Ossuary',
    city: 'prague',
    name: '人骨教堂一日遊',
    local: 'Kutná Hora',
    desc: '火車約 1 小時。塞德萊茨人骨教堂用上萬人的骨頭裝飾，再加上 UNESCO 的聖芭芭拉大教堂，半天到一天。行程有空檔時的好選擇。',
    time: '半天～一天',
    verify: true,
    map: 'Sedlec Ossuary',
  },
  // ── 庫倫洛夫 ──
  {
    id: 'fun-ck-town',
    wiki: 'en:Český Krumlov Castle',
    city: 'krumlov',
    name: '庫倫洛夫老城＋城堡',
    local: 'Český Krumlov',
    desc: '被河道環繞的 UNESCO 紅屋頂小鎮（台灣人常叫它 CK 小鎮），爬上城堡的彩繪塔可以看到整片屋頂。冬天城堡內部導覽大多休館、開放時間縮短，出發前先查。',
    time: '半天～一天',
    verify: true,
    map: 'Český Krumlov Castle',
  },
  // ── 維也納 ──
  {
    id: 'fun-vie-rathaus',
    wiki: 'en:Vienna City Hall',
    city: 'vienna',
    name: '市政廳聖誕市集',
    local: 'Wiener Christkindlmarkt',
    desc: '維也納最大的聖誕市集，市政廳前的樹都掛滿燈；旁邊的溜冰場開到 1/6。',
    tips: ['熱飲的紀念杯要付押金，退杯拿回押金，或直接帶走當紀念'],
    when: '11/13–12/26，10:00–22:00（12/24 到 18:30）',
    event: 'vienna-rathaus',
    map: 'Wiener Christkindlmarkt Rathausplatz',
  },
  {
    id: 'fun-vie-schoenbrunn',
    wiki: 'en:Schönbrunn Palace',
    city: 'vienna',
    name: '美泉宮＋聖誕新年市集',
    local: 'Schloss Schönbrunn',
    desc: '哈布斯堡家族的夏宮，宮殿導覽要預約時段；宮前廣場的市集開到 1/6，是維也納收得最晚的市集之一。',
    when: '市集 11/6–2027/1/6',
    event: 'vienna-schoenbrunn',
    time: '半天',
    verify: true,
    links: [{ label: '官網', url: 'https://www.schoenbrunn.at/en/' }],
  },
  {
    id: 'fun-vie-stephansdom',
    wiki: 'en:St. Stephen\'s Cathedral, Vienna',
    city: 'vienna',
    name: '聖史蒂芬主教座堂',
    local: 'Stephansdom',
    desc: '維也納的地標，爬南塔 343 階可以近看彩色磚瓦屋頂；教堂前的廣場也有聖誕市集。',
    time: '1 小時',
    map: 'Stephansdom',
  },
  {
    id: 'fun-vie-belvedere',
    wiki: 'en:Belvedere, Vienna',
    city: 'vienna',
    name: '美景宮（克林姆《吻》）',
    local: 'Belvedere',
    desc: '上美景宮收藏克林姆的《吻》，看完逛宮前的聖誕市集（開到 12/31）。',
    time: '2 小時',
    links: [{ label: '官網', url: 'https://www.belvedere.at/en' }],
  },
  {
    id: 'fun-vie-opera',
    wiki: 'en:Vienna State Opera',
    city: 'vienna',
    geo: 'Wiener Staatsoper',
    name: '國家歌劇院站票',
    local: 'Wiener Staatsoper Stehplatz',
    desc: '站票只要十幾歐元，就能看世界頂級的歌劇或芭蕾，可以網路預購或演出前到現場買；冬天是演出旺季。',
    verify: true,
    links: [{ label: '官網', url: 'https://www.wiener-staatsoper.at/en/' }],
  },
  {
    id: 'fun-vie-hofburg',
    wiki: 'en:Hofburg',
    city: 'vienna',
    name: '霍夫堡＋茜茜公主博物館',
    local: 'Hofburg',
    desc: '皇室的冬宮，茜茜公主博物館、皇室套房、銀器館一張票看完。',
    time: '2 小時',
    map: 'Sisi Museum Hofburg',
  },
  {
    id: 'fun-vie-spittelberg',
    wiki: 'en:Christmas market',
    city: 'vienna',
    geo: 'Spittelberg, Wien',
    imageNote: '示意',
    name: 'Spittelberg 巷弄市集',
    local: 'Spittelberg',
    desc: '比市政廳小很多，攤位藏在石板小巷裡，手作小物多，氣氛比較文青。',
    when: '約 11/13–12/23',
    verify: true,
    map: 'Spittelberg Christmas Market',
  },
  // ── 薩爾斯堡 ──
  {
    id: 'fun-szg-market',
    wiki: 'en:Salzburg Cathedral',
    city: 'salzburg',
    name: '薩爾斯堡聖誕市集',
    local: 'Christkindlmarkt Domplatz',
    desc: '在主教座堂廣場和 Residenzplatz，背景就是山上的要塞，是歷史很久的聖誕市集。',
    when: '11/19–2027/1/1（12/24 只到 15:00）',
    event: 'salzburg-market',
    links: [{ label: '官網', url: 'https://www.christkindlmarkt.co.at/en/' }],
  },
  {
    id: 'fun-szg-fortress',
    wiki: 'en:Hohensalzburg Fortress',
    city: 'salzburg',
    name: '薩爾斯堡要塞',
    local: 'Festung Hohensalzburg',
    desc: '坐纜車上山，舊城、河和雪山一次入鏡，傍晚上去看夜景最漂亮。',
    time: '2 小時',
    map: 'Festung Hohensalzburg',
  },
  {
    id: 'fun-szg-oldtown',
    wiki: 'en:Mozart\'s Birthplace',
    city: 'salzburg',
    name: '糧食胡同＋莫札特出生地',
    local: 'Getreidegasse',
    desc: '掛滿鐵鑄招牌的購物街，莫札特出生的黃色房子就在這條街上。',
    time: '1–2 小時',
    map: 'Mozart Geburtshaus',
  },
  {
    id: 'fun-szg-mirabell',
    wiki: 'en:Mirabell Palace',
    city: 'salzburg',
    name: '米拉貝爾花園',
    local: 'Mirabellgarten',
    desc: '《真善美》Do-Re-Mi 的拍攝地，冬天沒什麼花，但順路走一圈拍照還是很漂亮。',
    time: '30 分鐘',
    map: 'Mirabellgarten',
  },
  // ── 哈修塔特 ──
  {
    id: 'fun-hal-village',
    wiki: 'en:Hallstatt',
    city: 'hallstatt',
    name: '哈修塔特湖畔小鎮',
    local: 'Hallstatt',
    desc: '明信片視角在小鎮北邊的湖岸步道。冬天遊客少，雪景加湖面倒影很美，但不少店和餐廳會休息。',
    tips: ['聖誕市集一年只有 12/8 一天'],
    time: '半天',
    map: 'Hallstatt viewpoint',
  },
  {
    id: 'fun-hal-skywalk',
    wiki: 'de:Salzwelten',
    city: 'hallstatt',
    geo: 'Aussichtsplattform Welterbeblick',
    imageNote: '示意',
    name: '世界遺產觀景台 Skywalk',
    local: 'Welterbeblick',
    desc: '坐鹽礦纜車上山看整個湖和小鎮。鹽礦冬天通常休館，纜車 2025–26 年又在整修，12 月能不能上去一定要先查。',
    verify: true,
    links: [{ label: 'Salzwelten', url: 'https://www.salzwelten.at/en/' }],
  },
  // ── 斯德哥爾摩 ──
  {
    id: 'fun-sto-gamlastan',
    wiki: 'en:Stortorget',
    city: 'stockholm',
    name: '老城 Gamla Stan＋大廣場聖誕市集',
    local: 'Stortorget',
    desc: '彩色老房子圍起來的小廣場，攤位賣薑餅、手工蠟燭和熱紅酒 glögg；老城小巷和皇宮都在附近，走路就能逛完。',
    when: '約 11/21–12/23（依往年推估）',
    event: 'stockholm-gamlastan',
    verify: true,
    map: 'Stortorget Stockholm',
  },
  {
    id: 'fun-sto-skansen',
    wiki: 'en:Skansen',
    city: 'stockholm',
    geo: 'Skansen, Stockholm',
    name: 'Skansen 露天博物館聖誕市集',
    local: 'Skansen',
    desc: '1903 年就開始辦的傳統市集，有營火、烤杏仁和瑞典手工藝，只有降臨期的週末開。',
    when: '11/27–12/20，週五～週日',
    event: 'stockholm-skansen',
    map: 'Skansen',
    links: [{ label: '官網', url: 'https://www.skansen.se/en/' }],
  },
  {
    id: 'fun-sto-vasa',
    wiki: 'en:Vasa Museum',
    city: 'stockholm',
    name: '瓦薩沉船博物館',
    local: 'Vasamuseet',
    desc: '1628 年首航就沉沒的戰艦，幾乎完整地被打撈上岸，就算不是船迷也會被它的尺寸震撼。',
    time: '1.5–2 小時',
    links: [{ label: '官網', url: 'https://www.vasamuseet.se/en' }],
  },
  {
    id: 'fun-sto-metro',
    wiki: 'en:T-Centralen',
    city: 'stockholm',
    name: '地鐵藝術巡禮',
    local: 'T-Centralen / Kungsträdgården',
    desc: '斯德哥爾摩的地鐵號稱世界最長的藝廊，T-Centralen 藍線的洞穴車站最有名，有 SL 票就能逛。',
    time: '1 小時',
    map: 'T-Centralen',
  },
  {
    id: 'fun-sto-lucia',
    wiki: 'en:Saint Lucy\'s Day',
    pin: false,
    city: 'stockholm',
    name: '聖露西亞節',
    local: 'Luciadagen 12/13',
    desc: '12/13 的瑞典傳統：穿白衣、頭戴蠟燭冠的隊伍在教堂裡唱歌。如果那天剛好在瑞典，找一場 Lucia 音樂會。',
    when: '12/13',
    verify: true,
  },
  // ── 阿比斯庫・基律納 ──
  {
    id: 'fun-lap-skystation',
    wiki: 'en:Abisko National Park',
    geo: 'Aurora Sky Station',
    imageNote: '示意',
    city: 'lapland',
    name: '極光站 Aurora Sky Station',
    local: 'Abisko',
    desc: '坐纜椅上 Nuolja 山看極光。阿比斯庫常有「藍洞」晴空，是歐洲看到極光機率最高的地方之一。夜間行程每晚只有 40 個名額，含嚮導、纜椅來回和保暖衣物。',
    tips: ['另有 17:30 集合的極光晚餐（10/1 起）', '天候太差纜椅停駛不退費；看不看得到極光不保證'],
    when: '夜間行程 2026/10/19–2027/3/27，20:30 開始',
    event: 'aurora-sky-station',
    verify: true,
    links: [{ label: '官網', url: 'https://auroraskystation.se/en/' }],
  },
  {
    id: 'fun-lap-dogsled',
    wiki: 'en:Dog sled',
    pin: false,
    imageNote: '示意',
    city: 'lapland',
    name: '狗拉雪橇',
    local: 'Hundspann',
    desc: '阿比斯庫、基律納都有，半天行程最熱門。12 月白天很短，選中午前後出發天色最亮。',
    time: '半天',
    verify: true,
  },
  {
    id: 'fun-lap-icehotel',
    wiki: 'en:Icehotel (Jukkasjärvi)',
    city: 'lapland',
    name: '冰旅館 ICEHOTEL',
    local: 'Jukkasjärvi',
    desc: '每年用托爾訥河的冰重新打造，ICEHOTEL 37 在 2026/12/11 開幕，沒住也能買參觀票。12/11 前只有全年開放的 ICEHOTEL 365。',
    when: '2026/12/11 開幕',
    event: 'icehotel',
    time: '2 小時',
    verify: true,
    links: [{ label: '官網', url: 'https://www.icehotel.com/' }],
  },
  {
    id: 'fun-lap-sami',
    wiki: 'en:Reindeer',
    geo: 'Jukkasjärvi',
    imageNote: '示意',
    city: 'lapland',
    name: '薩米文化＋餵馴鹿',
    local: 'Nutti Sámi Siida',
    desc: '在冰旅館所在的 Jukkasjärvi，可以餵馴鹿、聽薩米人講北極圈的生活，常跟冰旅館排同一天。',
    time: '1–2 小時',
    verify: true,
  },
  {
    id: 'fun-lap-canyon',
    wiki: 'en:Abisko National Park',
    geo: 'Abisko turiststation',
    city: 'lapland',
    name: '阿比斯庫峽谷步道',
    local: 'Abiskojåkka',
    desc: '從 STF 山屋走十分鐘就到，冰封的河谷很壯觀。路面結冰，要穿抓地力好的鞋或帶簡易冰爪。',
    time: '1 小時',
    map: 'Abiskojåkka canyon',
  },
  {
    id: 'fun-lap-church',
    wiki: 'en:Kiruna Church',
    geo: 'Kiruna kyrka',
    city: 'lapland',
    name: '基律納教堂（整座搬家）',
    local: 'Kiruna kyrka',
    desc: '為了鐵礦擴張，2025 年 8 月整座木造教堂用平板車搬到 5 公里外的新市中心，預計 2026 年底重新開放。',
    verify: true,
    map: 'Kiruna kyrka',
  },
  // ── 納爾維克 ──
  {
    id: 'fun-nar-fjell',
    wiki: 'no:Narvikfjellet',
    city: 'narvik',
    name: '納爾維克山纜車',
    local: 'Narvikfjellet',
    desc: '坐纜車上山俯瞰峽灣，天氣好的晚上也能看極光；冬天是滑雪場。',
    verify: true,
    map: 'Narvikfjellet',
  },
  // ── 2026-09 依 Rick Steves、官方觀光網站等補充的熱門景點 ──
  {
    id: 'fun-prg-strahov',
    wiki: 'en:Strahov Monastery',
    city: 'prague',
    name: '史特拉霍夫修道院圖書館',
    local: 'Strahovská knihovna',
    desc: '城堡旁的修道院圖書館，神學廳和哲學廳的壁畫天花板配上整面古書牆，非常壯觀（站在門口往內看）。離城堡走路幾分鐘，可以排在一起。',
    time: '1 小時',
    verify: true,
    map: 'Strahov Library',
  },
  {
    id: 'fun-prg-josefov',
    wiki: 'en:Josefov',
    geo: 'Old Jewish Cemetery, Prague',
    city: 'prague',
    name: '猶太區',
    local: 'Josefov',
    desc: '歐洲保存最完整的猶太文化遺產之一：西班牙會堂的摩爾式金色內部、墓碑層層疊疊的舊猶太墓園、平卡斯會堂牆上的名冊。一張聯票參觀多個會堂和墓園。',
    tips: ['週六和猶太節日休館', '冬季開放到 16:30'],
    cost: '聯票 600 Kč（26 歲以下學生 400 Kč）',
    time: '2–3 小時',
    verify: true,
    map: 'Old Jewish Cemetery Prague',
    links: [{ label: '猶太博物館', url: 'https://www.jewishmuseum.cz/en/' }],
  },
  {
    id: 'fun-prg-obecni',
    wiki: 'en:Municipal House',
    city: 'prague',
    name: '市民會館',
    local: 'Obecní dům',
    desc: '布拉格最華麗的新藝術建築，慕夏參與了室內裝飾。可以參加導覽看史麥塔納音樂廳，或只在一樓的咖啡館喝杯咖啡看裝潢。',
    time: '1 小時',
    verify: true,
    map: 'Obecní dům',
  },
  {
    id: 'fun-prg-petrin',
    wiki: 'en:Petřín Lookout Tower',
    city: 'prague',
    name: '佩特任山＋觀景塔',
    local: 'Petřín',
    desc: '小城區上方的山丘公園。坐纜車上山，再爬仿艾菲爾鐵塔的觀景塔看整個布拉格；纜車 2026/9/22 剛換新的全景車廂重新通車。',
    cost: '纜車單程 100 Kč（PID app 90 Kč）',
    time: '2 小時',
    verify: true,
    map: 'Petřín Lookout Tower',
  },
  {
    id: 'fun-prg-vysehrad',
    wiki: 'en:Vyšehrad',
    city: 'prague',
    name: '高堡',
    local: 'Vyšehrad',
    desc: '伏爾塔瓦河畔的古堡山丘，觀光客少、視野好，墓園裡長眠著德弗札克、慕夏等名人，適合想避開人潮的半天。',
    time: '2 小時',
    map: 'Vyšehrad',
  },
  {
    id: 'fun-vie-khm',
    wiki: 'en:Kunsthistorisches Museum',
    city: 'vienna',
    name: '藝術史博物館',
    local: 'Kunsthistorisches Museum',
    desc: '哈布斯堡家族的收藏，拉斐爾、提香、林布蘭都有，布勒哲爾展廳是世界最完整的收藏。建築本身和圓頂下的咖啡館也很值得。',
    time: '2–3 小時',
    verify: true,
    map: 'Kunsthistorisches Museum',
  },
  {
    id: 'fun-vie-treasury',
    wiki: 'en:Imperial Treasury, Vienna',
    geo: 'Kaiserliche Schatzkammer, Wien',
    city: 'vienna',
    name: '皇家寶物館',
    local: 'Kaiserliche Schatzkammer',
    desc: '霍夫堡裡的寶物館，收藏神聖羅馬帝國皇冠、奧地利帝國皇冠等王室珍寶，常被列為歐洲最精彩的珍寶收藏之一。',
    time: '1–1.5 小時',
    verify: true,
    map: 'Kaiserliche Schatzkammer Wien',
  },
  {
    id: 'fun-vie-prater',
    wiki: 'en:Wiener Riesenrad',
    city: 'vienna',
    name: '普拉特摩天輪＋冬季市集',
    local: 'Wiener Riesenrad / Wintermarkt',
    desc: '1897 年的古董摩天輪，電影《黑獄亡魂》的經典場景。冬天摩天輪下有冬季市集、現場演唱和遊樂設施。',
    when: '冬季市集 2026/11/20–2027/1/6',
    event: 'vienna-prater',
    time: '1–2 小時',
    verify: true,
    map: 'Wiener Riesenrad',
  },
  {
    id: 'fun-szg-hellbrunn',
    wiki: 'en:Hellbrunn Palace',
    city: 'salzburg',
    name: '海布倫宮聖誕市集',
    local: 'Hellbrunner Adventzauber',
    desc: '宮殿中庭擺滿 400 多棵裝飾冷杉，像走進童話森林；有小火車、營火和手作攤位。從舊城搭公車約 20 分鐘。',
    when: '2026/11/19–12/24，週一休（週二～五 13:00 起）',
    cost: '約 €7（含一杯熱飲）',
    event: 'hellbrunn-advent',
    time: '2 小時',
    verify: true,
    map: 'Schloss Hellbrunn',
  },
  {
    id: 'fun-szg-silentnight',
    wiki: 'en:Silent Night Chapel',
    city: 'salzburg',
    name: '《平安夜》教堂',
    local: 'Stille-Nacht-Kapelle, Oberndorf',
    desc: '聖誕歌《平安夜》1818 年首次演唱的地方，在薩爾斯堡北邊約 20 公里的小鎮。聖誕季有小市集，12/24 下午 5 點有紀念儀式；當天停車位全滿，只能搭大眾運輸或參加團。',
    time: '半天',
    verify: true,
    map: 'Stille Nacht Kapelle Oberndorf',
  },
  {
    id: 'fun-sto-cityhall',
    wiki: 'en:Stockholm City Hall',
    city: 'stockholm',
    name: '斯德哥爾摩市政廳',
    local: 'Stadshuset',
    desc: '諾貝爾晚宴在這裡的藍廳舉行，樓上的金廳用上千萬片金色馬賽克拼成。只能跟約 45 分鐘的導覽參觀。',
    tips: ['高塔冬天不開放（5–9 月才開），2027–28 年整修'],
    time: '1 小時',
    verify: true,
    map: 'Stockholm City Hall',
  },
  {
    id: 'fun-sto-palace',
    wiki: 'en:Stockholm Palace',
    city: 'stockholm',
    name: '斯德哥爾摩皇宮',
    local: 'Kungliga slottet',
    desc: '歐洲還在使用的最大皇宮之一，看王室套房和寶物館，中午有衛兵交接。就在老城裡，逛市集順路。',
    time: '1.5–2 小時',
    verify: true,
    map: 'Stockholm Palace',
  },
  {
    id: 'fun-lap-lkab',
    wiki: 'en:Kiruna Mine',
    city: 'lapland',
    name: '基律納鐵礦參觀',
    local: 'LKAB InfoMine',
    desc: '搭車進入世界最大的地下鐵礦，在地下的遊客中心看採礦怎麼運作，也會講整座城市為什麼要搬家。',
    tips: ['冬季只有特定日期開團、至少 10 人成行，要透過 Kiruna Lappland 預約'],
    cost: '約 350 SEK',
    time: '2.5–3 小時',
    verify: true,
    links: [{ label: 'Kiruna Lappland', url: 'https://kirunalapland.se/en/mine-tour/' }],
  },
  {
    id: 'fun-lap-auroratour',
    wiki: 'en:Aurora',
    pin: false,
    imageNote: '示意',
    city: 'lapland',
    name: '極光追逐攝影團',
    local: 'Aurora photo tour',
    desc: '導遊看雲圖開車去追晴空，通常附熱飲和專業相機幫你拍人像極光照，約 3.5 小時；阿比斯庫、基律納都有出發。陰天時比守在固定地點更有機會。',
    time: '約 3.5 小時',
    verify: true,
  },
];

const FOOD = [
  // ── 布拉格 ──
  {
    id: 'food-prg-lokal',
    wiki: 'en:Pilsner',
    geo: 'Lokál, Dlouhá, Praha',
    imageNote: '示意',
    city: 'prague',
    name: 'Lokál Dlouhááá',
    local: '捷克啤酒屋',
    desc: '在地人也常去的啤酒屋，坦克直送的皮爾森啤酒（tankové pivo）配捷克家常菜，價格實在。',
    tips: ['點 svíčková（奶油醬燉牛肉配麵包丸子）或炸豬排 řízek'],
    map: 'Lokál Dlouhááá Praha',
  },
  {
    id: 'food-prg-louvre',
    wiki: 'cs:Café Louvre',
    geo: 'Café Louvre, Národní, Praha',
    city: 'prague',
    name: 'Café Louvre',
    local: '百年咖啡館',
    desc: '1902 年開到現在的老咖啡館，卡夫卡、愛因斯坦都曾是座上客；早餐和甜點很受歡迎，建議訂位。',
    map: 'Café Louvre Praha',
  },
  {
    id: 'food-prg-kantyna',
    wiki: 'en:Czech cuisine',
    geo: 'Kantýna, Politických vězňů, Praha',
    imageNote: '示意',
    city: 'prague',
    name: 'Kantýna',
    local: '肉舖餐廳',
    desc: '由肉舖改成的餐廳，先到櫃台點肉、點菜再找位子，烤肉和牛排很強。',
    verify: true,
    map: 'Kantýna Praha',
  },
  {
    id: 'food-prg-dishes',
    wiki: 'en:Svíčková',
    pin: false,
    imageNote: '示意',
    city: 'prague',
    name: '捷克菜必點清單',
    local: 'česká kuchyně',
    desc: 'svíčková（奶油燉牛肉）、guláš 配 knedlíky（麵包丸子）、vepřo knedlo zelo（烤豬肉＋丸子＋酸菜）、smažený sýr（炸起司）。語言教室學到的菜名可以直接拿來點菜！',
  },
  {
    id: 'food-prg-market',
    wiki: 'en:Trdelník',
    pin: false,
    imageNote: '示意',
    city: 'prague',
    name: '聖誕市集小吃',
    local: 'svařák / klobása / trdelník',
    desc: 'svařák 熱紅酒、klobása 烤香腸、trdelník 煙囪捲。煙囪捲其實是觀光客小吃、不是捷克傳統，但冬天吃熱的還是很幸福。',
    tips: ['烤火腿按 100 g 計價，先問清楚總價再點'],
    event: 'prague-market',
  },
  // ── 庫倫洛夫 ──
  {
    id: 'food-ck-krcma',
    wiki: 'en:Český Krumlov',
    geo: 'Šatlavská, Český Krumlov',
    imageNote: '示意',
    city: 'krumlov',
    name: 'Krčma v Šatlavské',
    local: '中世紀燒烤酒館',
    desc: '地窖裡的炭火燒烤，蠟燭照明、木頭長桌，很有中世紀氣氛，晚餐要訂位。',
    verify: true,
    map: 'Krčma v Šatlavské',
  },
  // ── 維也納 ──
  {
    id: 'food-vie-figlmuller',
    wiki: 'en:Wiener schnitzel',
    geo: 'Figlmüller, Wollzeile, Wien',
    imageNote: '示意',
    city: 'vienna',
    name: 'Figlmüller',
    local: 'Wiener Schnitzel',
    desc: '比盤子還大的炸肉排（正宗維也納炸肉排用小牛肉，這家的招牌是豬肉），擠點檸檬就很好吃，要訂位。',
    map: 'Figlmüller Wollzeile',
  },
  {
    id: 'food-vie-plachutta',
    wiki: 'en:Tafelspitz',
    geo: 'Plachutta, Wollzeile, Wien',
    imageNote: '示意',
    city: 'vienna',
    name: 'Plachutta',
    local: 'Tafelspitz',
    desc: '招牌 Tafelspitz 清燉牛肉：先喝湯、再把骨髓抹在麵包上，最後配蘋果辣根醬吃肉。',
    map: 'Plachutta Wollzeile',
  },
  {
    id: 'food-vie-cafe',
    wiki: 'en:Café Central',
    city: 'vienna',
    name: '維也納咖啡館',
    local: 'Café Central / Sperl / Sacher',
    desc: 'Café Central 最華麗、排隊也最長；Café Sperl 比較有在地老咖啡館的味道；想吃正宗薩赫蛋糕就去 Café Sacher。',
    map: 'Café Central Wien',
  },
  {
    id: 'food-vie-wurstel',
    wiki: 'en:Käsekrainer',
    geo: 'Albertinaplatz, Wien',
    imageNote: '示意',
    city: 'vienna',
    name: '歌劇院旁香腸攤',
    local: 'Bitzinger Würstelstand',
    desc: 'Käsekrainer 起司爆漿香腸配芥末，看完歌劇的經典宵夜。',
    map: 'Bitzinger Würstelstand Albertina',
  },
  // ── 薩爾斯堡 ──
  {
    id: 'food-szg-augustiner',
    wiki: 'de:Augustiner Bräu Kloster Mülln',
    city: 'salzburg',
    name: '修道院啤酒屋',
    local: 'Augustiner Bräustübl Mülln',
    desc: '修道院自己釀的啤酒，從架上拿陶杯去櫃台裝；走廊的小攤可以買烤豬腳、椒鹽卷餅配著吃。',
    map: 'Augustiner Bräustübl Salzburg',
  },
  {
    id: 'food-szg-tomaselli',
    wiki: 'de:Café Tomaselli',
    city: 'salzburg',
    name: 'Café Tomaselli',
    local: '1700 年代的咖啡館',
    desc: '奧地利最老的咖啡館之一，服務生會端著蛋糕盤到桌邊讓你挑。',
    map: 'Café Tomaselli Salzburg',
  },
  {
    id: 'food-szg-bosna',
    wiki: 'en:Bosna (sausage)',
    geo: 'Balkan Grill Walter, Getreidegasse, Salzburg',
    imageNote: '示意',
    city: 'salzburg',
    name: 'Balkan Grill Walter',
    local: 'Bosna 熱狗',
    desc: '藏在 Getreidegasse 小巷裡的小窗口，Bosna 洋蔥咖哩熱狗是薩爾斯堡在地名物，常常要排隊。',
    map: 'Balkan Grill Walter Salzburg',
  },
  // ── 哈修塔特 ──
  {
    id: 'food-hal-fish',
    wiki: 'en:Arctic char',
    pin: false,
    imageNote: '示意',
    city: 'hallstatt',
    name: '湖魚料理',
    local: 'Reinanke / Saibling',
    desc: '哈修塔特湖的白鮭、紅點鮭是當地特產。鎮上餐廳本來就不多，冬天還有不少休息，去之前先查營業時間，或自己準備午餐。',
    verify: true,
  },
  // ── 斯德哥爾摩 ──
  {
    id: 'food-sto-julbord',
    wiki: 'en:Julbord',
    pin: false,
    imageNote: '示意',
    city: 'stockholm',
    name: '聖誕自助餐 julbord',
    local: 'Julbord',
    desc: '12 月限定的瑞典聖誕大餐：醃鯡魚、肉丸、聖誕火腿、Janssons frestelse 焗馬鈴薯一次吃到，很多餐廳要提早訂位。',
    when: '約 11 月底–12/23',
    verify: true,
  },
  {
    id: 'food-sto-meatballs',
    wiki: 'en:Swedish meatballs',
    geo: 'Meatballs for the People, Stockholm',
    imageNote: '示意',
    city: 'stockholm',
    name: 'Meatballs for the People',
    local: '瑞典肉丸',
    desc: '專賣瑞典肉丸，除了經典牛豬肉，還有麋鹿、野豬等口味，配越橘醬和馬鈴薯泥。',
    verify: true,
    map: 'Meatballs for the People Stockholm',
  },
  {
    id: 'food-sto-saluhall',
    wiki: 'sv:Östermalms saluhall',
    city: 'stockholm',
    name: 'Östermalms Saluhall',
    local: '1888 年的美食市場',
    desc: '海鮮、起司、熟食攤都有，可以直接坐在攤位吧台吃，想吃鮮蝦三明治或海鮮湯就來這。',
    map: 'Östermalms Saluhall',
  },
  {
    id: 'food-sto-fika',
    wiki: 'en:Cinnamon roll',
    geo: 'Vete-Katten, Kungsgatan, Stockholm',
    imageNote: '示意',
    city: 'stockholm',
    name: 'Fika 咖啡時光',
    local: 'Vete-Katten / Café Saturnus',
    desc: 'Fika 是瑞典人每天的咖啡＋甜點時間。Vete-Katten 是 1928 年的老店；Café Saturnus 的肉桂捲大到跟臉一樣。',
    map: 'Vete-Katten Stockholm',
  },
  {
    id: 'food-sto-pelikan',
    wiki: 'en:Swedish cuisine',
    geo: 'Pelikan, Blekingegatan, Stockholm',
    imageNote: '示意',
    city: 'stockholm',
    name: 'Pelikan',
    local: '老派啤酒屋',
    desc: '南島上的百年啤酒屋，挑高的木頭大廳，吃傳統瑞典家常菜：肉丸、醃鯡魚、豬腳。',
    verify: true,
    map: 'Pelikan Stockholm',
  },
  {
    id: 'food-sto-xmas',
    wiki: 'en:Lussekatt',
    pin: false,
    imageNote: '示意',
    city: 'stockholm',
    name: '聖誕季點心',
    local: 'glögg / lussekatt / pepparkakor',
    desc: 'glögg 熱紅酒加葡萄乾和杏仁、番紅花麵包 lussekatt（12/13 前後最多）、薑餅 pepparkakor，市集和咖啡館都買得到。',
  },
  // ── 阿比斯庫・基律納 ──
  {
    id: 'food-lap-stf',
    wiki: 'sv:Abisko turiststation',
    city: 'lapland',
    name: 'STF 阿比斯庫山屋餐廳',
    local: 'Abisko Turiststation',
    desc: '阿比斯庫能吃飯的地方很少，山屋餐廳有北極紅點鮭、馴鹿肉這類在地菜，晚餐建議先訂。村子裡有小超市，也可以買回房間煮。',
    verify: true,
  },
  {
    id: 'food-lap-reindeer',
    wiki: 'en:Sautéed reindeer',
    pin: false,
    imageNote: '示意',
    city: 'lapland',
    name: '馴鹿料理',
    local: 'Renskav / Suovas',
    desc: 'renskav 是薄切馴鹿肉炒奶油醬，配馬鈴薯泥和越橘醬；suovas 是薩米人的煙燻馴鹿肉，常包在薄餅裡吃。',
  },
  {
    id: 'food-lap-ripan',
    wiki: 'en:Kiruna',
    geo: 'Camp Ripan, Kiruna',
    imageNote: '示意',
    city: 'lapland',
    name: 'Camp Ripan 餐廳',
    local: 'Kiruna',
    desc: '基律納很有名的北極在地料理餐廳，食材多來自拉普蘭當地。',
    verify: true,
    map: 'Camp Ripan Kiruna',
  },
];

const STAYS = [
  // ── 布拉格 ──
  {
    id: 'stay-prg-old',
    wiki: 'en:Malá Strana',
    city: 'prague',
    name: '老城區／小城區',
    local: 'Staré Město / Malá Strana',
    desc: '走路就到聖誕市集、查理大橋和城堡，晚上逛完市集走回去最方便。聖誕季價格最高、要最早訂。',
    map: 'Staré Město Praha',
  },
  {
    id: 'stay-prg-vinohrady',
    wiki: 'en:Vinohrady',
    city: 'prague',
    name: 'Vinohrady／新城',
    local: 'Vinohrady / Nové Město',
    desc: '離老城 1–3 站地鐵，比較安靜、CP 值高，和平廣場也有自己的聖誕市集。',
    map: 'Vinohrady Praha',
  },
  {
    id: 'stay-prg-station',
    wiki: 'en:Praha hlavní nádraží',
    city: 'prague',
    name: '中央車站附近',
    local: 'Praha hlavní nádraží',
    desc: '隔天要搭早班火車去奧地利、或搭 AE 從機場進市區的話最方便。',
    map: 'Praha hlavní nádraží',
  },
  // ── 庫倫洛夫 ──
  {
    id: 'stay-ck-old',
    wiki: 'en:Český Krumlov',
    city: 'krumlov',
    name: '庫倫洛夫老城民宿',
    local: 'Vnitřní Město',
    desc: '住城裡才看得到入夜後沒有觀光客的小鎮；多是小型家庭旅館，冬天有些會休息。',
    verify: true,
  },
  // ── 維也納 ──
  {
    id: 'stay-vie-1',
    wiki: 'en:Graben, Vienna',
    city: 'vienna',
    name: '1 區舊城',
    local: 'Innere Stadt',
    desc: '走路就到聖史蒂芬、歌劇院和各大市集，最方便也最貴。',
    map: 'Innere Stadt Wien',
  },
  {
    id: 'stay-vie-6-7',
    wiki: 'en:Mariahilfer Straße',
    city: 'vienna',
    name: '6、7 區',
    local: 'Mariahilf / Neubau',
    desc: '在 U3、U6 地鐵沿線，購物街和咖啡館多，價格比 1 區友善，離 Spittelberg 巷弄市集很近。',
    map: 'Neubau Wien',
  },
  {
    id: 'stay-vie-hbf',
    wiki: 'en:Wien Hauptbahnhof',
    city: 'vienna',
    name: '中央車站附近',
    local: 'Wien Hauptbahnhof',
    desc: '從布拉格坐火車到站就能 check-in，要去機場也最快。',
    map: 'Wien Hauptbahnhof',
  },
  // ── 薩爾斯堡 ──
  {
    id: 'stay-szg-old',
    wiki: 'en:Historic Centre of the City of Salzburg',
    city: 'salzburg',
    name: '舊城／河對岸新城',
    local: 'Altstadt / Linzer Gasse',
    desc: '舊城走路就到市集和要塞；隔一條河的新城（Linzer Gasse 一帶）便宜一些，過橋 5 分鐘。',
    map: 'Linzer Gasse Salzburg',
  },
  {
    id: 'stay-szg-hbf',
    wiki: 'en:Salzburg Hauptbahnhof',
    city: 'salzburg',
    name: '中央車站周邊',
    local: 'Salzburg Hbf',
    desc: '搭車去哈修塔特、維也納最方便，價格也比舊城好。',
    map: 'Salzburg Hauptbahnhof',
  },
  // ── 哈修塔特 ──
  {
    id: 'stay-hal-town',
    wiki: 'en:Hallstatt',
    city: 'hallstatt',
    name: '住哈修塔特鎮上',
    local: 'Hallstatt',
    desc: '房間少、價格高、很早就滿，但清晨沒有遊客的湖景只有住鎮上才看得到。',
    verify: true,
  },
  {
    id: 'stay-hal-near',
    wiki: 'en:Obertraun',
    city: 'hallstatt',
    name: '住附近小鎮',
    local: 'Obertraun / Bad Goisern / Bad Ischl',
    desc: '便宜很多，搭公車或火車 10–30 分鐘就到哈修塔特；也可以從薩爾斯堡當天來回。',
    verify: true,
  },
  // ── 斯德哥爾摩 ──
  {
    id: 'stay-sto-central',
    wiki: 'en:Stockholm Central Station',
    city: 'stockholm',
    name: '中央車站周邊',
    local: 'Norrmalm',
    desc: 'Arlanda Express 和北上的夜車都在中央車站，只待一兩晚住這裡最省事。',
    map: 'Stockholm Central Station',
  },
  {
    id: 'stay-sto-gamla',
    wiki: 'en:Gamla stan',
    city: 'stockholm',
    name: '老城 Gamla Stan',
    local: 'Gamla Stan',
    desc: '石板巷弄氣氛最好，離大廣場聖誕市集最近，但房間小又貴。',
    map: 'Gamla Stan',
  },
  {
    id: 'stay-sto-soder',
    wiki: 'en:Södermalm',
    city: 'stockholm',
    name: '南島 Södermalm',
    local: 'Södermalm',
    desc: '在地人住的區，餐廳和咖啡館多、價格比較友善，坐幾站地鐵就到市中心。',
    map: 'Södermalm',
  },
  // ── 阿比斯庫・基律納 ──
  {
    id: 'stay-lap-stf',
    wiki: 'sv:Abisko turiststation',
    city: 'lapland',
    name: 'STF 阿比斯庫山屋',
    local: 'STF Abisko Turiststation',
    desc: '極光站就在旁邊、有自己的火車站，是看極光最經典的據點。有飯店房、青旅床位和小木屋，冬天很早就客滿。',
    verify: true,
    links: [{ label: 'STF', url: 'https://www.swedishtouristassociation.com/facilities/stf-abisko-turiststation/' }],
  },
  {
    id: 'stay-lap-village',
    wiki: 'en:Abisko',
    city: 'lapland',
    name: '阿比斯庫村民宿／小木屋',
    local: 'Abisko Östra',
    desc: '村子裡有幾間民宿和小木屋，很多附廚房，可以自己煮省錢；離極光站大約 2 公里。',
    verify: true,
  },
  {
    id: 'stay-lap-icehotel',
    wiki: 'en:Icehotel (Jukkasjärvi)',
    city: 'lapland',
    name: '冰旅館 ICEHOTEL',
    local: 'Jukkasjärvi',
    desc: '建議只住一晚冰房（室溫約 -5°C，睡在鋪馴鹿皮的特製睡袋裡），其他晚上住暖房。ICEHOTEL 37 是 12/11 開幕，之前只有全年開的 ICEHOTEL 365 冰房。',
    event: 'icehotel',
    verify: true,
    links: [{ label: '官網', url: 'https://www.icehotel.com/' }],
  },
  {
    id: 'stay-lap-kiruna',
    wiki: 'en:Kiruna',
    city: 'lapland',
    name: '基律納市區',
    local: 'Kiruna',
    desc: '選擇最多、離機場近，適合當作跑狗拉雪橇、冰旅館的據點。火車站在市區外約 6 公里，有配合班次的免費接駁車。',
    map: 'Kiruna centrum',
  },
  // ── 納爾維克 ──
  {
    id: 'stay-nar-town',
    wiki: 'en:Narvik',
    city: 'narvik',
    name: '納爾維克市區',
    local: 'Narvik',
    desc: '夜車坐到終點站的話，可以住一晚看峽灣，隔天從 Evenes 機場飛奧斯陸轉機。',
  },
];

/** 全部參考項目，cat 由所在清單決定，避免漏寫 */
export const TRIP_GUIDE = [
  ...TRANSPORT.map((item) => ({ ...item, cat: 'move' })),
  ...SIGHTS.map((item) => ({ ...item, cat: 'fun' })),
  ...FOOD.map((item) => ({ ...item, cat: 'food' })),
  ...STAYS.map((item) => ({ ...item, cat: 'stay' })),
];
