/**
 * 英文基礎單字大全 —— 同樣依教學順序排列（100 天課程照這個順序發單字）。
 * 每筆格式：[英文, 音標, 中文, 詞性]
 */

export const EN_CATEGORIES = [
  {
    id: 'greeting',
    icon: '👋',
    name: '招呼與客套',
    words: [
      ['hello', '/həˈloʊ/', '你好', 'int.'],
      ['hi', '/haɪ/', '嗨', 'int.'],
      ['good morning', '/ɡʊd ˈmɔːrnɪŋ/', '早安', 'phr.'],
      ['good evening', '/ɡʊd ˈiːvnɪŋ/', '晚上好', 'phr.'],
      ['goodbye', '/ɡʊdˈbaɪ/', '再見', 'int.'],
      ['see you', '/siː juː/', '回頭見', 'phr.'],
      ['please', '/pliːz/', '請', 'adv.'],
      ['thank you', '/θæŋk juː/', '謝謝', 'phr.'],
      ['sorry', '/ˈsɑːri/', '對不起', 'adj.'],
      ['excuse me', '/ɪkˈskjuːz miː/', '不好意思（叫人／借過）', 'phr.'],
      ['yes', '/jes/', '是', 'adv.'],
      ['no', '/noʊ/', '不', 'adv.'],
      ['nice to meet you', '/naɪs tuː miːt juː/', '很高興認識你', 'phr.'],
      ['how are you', '/haʊ ɑːr juː/', '你好嗎', 'phr.'],
      ['I am fine', '/aɪ æm faɪn/', '我很好', 'phr.'],
      ['you are welcome', '/juː ɑːr ˈwelkəm/', '不客氣', 'phr.'],
      ['take care', '/teɪk ker/', '保重', 'phr.'],
      ['have a nice day', '/hæv ə naɪs deɪ/', '祝你有美好的一天', 'phr.'],
      ['my name is', '/maɪ neɪm ɪz/', '我的名字是', 'phr.'],
      ['cheers', '/tʃɪrz/', '乾杯／謝啦（英式）', 'int.'],
    ],
  },
  {
    id: 'basic',
    icon: '🙋',
    name: '代名詞與基本詞',
    words: [
      ['I', '/aɪ/', '我', 'pron.'],
      ['you', '/juː/', '你、你們', 'pron.'],
      ['he', '/hiː/', '他', 'pron.'],
      ['she', '/ʃiː/', '她', 'pron.'],
      ['it', '/ɪt/', '它', 'pron.'],
      ['we', '/wiː/', '我們', 'pron.'],
      ['they', '/ðeɪ/', '他們', 'pron.'],
      ['this', '/ðɪs/', '這個', 'pron.'],
      ['that', '/ðæt/', '那個', 'pron.'],
      ['these', '/ðiːz/', '這些', 'pron.'],
      ['those', '/ðoʊz/', '那些', 'pron.'],
      ['my', '/maɪ/', '我的', 'det.'],
      ['your', '/jʊr/', '你的', 'det.'],
      ['his', '/hɪz/', '他的', 'det.'],
      ['her', '/hɜːr/', '她的', 'det.'],
      ['our', '/ˈaʊər/', '我們的', 'det.'],
      ['there is', '/ðer ɪz/', '有（單數）', 'phr.'],
      ['there are', '/ðer ɑːr/', '有（複數）', 'phr.'],
    ],
  },
  {
    id: 'number',
    icon: '🔢',
    name: '數字與時間',
    words: [
      ['one', '/wʌn/', '一', 'num.'],
      ['two', '/tuː/', '二', 'num.'],
      ['three', '/θriː/', '三', 'num.'],
      ['four', '/fɔːr/', '四', 'num.'],
      ['five', '/faɪv/', '五', 'num.'],
      ['ten', '/ten/', '十', 'num.'],
      ['twenty', '/ˈtwenti/', '二十', 'num.'],
      ['hundred', '/ˈhʌndrəd/', '百', 'num.'],
      ['thousand', '/ˈθaʊznd/', '千', 'num.'],
      ['first', '/fɜːrst/', '第一', 'ord.'],
      ['second', '/ˈsekənd/', '第二／秒', 'ord.'],
      ['half', '/hæf/', '一半', 'n.'],
      ['hour', '/ˈaʊər/', '小時', 'n.'],
      ['minute', '/ˈmɪnɪt/', '分鐘', 'n.'],
      ['o’clock', '/əˈklɑːk/', '……點整', 'adv.'],
      ['quarter past', '/ˈkwɔːrtər pæst/', '……點十五分', 'phr.'],
      ['today', '/təˈdeɪ/', '今天', 'adv.'],
      ['tomorrow', '/təˈmɑːroʊ/', '明天', 'adv.'],
      ['yesterday', '/ˈjestərdeɪ/', '昨天', 'adv.'],
      ['tonight', '/təˈnaɪt/', '今晚', 'adv.'],
    ],
  },
  {
    id: 'calendar',
    icon: '📅',
    name: '星期與月份',
    words: [
      ['Monday', '/ˈmʌndeɪ/', '星期一', 'n.'],
      ['Tuesday', '/ˈtuːzdeɪ/', '星期二', 'n.'],
      ['Wednesday', '/ˈwenzdeɪ/', '星期三', 'n.'],
      ['Thursday', '/ˈθɜːrzdeɪ/', '星期四', 'n.'],
      ['Friday', '/ˈfraɪdeɪ/', '星期五', 'n.'],
      ['Saturday', '/ˈsætərdeɪ/', '星期六', 'n.'],
      ['Sunday', '/ˈsʌndeɪ/', '星期日', 'n.'],
      ['weekend', '/ˈwiːkend/', '週末', 'n.'],
      ['January', '/ˈdʒænjueri/', '一月', 'n.'],
      ['February', '/ˈfebrueri/', '二月', 'n.'],
      ['March', '/mɑːrtʃ/', '三月', 'n.'],
      ['April', '/ˈeɪprəl/', '四月', 'n.'],
      ['June', '/dʒuːn/', '六月', 'n.'],
      ['July', '/dʒuˈlaɪ/', '七月', 'n.'],
      ['August', '/ˈɔːɡəst/', '八月', 'n.'],
      ['September', '/sepˈtembər/', '九月', 'n.'],
      ['October', '/ɑːkˈtoʊbər/', '十月', 'n.'],
      ['December', '/dɪˈsembər/', '十二月', 'n.'],
      ['season', '/ˈsiːzn/', '季節', 'n.'],
    ],
  },
  {
    id: 'color',
    icon: '🎨',
    name: '顏色',
    words: [
      ['white', '/waɪt/', '白色', 'adj.'],
      ['black', '/blæk/', '黑色', 'adj.'],
      ['red', '/red/', '紅色', 'adj.'],
      ['blue', '/bluː/', '藍色', 'adj.'],
      ['green', '/ɡriːn/', '綠色', 'adj.'],
      ['yellow', '/ˈjeloʊ/', '黃色', 'adj.'],
      ['orange', '/ˈɔːrɪndʒ/', '橘色', 'adj.'],
      ['pink', '/pɪŋk/', '粉紅色', 'adj.'],
      ['purple', '/ˈpɜːrpl/', '紫色', 'adj.'],
      ['brown', '/braʊn/', '棕色', 'adj.'],
      ['grey', '/ɡreɪ/', '灰色', 'adj.'],
      ['bright', '/braɪt/', '明亮的', 'adj.'],
    ],
  },
  {
    id: 'family',
    icon: '👨‍👩‍👧',
    name: '家庭與人',
    words: [
      ['family', '/ˈfæməli/', '家庭', 'n.'],
      ['mother', '/ˈmʌðər/', '母親', 'n.'],
      ['father', '/ˈfɑːðər/', '父親', 'n.'],
      ['parents', '/ˈperənts/', '父母', 'n.'],
      ['brother', '/ˈbrʌðər/', '兄弟', 'n.'],
      ['sister', '/ˈsɪstər/', '姊妹', 'n.'],
      ['son', '/sʌn/', '兒子', 'n.'],
      ['daughter', '/ˈdɔːtər/', '女兒', 'n.'],
      ['grandmother', '/ˈɡrænmʌðər/', '祖母', 'n.'],
      ['husband', '/ˈhʌzbənd/', '丈夫', 'n.'],
      ['wife', '/waɪf/', '妻子', 'n.'],
      ['partner', '/ˈpɑːrtnər/', '伴侶', 'n.'],
      ['friend', '/frend/', '朋友', 'n.'],
      ['neighbour', '/ˈneɪbər/', '鄰居', 'n.'],
      ['child', '/tʃaɪld/', '小孩', 'n.'],
      ['adult', '/əˈdʌlt/', '成年人', 'n.'],
      ['roommate', '/ˈruːmmeɪt/', '室友', 'n.'],
      ['guest', '/ɡest/', '客人', 'n.'],
    ],
  },
  {
    id: 'body',
    icon: '🧍',
    name: '身體與健康',
    words: [
      ['body', '/ˈbɑːdi/', '身體', 'n.'],
      ['head', '/hed/', '頭', 'n.'],
      ['hair', '/her/', '頭髮', 'n.'],
      ['eye', '/aɪ/', '眼睛', 'n.'],
      ['ear', '/ɪr/', '耳朵', 'n.'],
      ['nose', '/noʊz/', '鼻子', 'n.'],
      ['mouth', '/maʊθ/', '嘴巴', 'n.'],
      ['tooth', '/tuːθ/', '牙齒（複 teeth）', 'n.'],
      ['throat', '/θroʊt/', '喉嚨', 'n.'],
      ['hand', '/hænd/', '手', 'n.'],
      ['leg', '/leɡ/', '腿', 'n.'],
      ['stomach', '/ˈstʌmək/', '胃、肚子', 'n.'],
      ['back', '/bæk/', '背', 'n.'],
      ['pain', '/peɪn/', '疼痛', 'n.'],
      ['fever', '/ˈfiːvər/', '發燒', 'n.'],
      ['cough', '/kɔːf/', '咳嗽', 'n./v.'],
      ['medicine', '/ˈmedɪsn/', '藥', 'n.'],
      ['doctor', '/ˈdɑːktər/', '醫生', 'n.'],
      ['appointment', '/əˈpɔɪntmənt/', '預約', 'n.'],
      ['insurance', '/ɪnˈʃʊrəns/', '保險', 'n.'],
    ],
  },
  {
    id: 'food',
    icon: '🍞',
    name: '食物與飲料',
    words: [
      ['food', '/fuːd/', '食物', 'n.'],
      ['breakfast', '/ˈbrekfəst/', '早餐', 'n.'],
      ['lunch', '/lʌntʃ/', '午餐', 'n.'],
      ['dinner', '/ˈdɪnər/', '晚餐', 'n.'],
      ['bread', '/bred/', '麵包', 'n.'],
      ['butter', '/ˈbʌtər/', '奶油', 'n.'],
      ['cheese', '/tʃiːz/', '起司', 'n.'],
      ['egg', '/eɡ/', '蛋', 'n.'],
      ['milk', '/mɪlk/', '牛奶', 'n.'],
      ['meat', '/miːt/', '肉', 'n.'],
      ['chicken', '/ˈtʃɪkɪn/', '雞肉', 'n.'],
      ['beef', '/biːf/', '牛肉', 'n.'],
      ['pork', '/pɔːrk/', '豬肉', 'n.'],
      ['fish', '/fɪʃ/', '魚', 'n.'],
      ['soup', '/suːp/', '湯', 'n.'],
      ['rice', '/raɪs/', '米飯', 'n.'],
      ['potato', '/pəˈteɪtoʊ/', '馬鈴薯', 'n.'],
      ['vegetable', '/ˈvedʒtəbl/', '蔬菜', 'n.'],
      ['fruit', '/fruːt/', '水果', 'n.'],
      ['apple', '/ˈæpl/', '蘋果', 'n.'],
      ['salt', '/sɔːlt/', '鹽', 'n.'],
      ['sugar', '/ˈʃʊɡər/', '糖', 'n.'],
      ['water', '/ˈwɔːtər/', '水', 'n.'],
      ['coffee', '/ˈkɔːfi/', '咖啡', 'n.'],
      ['beer', '/bɪr/', '啤酒', 'n.'],
      ['takeaway', '/ˈteɪkəweɪ/', '外帶（英式）', 'n.'],
    ],
  },
  {
    id: 'home',
    icon: '🏠',
    name: '住家',
    words: [
      ['house', '/haʊs/', '房子', 'n.'],
      ['flat', '/flæt/', '公寓（英式）', 'n.'],
      ['apartment', '/əˈpɑːrtmənt/', '公寓（美式）', 'n.'],
      ['room', '/ruːm/', '房間', 'n.'],
      ['kitchen', '/ˈkɪtʃɪn/', '廚房', 'n.'],
      ['bathroom', '/ˈbæθruːm/', '浴室', 'n.'],
      ['bedroom', '/ˈbedruːm/', '臥室', 'n.'],
      ['window', '/ˈwɪndoʊ/', '窗戶', 'n.'],
      ['door', '/dɔːr/', '門', 'n.'],
      ['table', '/ˈteɪbl/', '桌子', 'n.'],
      ['chair', '/tʃer/', '椅子', 'n.'],
      ['bed', '/bed/', '床', 'n.'],
      ['fridge', '/frɪdʒ/', '冰箱', 'n.'],
      ['heating', '/ˈhiːtɪŋ/', '暖氣', 'n.'],
      ['key', '/kiː/', '鑰匙', 'n.'],
      ['rent', '/rent/', '房租', 'n./v.'],
      ['landlord', '/ˈlændlɔːrd/', '房東', 'n.'],
      ['dormitory', '/ˈdɔːrmətɔːri/', '學生宿舍', 'n.'],
      ['laundry', '/ˈlɔːndri/', '洗衣', 'n.'],
      ['furniture', '/ˈfɜːrnɪtʃər/', '家具（不可數）', 'n.'],
    ],
  },
  {
    id: 'clothes',
    icon: '👕',
    name: '衣物',
    words: [
      ['clothes', '/kloʊz/', '衣服', 'n.'],
      ['shirt', '/ʃɜːrt/', '襯衫', 'n.'],
      ['T-shirt', '/ˈtiː ʃɜːrt/', 'T恤', 'n.'],
      ['trousers', '/ˈtraʊzərz/', '長褲（英式）', 'n.'],
      ['jeans', '/dʒiːnz/', '牛仔褲', 'n.'],
      ['skirt', '/skɜːrt/', '裙子', 'n.'],
      ['dress', '/dres/', '洋裝', 'n.'],
      ['jumper', '/ˈdʒʌmpər/', '毛衣（英式）', 'n.'],
      ['jacket', '/ˈdʒækɪt/', '外套', 'n.'],
      ['coat', '/koʊt/', '大衣', 'n.'],
      ['shoes', '/ʃuːz/', '鞋子', 'n.'],
      ['socks', '/sɑːks/', '襪子', 'n.'],
      ['scarf', '/skɑːrf/', '圍巾', 'n.'],
      ['gloves', '/ɡlʌvz/', '手套', 'n.'],
      ['backpack', '/ˈbækpæk/', '背包', 'n.'],
    ],
  },
  {
    id: 'city',
    icon: '🏙️',
    name: '城市與地點',
    words: [
      ['city', '/ˈsɪti/', '城市', 'n.'],
      ['town', '/taʊn/', '城鎮', 'n.'],
      ['street', '/striːt/', '街道', 'n.'],
      ['square', '/skwer/', '廣場', 'n.'],
      ['bridge', '/brɪdʒ/', '橋', 'n.'],
      ['park', '/pɑːrk/', '公園', 'n.'],
      ['shop', '/ʃɑːp/', '商店', 'n.'],
      ['supermarket', '/ˈsuːpərmɑːrkɪt/', '超市', 'n.'],
      ['bank', '/bæŋk/', '銀行', 'n.'],
      ['post office', '/poʊst ˈɔːfɪs/', '郵局', 'n.'],
      ['hospital', '/ˈhɑːspɪtl/', '醫院', 'n.'],
      ['pharmacy', '/ˈfɑːrməsi/', '藥局', 'n.'],
      ['church', '/tʃɜːrtʃ/', '教堂', 'n.'],
      ['castle', '/ˈkæsl/', '城堡', 'n.'],
      ['museum', '/mjuˈziːəm/', '博物館', 'n.'],
      ['cinema', '/ˈsɪnəmə/', '電影院', 'n.'],
      ['library', '/ˈlaɪbreri/', '圖書館', 'n.'],
      ['station', '/ˈsteɪʃn/', '車站', 'n.'],
      ['airport', '/ˈerpɔːrt/', '機場', 'n.'],
      ['toilet', '/ˈtɔɪlət/', '廁所（英式）', 'n.'],
    ],
  },
  {
    id: 'travel',
    icon: '✈️',
    name: '交通與旅行',
    words: [
      ['car', '/kɑːr/', '汽車', 'n.'],
      ['bus', '/bʌs/', '公車', 'n.'],
      ['tram', '/træm/', '路面電車', 'n.'],
      ['underground', '/ˈʌndərɡraʊnd/', '地鐵（英式）', 'n.'],
      ['train', '/treɪn/', '火車', 'n.'],
      ['bike', '/baɪk/', '腳踏車', 'n.'],
      ['plane', '/pleɪn/', '飛機', 'n.'],
      ['ticket', '/ˈtɪkɪt/', '票', 'n.'],
      ['platform', '/ˈplætfɔːrm/', '月台', 'n.'],
      ['departure', '/dɪˈpɑːrtʃər/', '出發', 'n.'],
      ['arrival', '/əˈraɪvl/', '抵達', 'n.'],
      ['delay', '/dɪˈleɪ/', '誤點', 'n./v.'],
      ['luggage', '/ˈlʌɡɪdʒ/', '行李（不可數）', 'n.'],
      ['passport', '/ˈpæspɔːrt/', '護照', 'n.'],
      ['boarding pass', '/ˈbɔːrdɪŋ pæs/', '登機證', 'n.'],
      ['gate', '/ɡeɪt/', '登機門', 'n.'],
      ['check in', '/tʃek ɪn/', '報到、入住', 'phr. v.'],
      ['book', '/bʊk/', '預訂', 'v.'],
      ['return ticket', '/rɪˈtɜːrn ˈtɪkɪt/', '來回票', 'n.'],
      ['single ticket', '/ˈsɪŋɡl ˈtɪkɪt/', '單程票', 'n.'],
      ['map', '/mæp/', '地圖', 'n.'],
      ['direction', '/dəˈrekʃn/', '方向', 'n.'],
    ],
  },
  {
    id: 'campus',
    icon: '🎓',
    name: '校園與學術',
    words: [
      ['university', '/ˌjuːnɪˈvɜːrsəti/', '大學', 'n.'],
      ['student', '/ˈstuːdnt/', '學生', 'n.'],
      ['lecturer', '/ˈlektʃərər/', '講師', 'n.'],
      ['course', '/kɔːrs/', '課程', 'n.'],
      ['lecture', '/ˈlektʃər/', '講堂課', 'n.'],
      ['seminar', '/ˈsemɪnɑːr/', '研討課', 'n.'],
      ['semester', '/sɪˈmestər/', '學期', 'n.'],
      ['timetable', '/ˈtaɪmteɪbl/', '課表', 'n.'],
      ['assignment', '/əˈsaɪnmənt/', '作業', 'n.'],
      ['essay', '/ˈeseɪ/', '小論文', 'n.'],
      ['deadline', '/ˈdedlaɪn/', '截止期限', 'n.'],
      ['exam', '/ɪɡˈzæm/', '考試', 'n.'],
      ['grade', '/ɡreɪd/', '成績', 'n.'],
      ['credit', '/ˈkredɪt/', '學分', 'n.'],
      ['degree', '/dɪˈɡriː/', '學位', 'n.'],
      ['research', '/ˈriːsɜːrtʃ/', '研究', 'n./v.'],
      ['reference', '/ˈrefrəns/', '參考文獻', 'n.'],
      ['citation', '/saɪˈteɪʃn/', '引用', 'n.'],
      ['abstract', '/ˈæbstrækt/', '摘要', 'n.'],
      ['presentation', '/ˌpriːzenˈteɪʃn/', '報告', 'n.'],
      ['group work', '/ɡruːp wɜːrk/', '分組作業', 'n.'],
      ['attendance', '/əˈtendəns/', '出席', 'n.'],
      ['tutorial', '/tuːˈtɔːriəl/', '輔導課', 'n.'],
      ['supervisor', '/ˈsuːpərvaɪzər/', '指導教授', 'n.'],
      ['enrolment', '/ɪnˈroʊlmənt/', '註冊', 'n.'],
      ['scholarship', '/ˈskɑːlərʃɪp/', '獎學金', 'n.'],
      ['campus', '/ˈkæmpəs/', '校園', 'n.'],
      ['exchange student', '/ɪksˈtʃeɪndʒ ˈstuːdnt/', '交換學生', 'n.'],
    ],
  },
  {
    id: 'job',
    icon: '💼',
    name: '職業與工作',
    words: [
      ['work', '/wɜːrk/', '工作', 'n./v.'],
      ['job', '/dʒɑːb/', '職位、工作', 'n.'],
      ['teacher', '/ˈtiːtʃər/', '老師', 'n.'],
      ['engineer', '/ˌendʒɪˈnɪr/', '工程師', 'n.'],
      ['nurse', '/nɜːrs/', '護理師', 'n.'],
      ['lawyer', '/ˈlɔːjər/', '律師', 'n.'],
      ['developer', '/dɪˈveləpər/', '開發者', 'n.'],
      ['manager', '/ˈmænɪdʒər/', '主管', 'n.'],
      ['colleague', '/ˈkɑːliːɡ/', '同事', 'n.'],
      ['salary', '/ˈsæləri/', '薪水', 'n.'],
      ['interview', '/ˈɪntərvjuː/', '面試', 'n.'],
      ['CV', '/ˌsiː ˈviː/', '履歷（歐洲用語）', 'n.'],
      ['internship', '/ˈɪntɜːrnʃɪp/', '實習', 'n.'],
      ['meeting', '/ˈmiːtɪŋ/', '會議', 'n.'],
    ],
  },
  {
    id: 'weather',
    icon: '🌦️',
    name: '天氣與自然',
    words: [
      ['weather', '/ˈweðər/', '天氣', 'n.'],
      ['sun', '/sʌn/', '太陽', 'n.'],
      ['rain', '/reɪn/', '雨', 'n./v.'],
      ['snow', '/snoʊ/', '雪', 'n./v.'],
      ['wind', '/wɪnd/', '風', 'n.'],
      ['cloud', '/klaʊd/', '雲', 'n.'],
      ['storm', '/stɔːrm/', '暴風雨', 'n.'],
      ['fog', '/fɔːɡ/', '霧', 'n.'],
      ['temperature', '/ˈtemprətʃər/', '溫度', 'n.'],
      ['degree', '/dɪˈɡriː/', '度', 'n.'],
      ['forecast', '/ˈfɔːrkæst/', '預報', 'n.'],
      ['tree', '/triː/', '樹', 'n.'],
      ['forest', '/ˈfɔːrɪst/', '森林', 'n.'],
      ['mountain', '/ˈmaʊntn/', '山', 'n.'],
      ['river', '/ˈrɪvər/', '河', 'n.'],
      ['lake', '/leɪk/', '湖', 'n.'],
      ['sea', '/siː/', '海', 'n.'],
      ['nature', '/ˈneɪtʃər/', '大自然', 'n.'],
    ],
  },
  {
    id: 'adjective',
    icon: '🔠',
    name: '常用形容詞',
    words: [
      ['good', '/ɡʊd/', '好的', 'adj.'],
      ['bad', '/bæd/', '壞的', 'adj.'],
      ['big', '/bɪɡ/', '大的', 'adj.'],
      ['small', '/smɔːl/', '小的', 'adj.'],
      ['new', '/nuː/', '新的', 'adj.'],
      ['old', '/oʊld/', '舊的、老的', 'adj.'],
      ['young', '/jʌŋ/', '年輕的', 'adj.'],
      ['long', '/lɔːŋ/', '長的', 'adj.'],
      ['short', '/ʃɔːrt/', '短的、矮的', 'adj.'],
      ['high', '/haɪ/', '高的', 'adj.'],
      ['fast', '/fæst/', '快的', 'adj.'],
      ['slow', '/sloʊ/', '慢的', 'adj.'],
      ['hot', '/hɑːt/', '熱的', 'adj.'],
      ['cold', '/koʊld/', '冷的', 'adj.'],
      ['expensive', '/ɪkˈspensɪv/', '昂貴的', 'adj.'],
      ['cheap', '/tʃiːp/', '便宜的', 'adj.'],
      ['difficult', '/ˈdɪfɪkəlt/', '困難的', 'adj.'],
      ['easy', '/ˈiːzi/', '容易的', 'adj.'],
      ['beautiful', '/ˈbjuːtɪfl/', '美麗的', 'adj.'],
      ['clean', '/kliːn/', '乾淨的', 'adj.'],
      ['dirty', '/ˈdɜːrti/', '髒的', 'adj.'],
      ['full', '/fʊl/', '滿的', 'adj.'],
      ['empty', '/ˈempti/', '空的', 'adj.'],
      ['happy', '/ˈhæpi/', '快樂的', 'adj.'],
      ['sad', '/sæd/', '難過的', 'adj.'],
      ['tired', '/ˈtaɪərd/', '疲倦的', 'adj.'],
      ['busy', '/ˈbɪzi/', '忙碌的', 'adj.'],
      ['important', '/ɪmˈpɔːrtnt/', '重要的', 'adj.'],
      ['interesting', '/ˈɪntrəstɪŋ/', '有趣的', 'adj.'],
      ['available', '/əˈveɪləbl/', '可用的、有空的', 'adj.'],
    ],
  },
  {
    id: 'verb',
    icon: '🏃',
    name: '常用動詞',
    words: [
      ['be', '/biː/', '是（am／is／are）', 'v.'],
      ['have', '/hæv/', '有', 'v.'],
      ['do', '/duː/', '做', 'v.'],
      ['go', '/ɡoʊ/', '去', 'v.'],
      ['come', '/kʌm/', '來', 'v.'],
      ['get', '/ɡet/', '得到、變成', 'v.'],
      ['make', '/meɪk/', '製作、使得', 'v.'],
      ['take', '/teɪk/', '拿、搭乘、花費', 'v.'],
      ['give', '/ɡɪv/', '給', 'v.'],
      ['see', '/siː/', '看見', 'v.'],
      ['hear', '/hɪr/', '聽見', 'v.'],
      ['say', '/seɪ/', '說（內容）', 'v.'],
      ['tell', '/tel/', '告訴（某人）', 'v.'],
      ['speak', '/spiːk/', '說（語言）', 'v.'],
      ['ask', '/æsk/', '問、要求', 'v.'],
      ['answer', '/ˈænsər/', '回答', 'v.'],
      ['know', '/noʊ/', '知道', 'v.'],
      ['think', '/θɪŋk/', '想、認為', 'v.'],
      ['want', '/wɑːnt/', '想要', 'v.'],
      ['need', '/niːd/', '需要', 'v.'],
      ['like', '/laɪk/', '喜歡', 'v.'],
      ['eat', '/iːt/', '吃', 'v.'],
      ['drink', '/drɪŋk/', '喝', 'v.'],
      ['sleep', '/sliːp/', '睡', 'v.'],
      ['buy', '/baɪ/', '買', 'v.'],
      ['pay', '/peɪ/', '付錢', 'v.'],
      ['read', '/riːd/', '讀', 'v.'],
      ['write', '/raɪt/', '寫', 'v.'],
      ['learn', '/lɜːrn/', '學', 'v.'],
      ['study', '/ˈstʌdi/', '研讀', 'v.'],
      ['live', '/lɪv/', '居住、生活', 'v.'],
      ['stay', '/steɪ/', '停留', 'v.'],
      ['wait', '/weɪt/', '等待', 'v.'],
      ['find', '/faɪnd/', '找到', 'v.'],
      ['lose', '/luːz/', '遺失、輸', 'v.'],
      ['help', '/help/', '幫助', 'v.'],
      ['start', '/stɑːrt/', '開始', 'v.'],
      ['finish', '/ˈfɪnɪʃ/', '完成', 'v.'],
      ['open', '/ˈoʊpən/', '打開', 'v.'],
      ['close', '/kloʊz/', '關上', 'v.'],
    ],
  },
  {
    id: 'phrasal',
    icon: '🧩',
    name: '常用片語動詞',
    words: [
      ['pick up', '/pɪk ʌp/', '接（人）、拿取、學會', 'phr. v.'],
      ['drop off', '/drɑːp ɔːf/', '放下、送達', 'phr. v.'],
      ['give up', '/ɡɪv ʌp/', '放棄', 'phr. v.'],
      ['look for', '/lʊk fɔːr/', '尋找', 'phr. v.'],
      ['look after', '/lʊk ˈæftər/', '照顧', 'phr. v.'],
      ['find out', '/faɪnd aʊt/', '查明', 'phr. v.'],
      ['work out', '/wɜːrk aʊt/', '運動、想出來、順利發展', 'phr. v.'],
      ['turn on', '/tɜːrn ɑːn/', '打開（電器）', 'phr. v.'],
      ['turn off', '/tɜːrn ɔːf/', '關掉', 'phr. v.'],
      ['put off', '/pʊt ɔːf/', '延後', 'phr. v.'],
      ['set up', '/set ʌp/', '設立、安排', 'phr. v.'],
      ['come across', '/kʌm əˈkrɔːs/', '偶然遇到', 'phr. v.'],
      ['get on with', '/ɡet ɑːn wɪð/', '與人相處、繼續做', 'phr. v.'],
      ['run out of', '/rʌn aʊt əv/', '用完', 'phr. v.'],
      ['sign up for', '/saɪn ʌp fɔːr/', '報名參加', 'phr. v.'],
      ['fill in', '/fɪl ɪn/', '填寫（表格）', 'phr. v.'],
      ['hand in', '/hænd ɪn/', '繳交', 'phr. v.'],
      ['catch up on', '/kætʃ ʌp ɑːn/', '補進度', 'phr. v.'],
      ['end up', '/end ʌp/', '最後變成', 'phr. v.'],
      ['show up', '/ʃoʊ ʌp/', '出現、到場', 'phr. v.'],
    ],
  },
  {
    id: 'connector',
    icon: '🔗',
    name: '連接詞與副詞',
    words: [
      ['and', '/ænd/', '和', 'conj.'],
      ['but', '/bʌt/', '但是', 'conj.'],
      ['or', '/ɔːr/', '或者', 'conj.'],
      ['because', '/bɪˈkɔːz/', '因為', 'conj.'],
      ['so', '/soʊ/', '所以', 'conj.'],
      ['if', '/ɪf/', '如果', 'conj.'],
      ['when', '/wen/', '當……時', 'conj.'],
      ['although', '/ɔːlˈðoʊ/', '雖然', 'conj.'],
      ['however', '/haʊˈevər/', '然而', 'adv.'],
      ['therefore', '/ˈðerfɔːr/', '因此', 'adv.'],
      ['also', '/ˈɔːlsoʊ/', '也', 'adv.'],
      ['already', '/ɔːlˈredi/', '已經', 'adv.'],
      ['still', '/stɪl/', '仍然', 'adv.'],
      ['just', '/dʒʌst/', '剛剛、只是', 'adv.'],
      ['always', '/ˈɔːlweɪz/', '總是', 'adv.'],
      ['usually', '/ˈjuːʒuəli/', '通常', 'adv.'],
      ['sometimes', '/ˈsʌmtaɪmz/', '有時候', 'adv.'],
      ['never', '/ˈnevər/', '從不', 'adv.'],
      ['maybe', '/ˈmeɪbi/', '也許', 'adv.'],
      ['probably', '/ˈprɑːbəbli/', '很可能', 'adv.'],
    ],
  },
  {
    id: 'money',
    icon: '💳',
    name: '金錢與購物',
    words: [
      ['money', '/ˈmʌni/', '錢', 'n.'],
      ['price', '/praɪs/', '價格', 'n.'],
      ['cash', '/kæʃ/', '現金', 'n.'],
      ['card', '/kɑːrd/', '卡片', 'n.'],
      ['receipt', '/rɪˈsiːt/', '收據', 'n.'],
      ['discount', '/ˈdɪskaʊnt/', '折扣', 'n.'],
      ['sale', '/seɪl/', '特價', 'n.'],
      ['free', '/friː/', '免費的', 'adj.'],
      ['bill', '/bɪl/', '帳單', 'n.'],
      ['fee', '/fiː/', '費用', 'n.'],
      ['refund', '/ˈriːfʌnd/', '退款', 'n.'],
      ['budget', '/ˈbʌdʒɪt/', '預算', 'n.'],
      ['exchange rate', '/ɪksˈtʃeɪndʒ reɪt/', '匯率', 'n.'],
      ['withdraw', '/wɪðˈdrɔː/', '提領', 'v.'],
      ['transfer', '/ˈtrænsfɜːr/', '轉帳', 'n./v.'],
      ['size', '/saɪz/', '尺寸', 'n.'],
    ],
  },
  {
    id: 'tech',
    icon: '📱',
    name: '科技與網路',
    words: [
      ['phone', '/foʊn/', '電話、手機', 'n.'],
      ['laptop', '/ˈlæptɑːp/', '筆電', 'n.'],
      ['screen', '/skriːn/', '螢幕', 'n.'],
      ['charger', '/ˈtʃɑːrdʒər/', '充電器', 'n.'],
      ['password', '/ˈpæswɜːrd/', '密碼', 'n.'],
      ['email', '/ˈiːmeɪl/', '電子郵件', 'n.'],
      ['file', '/faɪl/', '檔案', 'n.'],
      ['folder', '/ˈfoʊldər/', '資料夾', 'n.'],
      ['download', '/ˈdaʊnloʊd/', '下載', 'v.'],
      ['upload', '/ˈʌploʊd/', '上傳', 'v.'],
      ['update', '/ʌpˈdeɪt/', '更新', 'v.'],
      ['app', '/æp/', '應用程式', 'n.'],
      ['link', '/lɪŋk/', '連結', 'n.'],
      ['account', '/əˈkaʊnt/', '帳號、帳戶', 'n.'],
      ['settings', '/ˈsetɪŋz/', '設定', 'n.'],
    ],
  },
  {
    id: 'feeling',
    icon: '💗',
    name: '情緒與個性',
    words: [
      ['feel', '/fiːl/', '感覺', 'v.'],
      ['excited', '/ɪkˈsaɪtɪd/', '興奮的', 'adj.'],
      ['nervous', '/ˈnɜːrvəs/', '緊張的', 'adj.'],
      ['worried', '/ˈwɜːrid/', '擔心的', 'adj.'],
      ['angry', '/ˈæŋɡri/', '生氣的', 'adj.'],
      ['bored', '/bɔːrd/', '覺得無聊的', 'adj.'],
      ['confused', '/kənˈfjuːzd/', '困惑的', 'adj.'],
      ['confident', '/ˈkɑːnfɪdənt/', '有自信的', 'adj.'],
      ['friendly', '/ˈfrendli/', '友善的', 'adj.'],
      ['kind', '/kaɪnd/', '親切的', 'adj.'],
      ['shy', '/ʃaɪ/', '害羞的', 'adj.'],
      ['polite', '/pəˈlaɪt/', '有禮貌的', 'adj.'],
      ['patient', '/ˈpeɪʃnt/', '有耐心的', 'adj.'],
      ['lazy', '/ˈleɪzi/', '懶惰的', 'adj.'],
      ['proud', '/praʊd/', '驕傲的、自豪的', 'adj.'],
      ['grateful', '/ˈɡreɪtfl/', '感激的', 'adj.'],
    ],
  },
  {
    id: 'admin',
    icon: '📄',
    name: '行政與文件',
    words: [
      ['form', '/fɔːrm/', '表格', 'n.'],
      ['document', '/ˈdɑːkjumənt/', '文件', 'n.'],
      ['signature', '/ˈsɪɡnətʃər/', '簽名', 'n.'],
      ['stamp', '/stæmp/', '印章、郵票', 'n.'],
      ['visa', '/ˈviːzə/', '簽證', 'n.'],
      ['permit', '/ˈpɜːrmɪt/', '許可證', 'n.'],
      ['registration', '/ˌredʒɪˈstreɪʃn/', '登記、註冊', 'n.'],
      ['certificate', '/sərˈtɪfɪkət/', '證明書', 'n.'],
      ['deadline', '/ˈdedlaɪn/', '期限', 'n.'],
      ['apply for', '/əˈplaɪ fɔːr/', '申請', 'phr. v.'],
      ['confirm', '/kənˈfɜːrm/', '確認', 'v.'],
      ['submit', '/səbˈmɪt/', '提交', 'v.'],
      ['attach', '/əˈtætʃ/', '附加', 'v.'],
      ['approve', '/əˈpruːv/', '核准', 'v.'],
      ['valid', '/ˈvælɪd/', '有效的', 'adj.'],
    ],
  },
  {
    id: 'social',
    icon: '💬',
    name: '社交口語',
    words: [
      ['of course', '/əv kɔːrs/', '當然', 'phr.'],
      ['no problem', '/noʊ ˈprɑːbləm/', '沒問題', 'phr.'],
      ['never mind', '/ˈnevər maɪnd/', '別在意', 'phr.'],
      ['I see', '/aɪ siː/', '我懂了', 'phr.'],
      ['that makes sense', '/ðæt meɪks sens/', '這樣說得通', 'phr.'],
      ['fair enough', '/fer ɪˈnʌf/', '有道理、可以接受', 'phr.'],
      ['to be honest', '/tuː biː ˈɑːnɪst/', '老實說', 'phr.'],
      ['by the way', '/baɪ ðə weɪ/', '順帶一提', 'phr.'],
      ['as far as I know', '/æz fɑːr æz aɪ noʊ/', '就我所知', 'phr.'],
      ['let me check', '/let miː tʃek/', '我確認一下', 'phr.'],
      ['hang on', '/hæŋ ɑːn/', '等一下', 'phr.'],
      ['sounds good', '/saʊndz ɡʊd/', '聽起來不錯', 'phr.'],
      ['I am not sure', '/aɪ æm nɑːt ʃʊr/', '我不確定', 'phr.'],
      ['it depends', '/ɪt dɪˈpendz/', '看情況', 'phr.'],
      ['what do you mean', '/wʌt duː juː miːn/', '你是什麼意思', 'phr.'],
      ['could you repeat that', '/kʊd juː rɪˈpiːt ðæt/', '可以再說一次嗎', 'phr.'],
      ['speak up', '/spiːk ʌp/', '大聲一點、說出想法', 'phr. v.'],
      ['I would rather', '/aɪ wʊd ˈræðər/', '我寧願', 'phr.'],
      ['do you mind if', '/duː juː maɪnd ɪf/', '你介意我……嗎', 'phr.'],
      ['see you around', '/siː juː əˈraʊnd/', '再見囉', 'phr.'],
    ],
  },
];

function slug(text) {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

export const EN_VOCAB = EN_CATEGORIES.flatMap((category) =>
  category.words.map(([term, pron, zh, pos]) => ({
    id: `en-v-${category.id}-${slug(term)}`,
    lang: 'en',
    term,
    pron,
    zh,
    pos: pos || '',
    cat: category.name,
    catId: category.id,
  })),
);
