/**
 * 捷克文基礎單字大全 —— 依「教學順序」排列的分類清單。
 * 100 天課程也是照這個順序發單字，所以順序＝由淺入深，不要隨意調動。
 *
 * 每筆格式：[捷克文, 拼讀（重音在第一音節）, 中文, 詞性／性別]
 *   m = 陽性、f = 陰性、n = 中性、pl = 複數
 */

export const CZ_CATEGORIES = [
  {
    id: 'greeting',
    icon: '👋',
    name: '招呼與禮貌',
    words: [
      ['ahoj', 'A-hoy', '嗨／掰掰（朋友）', '感嘆'],
      ['čau', 'chau', '嗨／掰（更隨性）', '感嘆'],
      ['dobrý den', 'DOB-ree den', '您好（白天正式）', '片語'],
      ['dobré ráno', 'DOB-ree RAA-no', '早安', '片語'],
      ['dobrý večer', 'DOB-ree VE-cher', '晚上好', '片語'],
      ['dobrou noc', 'DOB-rou nots', '晚安（睡前）', '片語'],
      ['na shledanou', 'na SKHLE-da-nou', '再見（正式）', '片語'],
      ['děkuji', 'DYE-ku-yi', '謝謝', '動詞'],
      ['díky', 'DYEE-ki', '謝啦', '感嘆'],
      ['prosím', 'PRO-seem', '請／不客氣／你說什麼', '副詞'],
      ['promiňte', 'PRO-min-tye', '不好意思（正式）', '動詞'],
      ['pardon', 'PAR-don', '借過、抱歉', '感嘆'],
      ['ano', 'A-no', '是', '副詞'],
      ['ne', 'ne', '不', '副詞'],
      ['jo', 'yo', '嗯（口語的是）', '副詞'],
      ['není zač', 'NE-nyee zach', '不客氣', '片語'],
      ['těší mě', 'TYE-shee mnye', '幸會', '片語'],
      ['na zdraví', 'na ZDRA-vee', '乾杯！', '片語'],
      ['dobrou chuť', 'DOB-rou khut', '用餐愉快', '片語'],
      ['jak se máš', 'yak se maash', '你好嗎（朋友）', '片語'],
      ['mám se dobře', 'maam se DOB-rzhe', '我很好', '片語'],
      ['jmenuji se', 'YME-nu-yi se', '我叫……', '片語'],
      ['mějte se', 'MYEY-te se', '保重', '片語'],
      ['hezký den', 'HEZ-kee den', '祝你有美好的一天', '片語'],
      ['omlouvám se', 'OM-lou-vaam se', '我道歉', '片語'],
    ],
  },
  {
    id: 'pronoun',
    icon: '🙋',
    name: '人稱與指示詞',
    words: [
      ['já', 'yaa', '我', '代名詞'],
      ['ty', 'ti', '你', '代名詞'],
      ['on', 'on', '他', '代名詞'],
      ['ona', 'O-na', '她', '代名詞'],
      ['ono', 'O-no', '它', '代名詞'],
      ['my', 'mi', '我們', '代名詞'],
      ['vy', 'vi', '你們／您', '代名詞'],
      ['oni', 'O-nyi', '他們', '代名詞'],
      ['to', 'to', '這個、那個（萬用）', '代名詞'],
      ['tohle', 'TO-hle', '這個', '代名詞'],
      ['tamto', 'TAM-to', '那個', '代名詞'],
      ['můj', 'mooy', '我的', '代名詞'],
      ['tvůj', 'tvooy', '你的', '代名詞'],
      ['náš', 'naash', '我們的', '代名詞'],
      ['váš', 'vaash', '你們的／您的', '代名詞'],
      ['jeho', 'YE-ho', '他的', '代名詞'],
      ['její', 'YE-yee', '她的', '代名詞'],
      ['sám', 'saam', '自己、獨自', '形容詞'],
      ['každý', 'KAZH-dee', '每一個', '代名詞'],
      ['někdo', 'NYEK-do', '某人', '代名詞'],
      ['nikdo', 'NYIK-do', '沒有人', '代名詞'],
      ['něco', 'NYE-tso', '某物', '代名詞'],
      ['nic', 'nyits', '什麼都沒有', '代名詞'],
      ['všechno', 'VSHEKH-no', '全部', '代名詞'],
    ],
  },
  {
    id: 'number',
    icon: '🔢',
    name: '數字',
    words: [
      ['nula', 'NU-la', '零', '數詞'],
      ['jeden / jedna', 'YE-den / YED-na', '一（陽／陰）', '數詞'],
      ['dva / dvě', 'dva / dvye', '二（陽／陰中）', '數詞'],
      ['tři', 'trzhi', '三', '數詞'],
      ['čtyři', 'CHTI-rzhi', '四', '數詞'],
      ['pět', 'pyet', '五', '數詞'],
      ['šest', 'shest', '六', '數詞'],
      ['sedm', 'SE-dum', '七', '數詞'],
      ['osm', 'O-sum', '八', '數詞'],
      ['devět', 'DE-vyet', '九', '數詞'],
      ['deset', 'DE-set', '十', '數詞'],
      ['jedenáct', 'YE-de-naatst', '十一', '數詞'],
      ['dvanáct', 'DVA-naatst', '十二', '數詞'],
      ['třináct', 'TRZHI-naatst', '十三', '數詞'],
      ['čtrnáct', 'CHTR-naatst', '十四', '數詞'],
      ['patnáct', 'PAT-naatst', '十五', '數詞'],
      ['šestnáct', 'SHEST-naatst', '十六', '數詞'],
      ['sedmnáct', 'SE-dum-naatst', '十七', '數詞'],
      ['osmnáct', 'O-sum-naatst', '十八', '數詞'],
      ['devatenáct', 'DE-va-te-naatst', '十九', '數詞'],
      ['dvacet', 'DVA-tset', '二十', '數詞'],
      ['třicet', 'TRZHI-tset', '三十', '數詞'],
      ['čtyřicet', 'CHTI-rzhi-tset', '四十', '數詞'],
      ['padesát', 'PA-de-saat', '五十', '數詞'],
      ['sto', 'sto', '一百', '數詞'],
      ['tisíc', 'TYI-seets', '一千', '數詞'],
      ['první', 'PRV-nyee', '第一', '序數'],
      ['druhý', 'DRU-hee', '第二', '序數'],
      ['třetí', 'TRZHE-tyee', '第三', '序數'],
      ['půl', 'pool', '一半', '名詞'],
    ],
  },
  {
    id: 'time',
    icon: '🕐',
    name: '時間',
    words: [
      ['čas', 'chas', '時間', 'm'],
      ['hodina', 'HO-dyi-na', '小時、鐘點', 'f'],
      ['minuta', 'MI-nu-ta', '分鐘', 'f'],
      ['den', 'den', '天、白天', 'm'],
      ['týden', 'TEE-den', '週', 'm'],
      ['měsíc', 'MYE-seets', '月／月亮', 'm'],
      ['rok', 'rok', '年', 'm'],
      ['dnes', 'dnes', '今天', '副詞'],
      ['zítra', 'ZEE-tra', '明天', '副詞'],
      ['včera', 'VCHE-ra', '昨天', '副詞'],
      ['ráno', 'RAA-no', '早上', 'n'],
      ['dopoledne', 'DO-po-led-ne', '上午', 'n'],
      ['poledne', 'PO-led-ne', '中午', 'n'],
      ['odpoledne', 'OD-po-led-ne', '下午', 'n'],
      ['večer', 'VE-cher', '晚上', 'm'],
      ['noc', 'nots', '夜晚', 'f'],
      ['víkend', 'VEE-kend', '週末', 'm'],
      ['teď', 'tedy', '現在', '副詞'],
      ['hned', 'hned', '馬上', '副詞'],
      ['brzy', 'BR-zi', '早、快', '副詞'],
      ['pozdě', 'POZ-dye', '晚、遲', '副詞'],
      ['pořád', 'PO-rzhaad', '一直', '副詞'],
      ['zatím', 'ZA-tyeem', '目前為止', '副詞'],
      ['potom', 'PO-tom', '之後', '副詞'],
    ],
  },
  {
    id: 'weekday',
    icon: '📅',
    name: '星期與月份',
    words: [
      ['pondělí', 'PON-dye-lee', '星期一', 'n'],
      ['úterý', 'OO-te-ree', '星期二', 'n'],
      ['středa', 'STRZHE-da', '星期三', 'f'],
      ['čtvrtek', 'CHTVR-tek', '星期四', 'm'],
      ['pátek', 'PAA-tek', '星期五', 'm'],
      ['sobota', 'SO-bo-ta', '星期六', 'f'],
      ['neděle', 'NE-dye-le', '星期日', 'f'],
      ['leden', 'LE-den', '一月', 'm'],
      ['únor', 'OO-nor', '二月', 'm'],
      ['březen', 'BRZHE-zen', '三月', 'm'],
      ['duben', 'DU-ben', '四月', 'm'],
      ['květen', 'KVYE-ten', '五月', 'm'],
      ['červen', 'CHER-ven', '六月', 'm'],
      ['červenec', 'CHER-ve-nets', '七月', 'm'],
      ['srpen', 'SR-pen', '八月', 'm'],
      ['září', 'ZAA-rzhee', '九月', 'n'],
      ['říjen', 'RZHEE-yen', '十月', 'm'],
      ['listopad', 'LIS-to-pad', '十一月', 'm'],
      ['prosinec', 'PRO-si-nets', '十二月', 'm'],
      ['jaro', 'YA-ro', '春天', 'n'],
      ['léto', 'LEE-to', '夏天', 'n'],
      ['podzim', 'POD-zim', '秋天', 'm'],
      ['zima', 'ZI-ma', '冬天／寒冷', 'f'],
    ],
  },
  {
    id: 'color',
    icon: '🎨',
    name: '顏色',
    words: [
      ['barva', 'BAR-va', '顏色', 'f'],
      ['bílý', 'BEE-lee', '白色的', '形容詞'],
      ['černý', 'CHER-nee', '黑色的', '形容詞'],
      ['červený', 'CHER-ve-nee', '紅色的', '形容詞'],
      ['modrý', 'MOD-ree', '藍色的', '形容詞'],
      ['zelený', 'ZE-le-nee', '綠色的', '形容詞'],
      ['žlutý', 'ZHLU-tee', '黃色的', '形容詞'],
      ['oranžový', 'O-ran-zho-vee', '橘色的', '形容詞'],
      ['růžový', 'ROO-zho-vee', '粉紅色的', '形容詞'],
      ['fialový', 'FI-a-lo-vee', '紫色的', '形容詞'],
      ['hnědý', 'HNYE-dee', '棕色的', '形容詞'],
      ['šedý', 'SHE-dee', '灰色的', '形容詞'],
      ['zlatý', 'ZLA-tee', '金色的', '形容詞'],
      ['světlý', 'SVYET-lee', '淺色的、明亮的', '形容詞'],
      ['tmavý', 'TMA-vee', '深色的、暗的', '形容詞'],
    ],
  },
  {
    id: 'family',
    icon: '👨‍👩‍👧',
    name: '家庭與人',
    words: [
      ['rodina', 'RO-dyi-na', '家庭', 'f'],
      ['máma', 'MAA-ma', '媽媽', 'f'],
      ['táta', 'TAA-ta', '爸爸', 'm'],
      ['matka', 'MAT-ka', '母親（正式）', 'f'],
      ['otec', 'O-tets', '父親（正式）', 'm'],
      ['bratr', 'BRA-tr', '哥哥／弟弟', 'm'],
      ['sestra', 'SES-tra', '姊姊／妹妹', 'f'],
      ['syn', 'sin', '兒子', 'm'],
      ['dcera', 'DTSE-ra', '女兒', 'f'],
      ['babička', 'BA-bich-ka', '奶奶', 'f'],
      ['dědeček', 'DYE-de-chek', '爺爺', 'm'],
      ['manžel', 'MAN-zhel', '丈夫', 'm'],
      ['manželka', 'MAN-zhel-ka', '妻子', 'f'],
      ['přítel', 'PRZHEE-tel', '男朋友／朋友', 'm'],
      ['přítelkyně', 'PRZHEE-tel-ki-nye', '女朋友', 'f'],
      ['kamarád', 'KA-ma-raad', '朋友', 'm'],
      ['dítě', 'DYEE-tye', '小孩', 'n'],
      ['muž', 'muzh', '男人', 'm'],
      ['žena', 'ZHE-na', '女人', 'f'],
      ['kluk', 'kluk', '男孩', 'm'],
      ['holka', 'HOL-ka', '女孩', 'f'],
      ['lidé', 'LI-dee', '人們', 'pl'],
      ['soused', 'SOU-sed', '鄰居', 'm'],
      ['host', 'host', '客人', 'm'],
    ],
  },
  {
    id: 'body',
    icon: '🧍',
    name: '身體',
    words: [
      ['tělo', 'TYE-lo', '身體', 'n'],
      ['hlava', 'HLA-va', '頭', 'f'],
      ['vlasy', 'VLA-si', '頭髮', 'pl'],
      ['oko', 'O-ko', '眼睛', 'n'],
      ['ucho', 'U-kho', '耳朵', 'n'],
      ['nos', 'nos', '鼻子', 'm'],
      ['ústa', 'OOS-ta', '嘴巴', 'pl'],
      ['zub', 'zub', '牙齒', 'm'],
      ['jazyk', 'YA-zik', '舌頭／語言', 'm'],
      ['krk', 'krk', '脖子、喉嚨', 'm'],
      ['rameno', 'RA-me-no', '肩膀', 'n'],
      ['ruka', 'RU-ka', '手、手臂', 'f'],
      ['prst', 'prst', '手指', 'm'],
      ['břicho', 'BRZHI-kho', '肚子', 'n'],
      ['záda', 'ZAA-da', '背', 'pl'],
      ['noha', 'NO-ha', '腳、腿', 'f'],
      ['koleno', 'KO-le-no', '膝蓋', 'n'],
      ['srdce', 'SRD-tse', '心臟', 'n'],
      ['kůže', 'KOO-zhe', '皮膚', 'f'],
      ['krev', 'krev', '血', 'f'],
    ],
  },
  {
    id: 'food',
    icon: '🍞',
    name: '食物',
    words: [
      ['jídlo', 'YEED-lo', '食物、餐', 'n'],
      ['snídaně', 'SNYEE-da-nye', '早餐', 'f'],
      ['oběd', 'O-byed', '午餐', 'm'],
      ['večeře', 'VE-che-rzhe', '晚餐', 'f'],
      ['chléb', 'khleeb', '麵包', 'm'],
      ['rohlík', 'RO-hleek', '捷克小圓麵包', 'm'],
      ['máslo', 'MAAS-lo', '奶油', 'n'],
      ['sýr', 'seer', '起司', 'm'],
      ['vejce', 'VEY-tse', '蛋', 'n'],
      ['mléko', 'MLEE-ko', '牛奶', 'n'],
      ['maso', 'MA-so', '肉', 'n'],
      ['kuře', 'KU-rzhe', '雞肉', 'n'],
      ['vepřové', 'VEP-rzho-vee', '豬肉', 'n'],
      ['hovězí', 'HO-vye-zee', '牛肉', 'n'],
      ['ryba', 'RI-ba', '魚', 'f'],
      ['šunka', 'SHUN-ka', '火腿', 'f'],
      ['polévka', 'PO-leev-ka', '湯', 'f'],
      ['knedlík', 'KNED-leek', '捷克麵團餃（配醬汁）', 'm'],
      ['brambory', 'BRAM-bo-ri', '馬鈴薯', 'pl'],
      ['rýže', 'REE-zhe', '米飯', 'f'],
      ['těstoviny', 'TYES-to-vi-ni', '義大利麵', 'pl'],
      ['sůl', 'sool', '鹽', 'f'],
      ['cukr', 'TSU-kr', '糖', 'm'],
      ['pepř', 'peprzh', '胡椒', 'm'],
      ['olej', 'O-ley', '油', 'm'],
      ['med', 'med', '蜂蜜', 'm'],
      ['čokoláda', 'CHO-ko-laa-da', '巧克力', 'f'],
      ['dort', 'dort', '蛋糕', 'm'],
      ['zmrzlina', 'ZMRZ-li-na', '冰淇淋', 'f'],
      ['guláš', 'GU-laash', '燉牛肉（國民菜）', 'm'],
      ['svíčková', 'SVEECH-ko-vaa', '奶油醬燉牛肉（國菜）', 'f'],
      ['smažený sýr', 'SMA-zhe-nee seer', '炸起司', 'm'],
    ],
  },
  {
    id: 'drink',
    icon: '🍺',
    name: '飲料',
    words: [
      ['pití', 'PI-tyee', '飲料', 'n'],
      ['voda', 'VO-da', '水', 'f'],
      ['perlivá voda', 'PER-li-vaa VO-da', '氣泡水', 'f'],
      ['neperlivá voda', 'NE-per-li-vaa VO-da', '無氣泡水', 'f'],
      ['čaj', 'chay', '茶', 'm'],
      ['káva', 'KAA-va', '咖啡', 'f'],
      ['pivo', 'PI-vo', '啤酒', 'n'],
      ['víno', 'VEE-no', '葡萄酒', 'n'],
      ['džus', 'dzhus', '果汁', 'm'],
      ['limonáda', 'LI-mo-naa-da', '汽水', 'f'],
      ['mléko', 'MLEE-ko', '牛奶', 'n'],
      ['sklenice', 'SKLE-nyi-tse', '玻璃杯', 'f'],
      ['láhev', 'LAA-hev', '瓶子', 'f'],
      ['led', 'led', '冰塊', 'm'],
      ['s sebou', 's SE-bou', '外帶', '片語'],
    ],
  },
  {
    id: 'fruit',
    icon: '🍎',
    name: '蔬果',
    words: [
      ['ovoce', 'O-vo-tse', '水果', 'n'],
      ['zelenina', 'ZE-le-nyi-na', '蔬菜', 'f'],
      ['jablko', 'YABL-ko', '蘋果', 'n'],
      ['banán', 'BA-naan', '香蕉', 'm'],
      ['pomeranč', 'PO-me-ranch', '柳橙', 'm'],
      ['hruška', 'HRUSH-ka', '梨子', 'f'],
      ['jahoda', 'YA-ho-da', '草莓', 'f'],
      ['hroznové víno', 'HROZ-no-vee VEE-no', '葡萄', 'n'],
      ['meloun', 'ME-loun', '西瓜、甜瓜', 'm'],
      ['citron', 'TSI-tron', '檸檬', 'm'],
      ['rajče', 'RAY-che', '番茄', 'n'],
      ['okurka', 'O-kur-ka', '小黃瓜', 'f'],
      ['mrkev', 'MR-kev', '紅蘿蔔', 'f'],
      ['cibule', 'TSI-bu-le', '洋蔥', 'f'],
      ['česnek', 'CHES-nek', '大蒜', 'm'],
      ['zelí', 'ZE-lee', '高麗菜、酸菜', 'n'],
      ['salát', 'SA-laat', '生菜、沙拉', 'm'],
      ['houba', 'HOU-ba', '香菇', 'f'],
      ['paprika', 'PAP-ri-ka', '甜椒', 'f'],
      ['brokolice', 'BRO-ko-li-tse', '花椰菜', 'f'],
    ],
  },
  {
    id: 'restaurant',
    icon: '🍽️',
    name: '餐廳',
    words: [
      ['restaurace', 'RES-tau-ra-tse', '餐廳', 'f'],
      ['hospoda', 'HOS-po-da', '啤酒館', 'f'],
      ['kavárna', 'KA-vaar-na', '咖啡廳', 'f'],
      ['jídelní lístek', 'YEE-del-nyee LEES-tek', '菜單', 'm'],
      ['číšník', 'CHEESH-nyeek', '服務生', 'm'],
      ['objednávka', 'OB-yed-naav-ka', '點的餐、訂單', 'f'],
      ['účet', 'OO-chet', '帳單', 'm'],
      ['spropitné', 'SPRO-pit-nee', '小費', 'n'],
      ['talíř', 'TA-leerzh', '盤子', 'm'],
      ['lžíce', 'LZHEE-tse', '湯匙', 'f'],
      ['vidlička', 'VID-lich-ka', '叉子', 'f'],
      ['nůž', 'noozh', '刀子', 'm'],
      ['ubrousek', 'U-brou-sek', '餐巾紙', 'm'],
      ['rezervace', 'RE-zer-va-tse', '訂位', 'f'],
      ['hlad', 'hlad', '飢餓', 'm'],
      ['žízeň', 'ZHEE-zenye', '口渴', 'f'],
      ['polední menu', 'PO-led-nyee ME-nu', '午間套餐', 'n'],
    ],
  },
  {
    id: 'home',
    icon: '🏠',
    name: '住家',
    words: [
      ['dům', 'doom', '房子', 'm'],
      ['byt', 'bit', '公寓', 'm'],
      ['pokoj', 'PO-koy', '房間', 'm'],
      ['kuchyně', 'KU-khi-nye', '廚房', 'f'],
      ['koupelna', 'KOU-pel-na', '浴室', 'f'],
      ['záchod', 'ZAA-khod', '廁所', 'm'],
      ['ložnice', 'LOZH-nyi-tse', '臥室', 'f'],
      ['obývák', 'O-bee-vaak', '客廳', 'm'],
      ['okno', 'OK-no', '窗戶', 'n'],
      ['dveře', 'DVE-rzhe', '門', 'pl'],
      ['stůl', 'stool', '桌子', 'm'],
      ['židle', 'ZHID-le', '椅子', 'f'],
      ['postel', 'POS-tel', '床', 'f'],
      ['gauč', 'gauch', '沙發', 'm'],
      ['lednice', 'LED-nyi-tse', '冰箱', 'f'],
      ['sporák', 'SPO-raak', '爐子', 'm'],
      ['pračka', 'PRACH-ka', '洗衣機', 'f'],
      ['světlo', 'SVYET-lo', '燈、光', 'n'],
      ['klíč', 'kleech', '鑰匙', 'm'],
      ['zrcadlo', 'ZR-tsad-lo', '鏡子', 'n'],
      ['skříň', 'skrzheenye', '衣櫃', 'f'],
      ['topení', 'TO-pe-nyee', '暖氣', 'n'],
      ['nájem', 'NAA-yem', '房租', 'm'],
      ['kolej', 'KO-ley', '學生宿舍', 'f'],
      ['prádelna', 'PRAA-del-na', '洗衣間', 'f'],
    ],
  },
  {
    id: 'clothes',
    icon: '👕',
    name: '衣物',
    words: [
      ['oblečení', 'OB-le-che-nyee', '衣服', 'n'],
      ['tričko', 'TRICH-ko', 'T恤', 'n'],
      ['košile', 'KO-shi-le', '襯衫', 'f'],
      ['kalhoty', 'KAL-ho-ti', '長褲', 'pl'],
      ['džíny', 'DZHEE-ni', '牛仔褲', 'pl'],
      ['sukně', 'SUK-nye', '裙子', 'f'],
      ['šaty', 'SHA-ti', '洋裝', 'pl'],
      ['svetr', 'SVE-tr', '毛衣', 'm'],
      ['bunda', 'BUN-da', '夾克', 'f'],
      ['kabát', 'KA-baat', '大衣', 'm'],
      ['boty', 'BO-ti', '鞋子', 'pl'],
      ['ponožky', 'PO-nozh-ki', '襪子', 'pl'],
      ['čepice', 'CHE-pi-tse', '帽子', 'f'],
      ['šála', 'SHAA-la', '圍巾', 'f'],
      ['rukavice', 'RU-ka-vi-tse', '手套', 'f'],
      ['batoh', 'BA-toh', '背包', 'm'],
      ['deštník', 'DESHT-nyeek', '雨傘', 'm'],
      ['brýle', 'BREE-le', '眼鏡', 'pl'],
    ],
  },
  {
    id: 'city',
    icon: '🏙️',
    name: '城市與地點',
    words: [
      ['město', 'MYES-to', '城市', 'n'],
      ['vesnice', 'VES-nyi-tse', '村莊', 'f'],
      ['ulice', 'U-li-tse', '街道', 'f'],
      ['náměstí', 'NAA-myes-tyee', '廣場', 'n'],
      ['most', 'most', '橋', 'm'],
      ['park', 'park', '公園', 'm'],
      ['obchod', 'OB-khod', '商店', 'm'],
      ['supermarket', 'SU-per-mar-ket', '超市', 'm'],
      ['banka', 'BAN-ka', '銀行', 'f'],
      ['pošta', 'POSH-ta', '郵局', 'f'],
      ['nemocnice', 'NE-mots-nyi-tse', '醫院', 'f'],
      ['lékárna', 'LEE-kaar-na', '藥局', 'f'],
      ['škola', 'SHKO-la', '學校', 'f'],
      ['kostel', 'KOS-tel', '教堂', 'm'],
      ['hrad', 'hrad', '城堡', 'm'],
      ['muzeum', 'MU-ze-um', '博物館', 'n'],
      ['divadlo', 'DYI-vad-lo', '劇院', 'n'],
      ['kino', 'KI-no', '電影院', 'n'],
      ['hotel', 'HO-tel', '旅館', 'm'],
      ['nádraží', 'NAA-dra-zhee', '火車站', 'n'],
      ['letiště', 'LE-tyish-tye', '機場', 'n'],
      ['zastávka', 'ZA-staav-ka', '站牌', 'f'],
      ['knihovna', 'KNI-hov-na', '圖書館', 'f'],
      ['úřad', 'OO-rzhad', '公家機關', 'm'],
      ['záchody', 'ZAA-kho-di', '公廁', 'pl'],
    ],
  },
  {
    id: 'transport',
    icon: '🚋',
    name: '交通',
    words: [
      ['auto', 'AU-to', '汽車', 'n'],
      ['autobus', 'AU-to-bus', '公車', 'm'],
      ['tramvaj', 'TRAM-vay', '路面電車', 'f'],
      ['metro', 'ME-tro', '地鐵', 'n'],
      ['vlak', 'vlak', '火車', 'm'],
      ['kolo', 'KO-lo', '腳踏車', 'n'],
      ['letadlo', 'LE-tad-lo', '飛機', 'n'],
      ['taxi', 'TA-ksi', '計程車', 'n'],
      ['jízdenka', 'YEEZ-den-ka', '車票', 'f'],
      ['řidič', 'RZHI-dyich', '司機', 'm'],
      ['silnice', 'SIL-nyi-tse', '道路', 'f'],
      ['semafor', 'SE-ma-for', '紅綠燈', 'm'],
      ['parkoviště', 'PAR-ko-vish-tye', '停車場', 'n'],
      ['nástupiště', 'NAA-stu-pish-tye', '月台', 'n'],
      ['odjezd', 'OD-yezd', '出發', 'm'],
      ['příjezd', 'PRZHEE-yezd', '抵達', 'm'],
      ['přestup', 'PRZHE-stup', '轉乘', 'm'],
      ['zpoždění', 'ZPOZH-dye-nyee', '誤點', 'n'],
      ['kupón', 'KU-poon', '長期票', 'm'],
      ['revizor', 'RE-vi-zor', '查票員', 'm'],
    ],
  },
  {
    id: 'school',
    icon: '🎓',
    name: '學校',
    words: [
      ['univerzita', 'U-ni-ver-zi-ta', '大學', 'f'],
      ['student', 'STU-dent', '學生', 'm'],
      ['studentka', 'STU-dent-ka', '女學生', 'f'],
      ['učitel', 'U-chi-tel', '老師', 'm'],
      ['profesor', 'PRO-fe-sor', '教授', 'm'],
      ['třída', 'TRZHEE-da', '教室、班級', 'f'],
      ['přednáška', 'PRZHED-naash-ka', '講堂課', 'f'],
      ['cvičení', 'TSVI-che-nyee', '習題課', 'n'],
      ['zkouška', 'ZKOUSH-ka', '考試', 'f'],
      ['zápočet', 'ZAA-po-chet', '平時學分認證', 'm'],
      ['semestr', 'SE-mes-tr', '學期', 'm'],
      ['předmět', 'PRZHED-myet', '科目', 'm'],
      ['úkol', 'OO-kol', '作業', 'm'],
      ['kniha', 'KNI-ha', '書', 'f'],
      ['sešit', 'SE-shit', '筆記本', 'm'],
      ['tužka', 'TUZH-ka', '鉛筆', 'f'],
      ['pero', 'PE-ro', '筆', 'n'],
      ['papír', 'PA-peer', '紙', 'm'],
      ['počítač', 'PO-chee-tach', '電腦', 'm'],
      ['rozvrh', 'ROZ-vrh', '課表', 'm'],
      ['menza', 'MEN-za', '學生餐廳', 'f'],
      ['spolužák', 'SPO-lu-zhaak', '同學', 'm'],
    ],
  },
  {
    id: 'job',
    icon: '💼',
    name: '職業與工作',
    words: [
      ['práce', 'PRAA-tse', '工作', 'f'],
      ['povolání', 'PO-vo-laa-nyee', '職業', 'n'],
      ['lékař', 'LEE-karzh', '醫生', 'm'],
      ['zdravotní sestra', 'ZDRA-vot-nyee SES-tra', '護理師', 'f'],
      ['inženýr', 'IN-zhe-neer', '工程師', 'm'],
      ['právník', 'PRAAV-nyeek', '律師', 'm'],
      ['programátor', 'PRO-gra-maa-tor', '程式設計師', 'm'],
      ['kuchař', 'KU-kharzh', '廚師', 'm'],
      ['prodavač', 'PRO-da-vach', '店員', 'm'],
      ['policista', 'PO-li-tsis-ta', '警察', 'm'],
      ['úředník', 'OO-rzhed-nyeek', '公務員', 'm'],
      ['šéf', 'sheef', '老闆', 'm'],
      ['kolega', 'KO-le-ga', '同事', 'm'],
      ['plat', 'plat', '薪水', 'm'],
      ['brigáda', 'BRI-gaa-da', '打工', 'f'],
      ['schůzka', 'SKHOOZ-ka', '會議、約', 'f'],
    ],
  },
  {
    id: 'animal',
    icon: '🐉',
    name: '動物',
    words: [
      ['zvíře', 'ZVEE-rzhe', '動物', 'n'],
      ['pes', 'pes', '狗', 'm'],
      ['kočka', 'KOCH-ka', '貓', 'f'],
      ['kůň', 'koonye', '馬', 'm'],
      ['kráva', 'KRAA-va', '牛', 'f'],
      ['prase', 'PRA-se', '豬', 'n'],
      ['ovce', 'OV-tse', '羊', 'f'],
      ['slepice', 'SLE-pi-tse', '母雞', 'f'],
      ['pták', 'ptaak', '鳥', 'm'],
      ['ryba', 'RI-ba', '魚', 'f'],
      ['myš', 'mish', '老鼠', 'f'],
      ['medvěd', 'MED-vyed', '熊', 'm'],
      ['liška', 'LISH-ka', '狐狸', 'f'],
      ['vlk', 'vlk', '狼', 'm'],
      ['drak', 'drak', '龍', 'm'],
      ['had', 'had', '蛇', 'm'],
      ['včela', 'VCHE-la', '蜜蜂', 'f'],
      ['motýl', 'MO-teel', '蝴蝶', 'm'],
      ['komár', 'KO-maar', '蚊子', 'm'],
    ],
  },
  {
    id: 'weather',
    icon: '🌦️',
    name: '天氣與自然',
    words: [
      ['počasí', 'PO-cha-see', '天氣', 'n'],
      ['slunce', 'SLUN-tse', '太陽', 'n'],
      ['déšť', 'deeshtye', '雨', 'm'],
      ['sníh', 'snyeeh', '雪', 'm'],
      ['vítr', 'VEE-tr', '風', 'm'],
      ['mrak', 'mrak', '雲', 'm'],
      ['bouřka', 'BOURZH-ka', '雷雨', 'f'],
      ['mlha', 'MLHA', '霧', 'f'],
      ['teplo', 'TEP-lo', '溫暖', 'n'],
      ['horko', 'HOR-ko', '炎熱', 'n'],
      ['led', 'led', '冰', 'm'],
      ['obloha', 'OB-lo-ha', '天空', 'f'],
      ['hvězda', 'HVYEZ-da', '星星', 'f'],
      ['strom', 'strom', '樹', 'm'],
      ['les', 'les', '森林', 'm'],
      ['hora', 'HO-ra', '山', 'f'],
      ['řeka', 'RZHE-ka', '河', 'f'],
      ['jezero', 'YE-ze-ro', '湖', 'n'],
      ['moře', 'MO-rzhe', '海', 'n'],
      ['květina', 'KVYE-tyi-na', '花', 'f'],
      ['příroda', 'PRZHEE-ro-da', '大自然', 'f'],
      ['stupňů', 'STUP-nyoo', '度（溫度）', 'pl'],
    ],
  },
  {
    id: 'adjective',
    icon: '🔠',
    name: '常用形容詞',
    words: [
      ['dobrý', 'DOB-ree', '好的', '形容詞'],
      ['špatný', 'SHPAT-nee', '壞的', '形容詞'],
      ['velký', 'VEL-kee', '大的', '形容詞'],
      ['malý', 'MA-lee', '小的', '形容詞'],
      ['nový', 'NO-vee', '新的', '形容詞'],
      ['starý', 'STA-ree', '舊的、老的', '形容詞'],
      ['mladý', 'MLA-dee', '年輕的', '形容詞'],
      ['dlouhý', 'DLOU-hee', '長的', '形容詞'],
      ['krátký', 'KRAAT-kee', '短的', '形容詞'],
      ['vysoký', 'VI-so-kee', '高的', '形容詞'],
      ['nízký', 'NYEEZ-kee', '低的', '形容詞'],
      ['rychlý', 'RIKH-lee', '快的', '形容詞'],
      ['pomalý', 'PO-ma-lee', '慢的', '形容詞'],
      ['teplý', 'TEP-lee', '溫暖的', '形容詞'],
      ['studený', 'STU-de-nee', '冷的', '形容詞'],
      ['drahý', 'DRA-hee', '貴的', '形容詞'],
      ['levný', 'LEV-nee', '便宜的', '形容詞'],
      ['těžký', 'TYESH-kee', '重的、難的', '形容詞'],
      ['lehký', 'LEH-kee', '輕的、容易的', '形容詞'],
      ['krásný', 'KRAAS-nee', '美麗的', '形容詞'],
      ['hezký', 'HEZ-kee', '好看的', '形容詞'],
      ['čistý', 'CHIS-tee', '乾淨的', '形容詞'],
      ['špinavý', 'SHPI-na-vee', '髒的', '形容詞'],
      ['plný', 'PLNEE', '滿的', '形容詞'],
      ['prázdný', 'PRAAZD-nee', '空的', '形容詞'],
      ['šťastný', 'SHTYAST-nee', '快樂的', '形容詞'],
      ['smutný', 'SMUT-nee', '難過的', '形容詞'],
      ['unavený', 'U-na-ve-nee', '疲倦的', '形容詞'],
      ['nemocný', 'NE-mots-nee', '生病的', '形容詞'],
      ['zdravý', 'ZDRA-vee', '健康的', '形容詞'],
      ['hladový', 'HLA-do-vee', '飢餓的', '形容詞'],
      ['důležitý', 'DOO-le-zhi-tee', '重要的', '形容詞'],
      ['zajímavý', 'ZA-yee-ma-vee', '有趣的', '形容詞'],
      ['nudný', 'NUD-nee', '無聊的', '形容詞'],
      ['jiný', 'YI-nee', '不同的、別的', '形容詞'],
      ['stejný', 'STEY-nee', '一樣的', '形容詞'],
    ],
  },
  {
    id: 'verb',
    icon: '🏃',
    name: '常用動詞',
    words: [
      ['být', 'beet', '是（jsem／jsi／je）', '動詞'],
      ['mít', 'meet', '有（mám／máš／má）', '動詞'],
      ['dělat', 'DYE-lat', '做（dělám）', '動詞'],
      ['jít', 'yeet', '走路去（jdu）', '動詞'],
      ['jet', 'yet', '搭車去（jedu）', '動詞'],
      ['přijít', 'PRZHI-yeet', '來、抵達', '動詞'],
      ['vidět', 'VI-dyet', '看見（vidím）', '動詞'],
      ['slyšet', 'SLI-shet', '聽見（slyším）', '動詞'],
      ['mluvit', 'MLU-vit', '說（mluvím）', '動詞'],
      ['říct', 'rzheetst', '說出、告訴（řeknu）', '動詞'],
      ['ptát se', 'ptaat se', '問（ptám se）', '動詞'],
      ['odpovědět', 'OD-po-vye-dyet', '回答', '動詞'],
      ['rozumět', 'RO-zu-myet', '理解（rozumím）', '動詞'],
      ['vědět', 'VYE-dyet', '知道（vím）', '動詞'],
      ['znát', 'znaat', '認識（znám）', '動詞'],
      ['myslet', 'MIS-let', '想、認為（myslím）', '動詞'],
      ['chtít', 'khtyeet', '想要（chci／chceš）', '動詞'],
      ['moct', 'motst', '能夠（můžu）', '動詞'],
      ['muset', 'MU-set', '必須（musím）', '動詞'],
      ['umět', 'U-myet', '會（umím）', '動詞'],
      ['jíst', 'yeest', '吃（jím）', '動詞'],
      ['pít', 'peet', '喝（piju）', '動詞'],
      ['spát', 'spaat', '睡（spím）', '動詞'],
      ['vstávat', 'VSTAA-vat', '起床', '動詞'],
      ['sedět', 'SE-dyet', '坐著', '動詞'],
      ['stát', 'staat', '站著／值多少錢', '動詞'],
      ['koupit', 'KOU-pit', '買', '動詞'],
      ['prodat', 'PRO-dat', '賣', '動詞'],
      ['platit', 'PLA-tit', '付錢', '動詞'],
      ['dát', 'daat', '給', '動詞'],
      ['vzít', 'vzeet', '拿、取', '動詞'],
      ['psát', 'psaat', '寫（píšu）', '動詞'],
      ['číst', 'cheest', '讀（čtu）', '動詞'],
      ['učit se', 'U-chit se', '學習（učím se）', '動詞'],
      ['pracovat', 'PRA-tso-vat', '工作（pracuju）', '動詞'],
      ['hrát', 'hraat', '玩、演奏（hraju）', '動詞'],
      ['zpívat', 'ZPEE-vat', '唱歌', '動詞'],
      ['tančit', 'TAN-chit', '跳舞', '動詞'],
      ['běžet', 'BYE-zhet', '跑', '動詞'],
      ['plavat', 'PLA-vat', '游泳', '動詞'],
      ['otevřít', 'O-tev-rzheet', '打開', '動詞'],
      ['zavřít', 'ZAV-rzheet', '關上', '動詞'],
      ['začít', 'ZA-cheet', '開始', '動詞'],
      ['skončit', 'SKON-chit', '結束', '動詞'],
      ['pomoct', 'PO-motst', '幫忙', '動詞'],
      ['čekat', 'CHE-kat', '等（čekám）', '動詞'],
      ['hledat', 'HLE-dat', '找（hledám）', '動詞'],
      ['najít', 'NA-yeet', '找到', '動詞'],
      ['ztratit', 'ZTRA-tit', '弄丟', '動詞'],
      ['milovat', 'MI-lo-vat', '愛', '動詞'],
      ['líbit se', 'LEE-bit se', '喜歡（líbí se mi）', '動詞'],
      ['potřebovat', 'PO-trzhe-bo-vat', '需要（potřebuju）', '動詞'],
      ['bydlet', 'BID-let', '居住（bydlím）', '動詞'],
      ['žít', 'zheet', '生活、活著', '動詞'],
      ['cestovat', 'TSES-to-vat', '旅行', '動詞'],
      ['vařit', 'VA-rzhit', '煮飯', '動詞'],
      ['uklízet', 'U-klee-zet', '打掃', '動詞'],
      ['zavolat', 'ZA-vo-lat', '打電話、叫（人）', '動詞'],
      ['zapomenout', 'ZA-po-me-nout', '忘記', '動詞'],
      ['pamatovat si', 'PA-ma-to-vat si', '記得', '動詞'],
    ],
  },
  {
    id: 'question',
    icon: '❓',
    name: '疑問詞',
    words: [
      ['kdo', 'kdo', '誰', '疑問詞'],
      ['co', 'tso', '什麼', '疑問詞'],
      ['kde', 'kde', '在哪裡', '疑問詞'],
      ['kam', 'kam', '去哪裡', '疑問詞'],
      ['odkud', 'OD-kud', '從哪裡', '疑問詞'],
      ['kdy', 'kdi', '什麼時候', '疑問詞'],
      ['jak', 'yak', '怎麼樣', '疑問詞'],
      ['proč', 'proch', '為什麼', '疑問詞'],
      ['kolik', 'KO-lik', '多少', '疑問詞'],
      ['který', 'KTE-ree', '哪一個', '疑問詞'],
      ['jaký', 'YA-kee', '什麼樣的', '疑問詞'],
    ],
  },
  {
    id: 'adverb',
    icon: '🔗',
    name: '副詞與連接詞',
    words: [
      ['a', 'a', '和', '連接詞'],
      ['ale', 'A-le', '但是', '連接詞'],
      ['nebo', 'NE-bo', '或者', '連接詞'],
      ['protože', 'PRO-to-zhe', '因為', '連接詞'],
      ['když', 'kdizh', '當……的時候', '連接詞'],
      ['jestli', 'YEST-li', '如果', '連接詞'],
      ['taky', 'TA-ki', '也', '副詞'],
      ['jenom', 'YE-nom', '只有', '副詞'],
      ['už', 'uzh', '已經', '副詞'],
      ['ještě', 'YESH-tye', '還、再', '副詞'],
      ['moc', 'mots', '很、太', '副詞'],
      ['trochu', 'TRO-khu', '一點點', '副詞'],
      ['hodně', 'HOD-nye', '很多', '副詞'],
      ['málo', 'MAA-lo', '很少', '副詞'],
      ['vždycky', 'VZHDITS-ki', '總是', '副詞'],
      ['nikdy', 'NYIK-di', '從不', '副詞'],
      ['často', 'CHAS-to', '常常', '副詞'],
      ['někdy', 'NYEK-di', '有時候', '副詞'],
      ['možná', 'MOZH-naa', '也許', '副詞'],
      ['určitě', 'UR-chi-tye', '一定', '副詞'],
      ['bohužel', 'BO-hu-zhel', '可惜', '副詞'],
      ['samozřejmě', 'SA-mo-zrzhey-mnye', '當然', '副詞'],
      ['spolu', 'SPO-lu', '一起', '副詞'],
      ['znovu', 'ZNO-vu', '再一次', '副詞'],
    ],
  },
  {
    id: 'place',
    icon: '🧭',
    name: '介系詞與方位',
    words: [
      ['v', 'v', '在……裡（第六格）', '介系詞'],
      ['na', 'na', '在……上／去（第四／六格）', '介系詞'],
      ['do', 'do', '進入、到（第二格）', '介系詞'],
      ['z', 'z', '從……出來（第二格）', '介系詞'],
      ['od', 'od', '從（某人／某時）', '介系詞'],
      ['k', 'k', '朝向（第三格）', '介系詞'],
      ['u', 'u', '在……旁邊（第二格）', '介系詞'],
      ['s', 's', '和……一起（第七格）', '介系詞'],
      ['bez', 'bez', '沒有（第二格）', '介系詞'],
      ['pro', 'pro', '為了（第四格）', '介系詞'],
      ['před', 'przhed', '在……前面', '介系詞'],
      ['za', 'za', '在……後面', '介系詞'],
      ['nad', 'nad', '在……上方', '介系詞'],
      ['pod', 'pod', '在……下方', '介系詞'],
      ['mezi', 'ME-zi', '在……之間', '介系詞'],
      ['vedle', 'VED-le', '在……旁邊', '介系詞'],
      ['blízko', 'BLEEZ-ko', '靠近', '副詞'],
      ['daleko', 'DA-le-ko', '遠', '副詞'],
      ['vlevo', 'VLE-vo', '在左邊', '副詞'],
      ['vpravo', 'VPRA-vo', '在右邊', '副詞'],
      ['rovně', 'ROV-nye', '直走', '副詞'],
      ['nahoře', 'NA-ho-rzhe', '在上面', '副詞'],
      ['dole', 'DO-le', '在下面', '副詞'],
      ['tady', 'TA-di', '這裡', '副詞'],
      ['tam', 'tam', '那裡', '副詞'],
    ],
  },
  {
    id: 'shopping',
    icon: '🛒',
    name: '購物與金錢',
    words: [
      ['peníze', 'PE-nyee-ze', '錢', 'pl'],
      ['koruna', 'KO-ru-na', '克朗', 'f'],
      ['cena', 'TSE-na', '價格', 'f'],
      ['sleva', 'SLE-va', '折扣', 'f'],
      ['výprodej', 'VEE-pro-dey', '出清特賣', 'm'],
      ['karta', 'KAR-ta', '卡片、信用卡', 'f'],
      ['hotovost', 'HO-to-vost', '現金', 'f'],
      ['účtenka', 'OOCH-ten-ka', '收據', 'f'],
      ['taška', 'TASH-ka', '袋子', 'f'],
      ['velikost', 'VE-li-kost', '尺寸', 'f'],
      ['bankomat', 'BAN-ko-mat', '提款機', 'm'],
      ['poplatek', 'PO-pla-tek', '手續費', 'm'],
      ['zdarma', 'ZDAR-ma', '免費', '副詞'],
      ['vrátit', 'VRAA-tit', '退還', '動詞'],
      ['zkusit si', 'ZKU-sit si', '試穿', '動詞'],
      ['kolik to stojí', 'KO-lik to STO-yee', '這多少錢', '片語'],
    ],
  },
  {
    id: 'health',
    icon: '💊',
    name: '健康與求助',
    words: [
      ['zdraví', 'ZDRA-vee', '健康', 'n'],
      ['nemoc', 'NE-mots', '疾病', 'f'],
      ['bolest', 'BO-lest', '疼痛', 'f'],
      ['horečka', 'HO-rech-ka', '發燒', 'f'],
      ['kašel', 'KA-shel', '咳嗽', 'm'],
      ['rýma', 'REE-ma', '流鼻水', 'f'],
      ['chřipka', 'KHRZHIP-ka', '流感', 'f'],
      ['lék', 'leek', '藥', 'm'],
      ['recept', 'RE-tsept', '處方箋', 'm'],
      ['doktor', 'DOK-tor', '醫生', 'm'],
      ['pohotovost', 'PO-ho-to-vost', '急診', 'f'],
      ['alergie', 'A-ler-gi-ye', '過敏', 'f'],
      ['úraz', 'OO-raz', '受傷', 'm'],
      ['pojišťovna', 'PO-yish-tyov-na', '保險公司', 'f'],
      ['záchranka', 'ZAA-khran-ka', '救護車', 'f'],
      ['pomoc', 'PO-mots', '幫助、救命', 'f'],
      ['nebezpečí', 'NE-bez-pe-chee', '危險', 'n'],
      ['pozor', 'PO-zor', '小心！', '感嘆'],
    ],
  },
  {
    id: 'tech',
    icon: '📱',
    name: '科技與網路',
    words: [
      ['telefon', 'TE-le-fon', '電話', 'm'],
      ['mobil', 'MO-bil', '手機', 'm'],
      ['počítač', 'PO-chee-tach', '電腦', 'm'],
      ['notebook', 'NOT-buk', '筆電', 'm'],
      ['internet', 'IN-ter-net', '網路', 'm'],
      ['wifi', 'VI-fi', 'wifi', 'f'],
      ['heslo', 'HES-lo', '密碼', 'n'],
      ['e-mail', 'EE-mayl', '電子郵件', 'm'],
      ['aplikace', 'A-pli-ka-tse', '應用程式', 'f'],
      ['nabíječka', 'NA-bee-yech-ka', '充電器', 'f'],
      ['obrazovka', 'O-bra-zov-ka', '螢幕', 'f'],
      ['zpráva', 'ZPRAA-va', '訊息', 'f'],
      ['fotka', 'FOT-ka', '照片', 'f'],
      ['stáhnout', 'STAAH-nout', '下載', '動詞'],
    ],
  },
  {
    id: 'feeling',
    icon: '💗',
    name: '情緒與個性',
    words: [
      ['radost', 'RA-dost', '喜悅', 'f'],
      ['štěstí', 'SHTYES-tyee', '幸福、運氣', 'n'],
      ['smutek', 'SMU-tek', '悲傷', 'm'],
      ['strach', 'strakh', '害怕', 'm'],
      ['vztek', 'vztek', '生氣', 'm'],
      ['láska', 'LAAS-ka', '愛', 'f'],
      ['klid', 'klid', '平靜', 'm'],
      ['nervózní', 'NER-vooz-nyee', '緊張的', '形容詞'],
      ['veselý', 'VE-se-lee', '開朗的', '形容詞'],
      ['milý', 'MI-lee', '親切的', '形容詞'],
      ['hodný', 'HOD-nee', '乖的、善良的', '形容詞'],
      ['tichý', 'TYI-khee', '安靜的', '形容詞'],
      ['hlučný', 'HLUCH-nee', '吵鬧的', '形容詞'],
      ['líný', 'LEE-nee', '懶惰的', '形容詞'],
      ['chytrý', 'KHIT-ree', '聰明的', '形容詞'],
      ['zvědavý', 'ZVYE-da-vee', '好奇的', '形容詞'],
      ['trpělivý', 'TR-pye-li-vee', '有耐心的', '形容詞'],
      ['stydlivý', 'STID-li-vee', '害羞的', '形容詞'],
    ],
  },
  {
    id: 'admin',
    icon: '📄',
    name: '行政與文件',
    words: [
      ['úřad', 'OO-rzhad', '公家機關', 'm'],
      ['formulář', 'FOR-mu-laarzh', '表格', 'm'],
      ['žádost', 'ZHAA-dost', '申請書', 'f'],
      ['podpis', 'POD-pis', '簽名', 'm'],
      ['razítko', 'RA-zeet-ko', '印章', 'n'],
      ['průkaz', 'PROO-kaz', '證件', 'm'],
      ['pas', 'pas', '護照', 'm'],
      ['vízum', 'VEE-zum', '簽證', 'n'],
      ['povolení', 'PO-vo-le-nyee', '許可', 'n'],
      ['pobyt', 'PO-bit', '居留', 'm'],
      ['potvrzení', 'PO-tvr-ze-nyee', '證明文件', 'n'],
      ['termín', 'TER-meen', '預約時段、期限', 'm'],
      ['cizinec', 'TSI-zi-nets', '外國人', 'm'],
      ['adresa', 'A-dre-sa', '地址', 'f'],
      ['smlouva', 'SMLOU-va', '合約', 'f'],
    ],
  },
  {
    id: 'leisure',
    icon: '⚽',
    name: '休閒與嗜好',
    words: [
      ['volný čas', 'VOL-nee chas', '空閒時間', 'm'],
      ['sport', 'sport', '運動', 'm'],
      ['fotbal', 'FOT-bal', '足球', 'm'],
      ['hokej', 'HO-key', '冰球（國球）', 'm'],
      ['běh', 'byeh', '跑步', 'm'],
      ['turistika', 'TU-ris-ti-ka', '健行', 'f'],
      ['výlet', 'VEE-let', '小旅行', 'm'],
      ['dovolená', 'DO-vo-le-naa', '假期', 'f'],
      ['film', 'film', '電影', 'm'],
      ['hudba', 'HUD-ba', '音樂', 'f'],
      ['koncert', 'KON-tsert', '演唱會', 'm'],
      ['hra', 'hra', '遊戲', 'f'],
      ['festival', 'FES-ti-val', '節慶', 'm'],
      ['zábava', 'ZAA-ba-va', '樂趣、娛樂', 'f'],
      ['procházka', 'PRO-khaaz-ka', '散步', 'f'],
    ],
  },
];

/** 去掉附加符號（háček／čárka）後轉成安全的 id 片段 */
function slug(text) {
  return text
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

/** 攤平成單字卡／測驗共用的格式；順序＝教學順序 */
export const CZ_VOCAB = CZ_CATEGORIES.flatMap((category) =>
  category.words.map(([term, pron, zh, pos]) => ({
    id: `cs-v-${category.id}-${slug(term)}`,
    lang: 'cs',
    term,
    pron,
    zh,
    pos: pos || '',
    cat: category.name,
    catId: category.id,
  })),
);

